### ISSUE TITLE
Rewrite remote user from local database

### ISSUE THREAD

**Issue by rcgraves** [zmartzone/mod_auth_openidc#219]
Pretty sure this is a won'tfix, but looking for ideas.

I would like to allow users to log on as local username with registered external identities. I have a way for local username jdoe to assert that they are doej@gmail.com. I would like to store that mapping in LDAP (or SQL or some IPC, but regex won't do) and have a successful OIDC login as doej@gmail.com propagate REMOTE_USER=doej.

This can be done by using something like simplesamlphp or gluu or ping as a "proxy idp" but that's a lot of code. Ideas to flatten/combine those layers?

Yes we would constrain the domains and OIDC providers to limit spoofing. gmail.com, hotmail.com, outlook.com, aol.com (yes still) would cover almost everyone.

**Comment by zandbelt** [comment]
If that mapping was available through a REST/JSON call then that would make the implementation relatively straightforward and may in fact be configurable today by pointing `OIDCProviderUserInfoEndpoint` to that API instead of the one provided by the Provider (assuming that the Provider puts all claims in the `id_token` directly because its userinfo endpoint will now no longer be called).

**Comment by rcgraves** [comment]
We could certainly make a simple REST/JSON to LDAP gateway.
OIDCProviderUserInfoEndpoint has a lot of promise, but the input is
going to be an opaque ID, right? We'd actually need the input to be
email because we're bootstrapping from email forwarding (not always a
good assumption, but it's low risk data). I guess we could
man-in-the-middle it, our code calling the actual endpoint to map ID
to email, then we map email to username.

**Comment by zandbelt** [comment]
you are right, also about the possible way forward though it all feels a bit hacky

**Comment by zandbelt** [comment]
actually one can use `RewriteMap` to implement this kind of functionality, see https://github.com/zmartzone/mod_auth_openidc/issues/198
