### ISSUE TITLE
# in the request URL causing user to redirect to different URL

### ISSUE THREAD

**Issue by abhishekraghav** [zmartzone/mod_auth_openidc#312]
Hi Hanz,

First of all thanks for such an amazing plugin.
Everything works perfectly fine except one use case i am describing below.

I am protecting an angular app which is registered as an confidential app in keycloak. The typical login flow works as expected which is the user clicks on login, redirected to keycloak auth URL, gets authenticated and redirected to dashboard.

Now i have a use case where i am sending emails to the users which contains a URL to a specific report location and that URL contains a "#" pound sign in the URL. e.g.
http://<FQDN>/app/landing.html#/report/list/1234

Now when a user clicks on this link.

- User is redirected to keycloak login page since /app/landing.html is protected in mod-auth conf.
- User enters the userid/password 
- User is redirected to just **http://<FQDN>/app/landing.html** instead of the original URL which was **http://<FQDN>/app/landing.html#/report/list/1234**

The URL fragment which contains # (i.e. #/report/list/1234) is lost once the user redirects back to app once he is authenticated on keycloak. I more point to note is, once the user is redirected to auth URL, i see that the keycloak auth URL still contains that URL fragment i.e only #/report/list/1234

I have a strong feeling, its not a bug/issue on mod_auth_openidc. it could be a limitation from a browser agent side as well that doesn't respect if the original URL contains a "#" in it and if there is login redirect occurs.

I am just handling security to an angular app so please pardon to my limited knowledge on angular. In angular world, URL fragments represent routes to the app. but if they becomes the original URL(entrypoint), may be because of a user bookmarked that link or static links send to the user through email. This causes URL redirecting to a different URL instead of where the URL should actually be.

Please help if you have any clue whats happening here. I am just clueless. 

platform Ubuntu
mod-auth-version  2.3
Application protected type Angular JS
Auth server  keycloak

Expected behaviour

User should be redirected to the actual URL which a user enters in the browser

###### Actual behaviour
The part of the URL is trimmed after authentication and user is redirected to the dashboard instead of that specific link.

Thanks.
Abhishek

**Comment by zandbelt** [comment]
If you can provide server side debug logs that should show whether it is mod_auth_openidc, Keycloack or the browser stripping the hash from the URL. In general I should mention that the fragment gets stripped by the browser and is never sent to the server which means that mod_auth_openidc would never see it (as opposed to what you seem to suggest). Anyhow, server side debug logs ("LogLevel auth_openidc:debug") should tell you what happens.

**Comment by zandbelt** [comment]
Thinking this through a bit more...: by the time your browser hits mod_auth_openidc, it should have already stripped the hash fragment so the scenario you describe cannot work. See e.g.: https://stackoverflow.com/questions/9384373/do-browsers-remove-in-url-automatically

**Comment by abhishekraghav** [comment]
Thanks Hanz, I understood the issue. It’s a browser limitation. I have also verified the mod-auth logs as suggested by you and it simply has a trimmed request URL without the fragment.
So we will have to look for a way to somehow pass this in a different way and then append it back once the authentication is successful. 

Thanks for your quick support.

**Comment by rajanjha786** [comment]
Hi abhishekraghav did you find out the way?
