### ISSUE TITLE
mod_auth_openidc

### ISSUE THREAD

**Issue by Raghu037** [zmartzone/mod_auth_openidc#314]
I could not find module for AIX. Could you please suggest which one should i pick for IBM AIX.. 

###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro (e.g. Ubuntu Xenial or Centos 7)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
There's no pre-compiled module for AIX. You can discuss options for obtaining one through commercial support via info@zmartzone.eu
