### ISSUE TITLE
R

### ISSUE THREAD

**Issue by mdelorimier** [zmartzone/mod_auth_openidc#316]
###### Environment

- mod_auth_openidc version (e.g. 2.3.3)
- Apache version (e.g. 2.4.29)
- platform/distro (Centos 7)

###### Expected behaviour
Get a refresh token in the headers when first authorizing the app for an account (Google/GSuite Account)

###### Actual behaviour
Not getting a refresh token whit the following options enabled, i am also getting an error (refresh_failed) while trying to refresh the access token with the following url : 

    auth?refresh=<return_to>&access_token=<access_token>

###### Minimized example

```
OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID ---
OIDCClientSecret ---

OIDCRedirectURI http://centos.localhost.com/auth
OIDCCryptoPassphrase ---
OIDCScope "openid email https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/userinfo.email"

OIDCAuthRequestParams hd=---&prompt=consent
OIDCSessionType server-cache:persistent
OIDCStateTimeout 86400
OIDCSessionMaxDuration 86400
OIDCSessionInactivityTimeout 86400

OIDCOAuthTokenIntrospectionInterval 3600
OIDCInfoHook iat access_token access_token_expires id_token userinfo refresh_token session

<Location />
AuthType openid-connect
Require claim ---.com
OIDCPassRefreshToken On
</Location>
</VirtualHost>
```

###### Configuration and Log files

```
[Wed Dec 06 14:52:51.271779 2017] [auth_openidc:warn] [pid 12075] [client 192.168.10.175:56729] oidc_refresh_access_token: refresh token routine called but no refresh_token found in the sessio                                       n
[Wed Dec 06 14:52:51.271808 2017] [auth_openidc:error] [pid 12075] [client 192.168.10.175:56729] oidc_handle_refresh_token_request: access_token could not be refreshed
```

**Comment by zandbelt** [comment]
That's because Google only returns a refresh token for the very first time that a Client goes though the authentication flow after registering. See: https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token

Since there's no refresh token stored in the session, you cannot refresh it either.

**Comment by mdelorimier** [comment]
Thanks for the fast response.

I have tried to unregister the application and do the process again and
still no refresh token. Also, prompt consent should always return a refresh
token from what I have seen in the docs.

Le jeu. 7 déc. 2017 02:36, Hans Zandbelt <notifications@github.com> a
écrit :

**Comment by zandbelt** [comment]
You can find out from the logs (LogLevel debug) whether a refresh token is returned. I don't think `prompt=consent` makes a difference but `access_type=offline` may.

**Comment by mdelorimier** [comment]
Will try that, thank you very much

Le jeu. 7 déc. 2017 06:56, Hans Zandbelt <notifications@github.com> a
écrit :

**Comment by mdelorimier** [comment]
After testing, it seems adding ```access_type=offline``` AND ```prompt=consent``` works. One question i have and that i don't see in the documentation is : will the refreshing of the token be done with the client being redirected to the provider or is it done in parallel by the server?

Also, i have tryed without ```access_type=offline``` and unassociating the app with my google account but still don't get a refresh token. One thing to note is that I have 2 factor authentication enabled. Could this be what is causing the refresh token to be missing?

**Comment by zandbelt** [comment]
those are really questions for Google

**Comment by mdelorimier** [comment]
Agreed for the extra params part.

Regarding the access token refreshing process, can you confirm this is done without redirecting the client? From reading the code that is how I see it happening.

Also, is it normal that the access token expiry provided by the module is not the same as the actual expiry of the access token?

**Comment by zandbelt** [comment]
Refreshing the access token can be done with the Refresh grant, i.e. without redirect. Of course the provider must support that grant.

There's no access token expiry provided by the module itself other than a header/envvar based on the `expires_in` value returned by the OP.

**Comment by zandbelt** [comment]
it is just what the Provider gives back, in both cases

**Comment by mdelorimier** [comment]
Ok, thanks for the great support :)
