### ISSUE TITLE
oidc_jwt_verify not validating for JWT generated with Auth0

### ISSUE THREAD

**Issue by rd0nz** [zmartzone/mod_auth_openidc#318]
Using various endpoints from Auth0 in order to implement authentication on a SPA. 

The SPA utilizes some webservices, which are proxied by Apache - backend services are implemented in .NET Core and running on Kestrel. Apache plays a key-role as API gateway.

Right now trying to get mod_auth_openidc working with local JWT validation. Auth0 is somewhat difficult to implement using Token Introspection and besides that - when switching to AuthType openid-connect, the session cookie never gets set - so local JWT validation is somewhat of a last resort already.

Auth0 has been configured fine, after signing-in a Bearer JWT gets generated, thanks to the OIDCResponseType. Now when trying to utilize the token in my requests to the APIs, I constantly get a 401. `www-authenticate →Bearer error="invalid_token", error_description="JWT token could not be validated`

According to the ErrorLog, jose.c can't find the KID in the JWT. When validating the JWT online at http://jwt.io together with my public key certificate (PEM), the JWT always validates. 

Note that in the log file, the acual JWT has been left out due to some sensitive info.

###### Environment

- mod_auth_openidc-2.3.3-apache-2.4.x-win64
- Apache 2.4.29 64 bits version
- Windows Server 2016 Datacenter

###### Minimized example
1. configure Apache with mod_auth_oidc on a 64bit Windows
2. configure an Auth0 account
3. configure the OIDC and OAuth parts, declaring some secure Locations
4. start the OIDC handshake, utilizing response_type token
5. try entering the secure Locations using the JWT

###### Configuration and Log files

Partial httpd config:

```
ProxyPass			/api/custody	http://localhost:5011/custody

OIDCResponseType		"code id_token token"
OIDCProviderMetadataURL		https://SPACE.auth0.com/.well-known/openid-configuration

OIDCScope 			"openid email profile"
OIDCRedirectURI 		https://www.DOMAIN.com/auth/callback
OIDCCryptoPassphrase 		somepasswordblabla

OIDCOAuthVerifyCertFiles	"c:\Services\Apache24\bin\certificate.pem"

<Location /auth/signin>
  AuthType 	auth-openidc  
  Require 	valid-user
  LogLevel	Debug
</Location>
	
<LocationMatch "^/api">
  AuthType 		auth-openidc 
  Require 		valid-user
  OIDCUnAuthAction 	401
  LogLevel		Debug
</LocationMatch>
```

```
[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] oauth.c(185): [client 179.236.169.27:27903] oidc_oauth_get_bearer_token: bearer token: XXX

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] oauth.c(480): [client 179.236.169.27:27903] oidc_oauth_validate_jwt_access_token: enter: JWT access_token header={"typ":"JWT","alg":"RS256","kid":"NzA3QTZEQjM5NEQxRkU4MzZDOTAwOUM3N0I4RTA3RDgzRUEzMEI5MQ"}

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] util.c(1995): [client 179.236.169.27:27903] oidc_util_create_symmetric_key: key_len=34

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] oauth.c(499): [client 179.236.169.27:27903] oidc_oauth_validate_jwt_access_token: successfully parsed JWT with header: {"typ":"JWT","alg":"RS256","kid":"NzA3QTZEQjM5NEQxRkU4MzZDOTAwOUM3N0I4RTA3RDgzRUEzMEI5MQ"}

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] proto.c(1230): [client 179.236.169.27:27903] oidc_proto_validate_iat: slack for JWT set < 0, do not enforce boundary check

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] oauth.c(516): [client 179.236.169.27:27903] oidc_oauth_validate_jwt_access_token: verify JWT against 1 statically configured public keys and 0 shared keys, with JWKs URI set to (null)

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:debug] [pid 3684:tid 1212] proto.c(1525): [client 179.236.169.27:27903] oidc_proto_jwt_verify: "jwks_uri" is not set, signature validation will only be performed against statically configured keys

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:error] [pid 3684:tid 1212] [client 179.236.169.27:27903] oidc_proto_jwt_verify: JWT signature verification failed: [src\\jose.c:924: oidc_jwt_verify]: could not find key with kid: NzA3QTZEQjM5NEQxRkU4MzZDOTAwOUM3N0I4RTA3RDgzRUEzMEI5MQ\n

[Thu Dec 28 08:22:22.144926 2017] [auth_openidc:error] [pid 3684:tid 1212] [client 179.236.169.27:27903] oidc_oauth_validate_jwt_access_token: JWT access token signature could not be validated, aborting
```

**Comment by zandbelt** [comment]
If a `kid` is used in the JWT header you'll need to specify that same `kid` in the configuration as follows:
```
OIDCOAuthVerifyCertFiles NzA3QTZEQjM5NEQxRkU4MzZDOTAwOUM3N0I4RTA3RDgzRUEzMEI5MQ#c:\Services\Apache24\bin\certificate.pem
```
As an enhancement, I guess if there's only one key configured, mod_auth_openidc could just try that.

**Comment by rd0nz** [comment]
Right! Totally missed that. Seems not to be a bug after all then.

Thanks for the help...
