### ISSUE TITLE
oidc_util_jwt_create: signing JWT failed on Mac OSX highSierra 10.12.6

### ISSUE THREAD

**Issue by coderPapu** [zmartzone/mod_auth_openidc#319]
Trying to use this In apache 2.4.25 running on Mac OSX highSierra 10.12.6.
Got it compile to create mod_auth_openidc.so
Used in a httpd conf as a sample.

LoadModule auth_openidc_module libexec/apache2/mod_auth_openidc.so

OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID xxxxx
OIDCClientSecret xxxxx
OIDCRedirectURI http://localhost/secure-app/index.jsp

OIDCResponseType code
OIDCScope "openid email"
OIDCCryptoPassphrase example@3003
OIDCAuthNHeader REMOTE_USER
OIDCClaimPrefix USERINFO_

<Location /secure-app/ >
   AuthType openid-connect
   Require valid-user
   LogLevel debug
</Location>

In browser when the url is https://localhost/secure-app/welcome.jsp it gives "Internal Server Error"
the apache error logs show

[auth_openidc:error] [pid 13714] [client 127.0.0.1:52446] oidc_util_jwt_create: signing JWT failed: [src/jose.c:834: oidc_jwt_sign]: cjose_jws_sign failed: invalid argument [file: jws.c, function: _cjose_jws_validate_hdr, line: 77]\n\n
 
Any clue will be appreciated. Thx.

(the cjose installed is CJOSE_VERSION "0.5.1")

###### Environment

- mod_auth_openidc version (e.g. 2.2.3)
- Apache version (e.g. 2.4.25)
- platform/distro (Mac OSX highSierra 10.12.6)

**Comment by zandbelt** [comment]
I'm going to have to blame your compilation process of mod_auth_openidc or libcjose because I'm running on basically the same platform 10.13.2 without any problems. I'm using Macports. Can you provide more insight into how you compiled cjose/mod_auth_openidc?

**Comment by coderPapu** [comment]
Hans, I used the default cjose. using 'brew install cjose' and Im not using Macports.
I followed http://lifewithcode.blogspot.com/2016/10/securing-apache-on-osx-using.html
which talks about compiling cjose. My brew install jose went well hence I didnt go for compiling it. After creating this ticket I saw mod_auth_openidc release 2.3.2 is talking about a custom fixed cjose zip. May be I have take that and compile it? If so I accept the blame and once verified I will close / delete the ticket :)
Thank you.

**Comment by zandbelt** [comment]
it is not cjose: version 0.5.1 is OK to use; it couldn't have come from brew AFAIK; the article that you link to says that it is not available there

the error suggests that "alg" is not set:
https://github.com/cisco/cjose/blob/master/src/jws.c#L77

but the `oidc_util_jwt_create` method from mod_auth_openidc (where the error originates) shows that's not the case:
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/util.c#L176
unless there's some linking problem (which I suspect now) so that CJOSE_HDR_ALG_DIR doesn't exist

**Comment by zandbelt** [comment]
Were you able to make any progress with this? Did you compile cjose on the same environment?
