### ISSUE TITLE
Iframes checking for user cookie changes should log to info/debug

### ISSUE THREAD

**Issue by kerrermanisNL** [zmartzone/mod_auth_openidc#322]
If you're running the the OpenID Connect Session Management feature you have to load in two iframes that check for changes in the user's cookie. When it's doing this it outputs two log lines to the console output of the browser every 5 seconds or so. I.e.:
```
checkSession: posting some_name xxxxxxxxxxxxxxxxxxxxxxxxxxx to http://something:80
receiveMessage: unchanged from http://something:80
```

Now this isn't necessarily bad, but it gets cluttered very quickly and makes it quite difficult to debug javascript features where you have to log some stuff of your own. I think it would be a nice improvement if these logs line could be written under "debug" or "info" instead so it's easier to ignore all of the lines easily by filtering the console settings in your browser.

**Comment by zandbelt** [comment]
Can you suggest changes here:
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L2708
and here:
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L2719
Do you mean prefixing it with a "debug" string?

**Comment by kerrermanisNL** [comment]
Ah this was a lot easier than I thought (hadn't really looked around yet 🙈 ). I'll open up a PR in a bit.
