### ISSUE TITLE
Bypass SSP

### ISSUE THREAD

**Issue by finugeorgep** [zmartzone/mod_auth_openidc#324]
We wanted to by pass SSO for a url.
eg: 
https://example.com/wp-json/mobile/webapi 

So anything after webapi it should not prompt SSO.

Tried to implement this by adding below in openid.conf

<Location /wp-json/mobile/webapi/> 

AuthType None 
Allow from all 
</Location> 

Also many like this. Still no luck

Actually the physical path is not there in document root, seems this is causing the issue. But the app team wants to get it bypassed.

###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro (e.g. Ubuntu Xenial or Centos 7)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
That seems to be related to Apache specific behavior on virtual paths indeed:
https://stackoverflow.com/questions/31485400/apache-2-4-authtype-none-on-virtual-subdirectory

You can work around it by using:
```
<Location /wp-json/mobile/webapi/>

Satisfy Any
Allow from all
```
or you could use:
```
OIDCUnAuthAction pass
```
