### ISSUE TITLE
Issue OpenID Application Auto Creation

### ISSUE THREAD

**Issue by alexandrehoarau** [zmartzone/mod_auth_openidc#325]
###### Environment

- mod_auth_openidc version : 2.3.2
- Apache version : 2.4.23
- platform/distro (SLES)

###### Expected behaviour

In my application side (Request tracker), when a new user have been grant by my identity federation platform. The RT will autocreate the user in the database according the claims received and fill the backend database "Name, Email etc..."

###### Actual behaviour

Currently, RT System is filling only the Name field in the database and not email as expected which seems filled but empty.

So, How can I check the mail claims is well passed in the request tracker for the user creation ?

###### Configuration and Log files

apache config :

OIDCScope "profile openid email"
OIDCRemoteUserClaim "name"

Logs :

` Feb 01 12:58:53.137030 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137043 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137059 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(3320): [client MY_IP:59254] oidc_check_user_id: incoming request: "/images/bpslogo.png?(null)", ap_is_initial_req(r)=0, referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137067 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(3263): [client MY_IP:59254] oidc_check_userid_openidc: recycling user 'a a' from initial request for sub-request, referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137076 2018] [auth_openidc:debug] [pid 2308] src/util.c(2191): [client MY_IP:59254] oidc_util_hdr_in_get: Cookie=mod_auth_openidc_session=6885c216-2587-4ac5-aee3-2dffc84c650f; RT_SID_RT_SERVER.443=dea49a98a63a5da5f04a2879a45dd82c, referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137084 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of Require valid-user : granted, referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.137090 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of <RequireAny>: granted, referer: https://RT_SERVER/NoAuth/css/rudder/squished-3ec0208fe444cf42f75cf364b96b71ae.css
[Thu Feb 01 12:58:53.157714 2018] [ssl:debug] [pid 2308] ssl_engine_kernel.c(366): [client MY_IP:59254] AH02034: Subsequent (No.4) HTTPS request received for child 2 (server RT_SERVER:443)
[Thu Feb 01 12:58:53.157983 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Thu Feb 01 12:58:53.158010 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Thu Feb 01 12:58:53.158026 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(3320): [client MY_IP:59254] oidc_check_user_id: incoming request: "/static/images/favicon.png?(null)", ap_is_initial_req(r)=1
[Thu Feb 01 12:58:53.158043 2018] [auth_openidc:debug] [pid 2308] src/util.c(2191): [client MY_IP:59254] oidc_util_hdr_in_get: Cookie=mod_auth_openidc_session=6885c216-2587-4ac5-aee3-2dffc84c650f; RT_SID_RT_SERVER.443=dea49a98a63a5da5f04a2879a45dd82c
[Thu Feb 01 12:58:53.158129 2018] [auth_openidc:debug] [pid 2308] src/util.c(1001): [client MY_IP:59254] oidc_util_get_cookie: returning "mod_auth_openidc_session" = "6885c216-2587-4ac5-aee3-2dffc84c650f"
[Thu Feb 01 12:58:53.158155 2018] [auth_openidc:debug] [pid 2308] src/cache/common.c(567): [client MY_IP:59254] oidc_cache_get: enter: 6885c216-2587-4ac5-aee3-2dffc84c650f (section=s, decrypt=0, type=shm)
[Thu Feb 01 12:58:53.158175 2018] [auth_openidc:debug] [pid 2308] src/cache/common.c(601): [client MY_IP:59254] oidc_cache_get: cache hit: return 1332 bytes from shm cache backend for key 6885c216-2587-4ac5-aee3-2dffc84c650f
[Thu Feb 01 12:58:53.158415 2018] [auth_openidc:debug] [pid 2308] src/util.c(1153): [client MY_IP:59254] oidc_util_request_matches_url: comparing "/static/images/favicon.png"=="/openidc"
[Thu Feb 01 12:58:53.158448 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(1348): [client MY_IP:59254] oidc_handle_existing_session: enter
[Thu Feb 01 12:58:53.158458 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(1352): [client MY_IP:59254] oidc_handle_existing_session: set remote_user to "a a"
[Thu Feb 01 12:58:53.158467 2018] [auth_openidc:debug] [pid 2308] src/util.c(2191): [client MY_IP:59254] oidc_util_hdr_in_get: Host=RT_SERVER
[Thu Feb 01 12:58:53.158516 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(900): [client MY_IP:59254] oidc_log_session_expires: session max lifetime: Thu, 01 Feb 2018 19:58:51 GMT (in 28798 secs from now)
[Thu Feb 01 12:58:53.158624 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(1013): [client MY_IP:59254] oidc_get_provider_from_session: enter
[Thu Feb 01 12:58:53.158655 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(1218): [client MY_IP:59254] oidc_refresh_claims_from_userinfo_endpoint: userinfo_endpoint=https://domain/oauth2/userinfo, interval=0
[Thu Feb 01 12:58:53.158676 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(1258): [client MY_IP:59254] oidc_copy_tokens_to_request_state: id_token={"sub":"e7acb8e1-affb-4d78-9f2f-8b8d1b824cff","aud":"helpdesk-eudat","iss":"https://domain/oauth2","exp":1517489930,"iat":1517486330,"nonce":"LjQeVddG65Ab4uO1tYzIFlK7gVi5K-jJOf8my8wHKqU"} claims={"sub":"e7acb8e1-affb-4d78-9f2f-8b8d1b824cff","email_verified":"true","name":"a a","email":"a@yopmail.com"}
[Thu Feb 01 12:58:53.158708 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_sub: e7acb8e1-affb-4d78-9f2f-8b8d1b824cff
[Thu Feb 01 12:58:53.158797 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_sub: e7acb8e1-affb-4d78-9f2f-8b8d1b824cff"
[Thu Feb 01 12:58:53.158810 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_email_verified: true
[Thu Feb 01 12:58:53.158818 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_email_verified: true"
[Thu Feb 01 12:58:53.158827 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_name: a a
[Thu Feb 01 12:58:53.158834 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_name: a a"
[Thu Feb 01 12:58:53.158842 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_email: a@yopmail.com
[Thu Feb 01 12:58:53.158938 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_email: a@yopmail.com"
[Thu Feb 01 12:58:53.158987 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_sub: e7acb8e1-affb-4d78-9f2f-8b8d1b824cff
[Thu Feb 01 12:58:53.159000 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_sub: e7acb8e1-affb-4d78-9f2f-8b8d1b824cff"
[Thu Feb 01 12:58:53.159010 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_aud: helpdesk-eudat
[Thu Feb 01 12:58:53.159016 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_aud: helpdesk-eudat"
[Thu Feb 01 12:58:53.159025 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_iss: https://domain/oauth2
[Thu Feb 01 12:58:53.159032 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_iss: https://domain/oauth2"
[Thu Feb 01 12:58:53.159045 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_exp: 1517489930
[Thu Feb 01 12:58:53.159156 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_exp: 1517489930"
[Thu Feb 01 12:58:53.159193 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_iat: 1517486330
[Thu Feb 01 12:58:53.159203 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_iat: 1517486330"
[Thu Feb 01 12:58:53.159211 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_CLAIM_nonce: LjQeVddG65Ab4uO1tYzIFlK7gVi5K-jJOf8my8wHKqU
[Thu Feb 01 12:58:53.159219 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_CLAIM_nonce: LjQeVddG65Ab4uO1tYzIFlK7gVi5K-jJOf8my8wHKqU"
[Thu Feb 01 12:58:53.159248 2018] [auth_openidc:debug] [pid 2308] src/util.c(2223): [client MY_IP:59254] oidc_util_hdr_table_set: OIDC_access_token: _5_8rJCKIe0Czzj7460Lm8fIYZBAQ2lhC_s8HW0vcws
[Thu Feb 01 12:58:53.159259 2018] [auth_openidc:debug] [pid 2308] src/util.c(1680): [client MY_IP:59254] oidc_util_set_app_info: setting environment variable "OIDC_access_token: _5_8rJCKIe0Czzj7460Lm8fIYZBAQ2lhC_s8HW0vcws"
[Thu Feb 01 12:58:53.159372 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(900): [client MY_IP:59254] oidc_log_session_expires: session inactivity timeout: Thu, 01 Feb 2018 12:03:51 GMT (in 297 secs from now)
[Thu Feb 01 12:58:53.159405 2018] [auth_openidc:debug] [pid 2308] src/util.c(2191): [client MY_IP:59254] oidc_util_hdr_in_get: Cookie=mod_auth_openidc_session=6885c216-2587-4ac5-aee3-2dffc84c650f; RT_SID_RT_SERVER.443=dea49a98a63a5da5f04a2879a45dd82c
[Thu Feb 01 12:58:53.159418 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of Require valid-user : granted
[Thu Feb 01 12:58:53.159429 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of <RequireAny>: granted
[Thu Feb 01 12:58:53.159535 2018] [auth_openidc:debug] [pid 2308] src/config.c(2165): [client MY_IP:59254] oidc_auth_fixups: overlaying env with 10 elements
[Thu Feb 01 12:58:53.159801 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Thu Feb 01 12:58:53.159831 2018] [authz_core:debug] [pid 2308] mod_authz_core.c(809): [client MY_IP:59254] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Thu Feb 01 12:58:53.159844 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(3320): [client MY_IP:59254] oidc_check_user_id: incoming request: "/images/favicon.png?(null)", ap_is_initial_req(r)=0
[Thu Feb 01 12:58:53.159859 2018] [auth_openidc:debug] [pid 2308] src/mod_auth_openidc.c(3263): [client MY_IP:59254] oidc_check_userid_openidc: recycling user 'a a' from initial request for sub-request
[Thu Feb 01 12:58:53.159979 2018] [auth_openidc:debug] [pid 2308] src/util.c(2191): [client MY_IP:59254] oidc_util_hdr_in_get: Cookie=mod_auth_openidc_session=6885c216-2587-4ac5-aee3-2dffc84c650f; RT_SID_RT_SERVER.443=dea49a98a63a5da5f04a2879a45dd82c
`

**Comment by zandbelt** [comment]
your RT system will have to pickup the `OIDC_CLAIM_email` header which is being set as shown in the logs

**Comment by alexandrehoarau** [comment]
Thanks I will check my RT, because from the module the claims seem well passed.

Alex
