### ISSUE TITLE
bug verified

### ISSUE THREAD

**Issue by yihuiliu63** [zmartzone/mod_auth_openidc#326]
###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro (e.g. Ubuntu Xenial or Centos 7)

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
?
