### ISSUE TITLE
configuration of custom ca-bundle

### ISSUE THREAD

**Issue by lxcow** [zmartzone/mod_auth_openidc#329]
###### Environment

- mod_auth_openidc-2.3.3 (compiled from source)
- apache httpd-2.4.27 
- openssl-1.0.1f
- jansson-2.10
- cjose-0.5.1 
- curl-7.19.7 (distro)
- platform/distro RedHat-6

###### Expected behaviour
If the https-certificate of the IDP (e.g. keycloak) was signed by a local CA, it should be possible to configure a special ca-bundle that includes this CA. (like mod_proxy does: `SSLProxyCACertificateFile`)
This would be helpful for Test-Setups where you don't want to buy a certificate of one of the established CAs.
 

###### Actual behaviour
It is not possible to set an alternative ca-bundle. Also the Environment-Variable CURL_CA_BUNDLE used by curl doen't work cause it is only evaluated by curl itself not by libcurl.so 

###### Minimized example
**httpd_config:**
```
# Server config
# IDP e.g: a keycloak placed in my intranet;  SSL-certificate signed by MY-LOCAL-CA  
# client "TEST"
OIDCProviderMetadataURL https://mykeycloak-test.local:8443/auth/realms/TEST/.well-known/openid-configuration
```

###### Configuration and Log files

**httpd_error_log:**
```
oidc_util_http_call: curl_easy_perform() failed on: https://mykeycloak-test.local:8443/auth/realms/.well-known/openid-configuration (SSL certificate problem: unable to get local issuer certificate)
```

**Comment by meshjoerg** [comment]
As a workaround to the problem of getting custom CA bundles to work with libcurl within mod_auth_openidc, I imported the CA bundle into the operating system's CA store. 
The location depends on your distribution, e.g. for Ubuntu 14.04 it's `/usr/local/share/ca-certificates/` and for Ubuntu 16.04 it's `/usr/share/ca-certificates/` where you can place custom CA bundles and then run `update-ca-certificates` to include them. They will be picked up by libcurl https connections succeed.
For RedHat there will certainly be a similar mechanism.

**Comment by lxcow** [comment]
> As a workaround to the problem of getting custom CA bundles to work with libcurl within mod_auth_openidc, I imported the CA bundle into the operating system's CA store.

Yes, this is a valid workaround - but you need root privileges and have be allowed to add CAs to the server global CA-store. But in my organisation I am not allowed to do so :-(

**Comment by hpbieker** [comment]
We are running apache with mod_auth_openidc on docker and a change that allows us to specify a bundle with the required certificates (a .pem with three certificates in our case) would make the construction of the container easier. If we can use a bundle I would not have to run the update certificates command and it makes it possible to just mount the certificate into the container.

**Comment by mimendo** [comment]
Hello,
The workaround is not working for me in Windows 7.
Has anybody tried it in Windows?
Thank you!

**Comment by zandbelt** [comment]
on Windows the code finds the bundle in the path so you'll need to adapt the one it finds there:
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/util.c#L727-L738
