### ISSUE TITLE
JSON parsing returned an error "401: Access Denied"

### ISSUE THREAD

**Issue by tiwari3010** [zmartzone/mod_auth_openidc#330]
Hi, 

I am getting below errors:
I have verified Issuer and ClientID and ClientSecret and they are correct.

###### Environment

- mod_auth_openidc-2.3.2-apache-2.4.x-win64.zip

Server version: Apache/2.4.29 (Win64)
Apache Lounge VC15 Server built:   Nov  3 2017 11:12:00
Server's Module Magic Number: 20120211:68
Server loaded:  APR 1.6.3, APR-UTIL 1.6.1
Compiled using: APR 1.6.3, APR-UTIL 1.6.1
Architecture:   64-bit
- platform: Windows 2012 R2 Sp2

###### Configuration and Log files

OIDCSSLValidateServer Off
OIDCProviderIssuer https://www.example.com
OIDCClientID f7c1a70c-d17a-4ecb-933b-40c0e0ea5a6a
OIDCClientSecret vb2ydAmyut0CpH1kKEcDph7c0fAv8VsFmGHfj+pnVa4=
OIDCProviderAuthorizationEndpoint https://www.example.com/affwebservices/CASSO/oidc/authorize
OIDCProviderTokenEndpoint https://www.example.com/affwebservices/CASSO/oidc/token
OIDCRedirectURI http://www.demo.com/example/redirect
OIDCCryptoPassphrase testpassword
OIDCProviderTokenEndpointAuth client_secret_post
OIDCProviderJwksUri https://www.example.com/affwebservices/CASSO/oidc/jwks?AuthorizationProvider=openId-provider-example
OIDCScope "openid name"
OIDCProviderUserInfoEndpoint https://www.example.com/affwebservices/CASSO/oidc/userinfo

**please note I am getting ClientID and ClientSecret from OAuthProvider server which cannot be decrypted.

=====================================

[Thu Feb 15 17:50:36.134424 2018] [auth_openidc:error] [pid 3404:tid 952] [client 172.31.25.20:55299] **oidc_util_decode_json_object:** JSON parsing returned an error: '[' or '{' expected near '<' (<HTML>\r\n<HEAD><TITLE>**401: Access Denied**</TITLE></HEAD>\r\n<BODY>\r\n<H1>401: Access Denied</H1>\r\n<BR>\r\n</BODY></HTML>\r\n)
[Thu Feb 15 17:50:36.134424 2018] [auth_openidc:error] [pid 3404:tid 952] [client 172.31.25.20:55299] oidc_proto_resolve_code_and_validate_response: failed to resolve the code

==============Browser Error===============
Error:

OpenID Connect Provider error: Error in handling response type.

**Comment by zandbelt** [comment]
The provider returns an error instead of the authentication response. You'll have to look into the logs at the Provider side to see why it rejected your request, most probably a mismatch of client_id/client_secret indeed.
