### ISSUE TITLE
OIDCOAuthAcceptTokenAs cookie:access_token, cookie is not found

### ISSUE THREAD

**Issue by xrenou** [zmartzone/mod_auth_openidc#332]
Hi !

Here is my issue :)

###### Environment

- mod_auth_openidc version (2.3.3)
- Apache version (2.4)
- Azure AD OAUTH

###### Expected behaviour

First, I have to say that this configuration is working with Authorization: Bearer <token> in the request header. but this is not a good way to go.
So my goal is to make it work with OIDCOAuthAcceptTokenAs cookie:access_token

###### Actual behaviour

my Apache config have some debug to show that my cookies are existing 
```
SetEnvIf Cookie "(^|;\ *)access_token=(.*)" MyTokenFromCookie=$2
CustomLog /var/log/apache2/custom.log cust
#shows my access_token cookie
LogFormat "%{MyTokenFromCookie}e" cust
#shows all the cookies
LogFormat "%{Cookie}i" cust
```
this log shows that I have plenty of cookies and that my access_token cookie is here

but with my following OAuth instructions
```
OIDCSSLValidateServer Off
OIDCOutgoingProxy <IP_PROXY>
OIDCOAuthVerifyJwksUri https://login.microsoftonline.com/<tenantid>/discovery/keys
OIDCUnAuthAction 401
OIDCIDTokenIatSlack 3600
OIDCOAuthAcceptTokenAs cookie:access_token

<Location /site>
                AuthType oauth20
                Require valid-user
                LogLevel debug
</Location>

ProxyPreserveHost On
ProxyVia Block
```
I've pretty tried everything and I always have this logtrace
```
[Thu Feb 22 18:31:48.857212 2018] [auth_openidc:debug] [pid 17666:tid 140247175919360] src/oauth.c(117): [client ] oidc_oauth_get_bearer_token: accept_token_in=8
[Thu Feb 22 18:31:48.857232 2018] [auth_openidc:debug] [pid 17666:tid 140247175919360] src/util.c(1002): [client ] oidc_util_get_cookie: returning "session" = <null>
[Thu Feb 22 18:31:48.857239 2018] [auth_openidc:warn] [pid 17666:tid 140247175919360] [client ] oidc_oauth_get_bearer_token: no cookie found with name: access_token
[Thu Feb 22 18:31:48.857250 2018] [auth_openidc:debug] [pid 17666:tid 140247175919360] src/oauth.c(180): [client ] oidc_oauth_get_bearer_token: no bearer token found in the allowed methods: ['cookie']
[Thu Feb 22 18:31:48.857260 2018] [auth_openidc:debug] [pid 17666:tid 140247175919360] src/util.c(2246): [client ] oidc_util_hdr_err_out_add: WWW-Authenticate: Bearer error="invalid_request", error_description="No bearer token found in the request"
```
What is happening ? why all my cookie names are not found ?
Am I getting wrong with the oauth overall functionment ?

Thanks a lot for your help

regards

Xavier

**Comment by zandbelt** [comment]
I am not able to reproduce this: `OIDCOAuthAcceptTokenAs cookie:access_token` looks for and finds a cookie named `access_token` if it exists; I suspect your browser does not actually send one, or maybe not to this specific path
