### ISSUE TITLE
Support array-type claims in colon notation

### ISSUE THREAD

**Issue by letmaik** [zmartzone/mod_auth_openidc#333]
###### Environment

- mod_auth_openidc version: 2.3.4rc3
- Apache version: 2.4.6
- platform/distro: CentOS 7

###### Expected behaviour

```
Require claim groups:ad603398067b43bf8f6049a9ad9c0c1c
```

I expected that this would succeed if the given value appears in the `groups` claim array which is an array of strings.

###### Actual behaviour

The condition using the colon doesn't seem to work with array based claims.

###### Work-around
```
Require claim "groups~ad603398067b43bf8f6049a9ad9c0c1c"
```
It appears as if the array is interpreted as a string. This work-around using a regex is fine for this specific use case but doesn't seem like a clean solution and would be harder if the values to compare against are not GUIDs where one array item may be partly contained in another etc.

**Comment by zandbelt** [comment]
I cannot reproduce this, my experiments work:
```
[Wed Mar 21 18:59:52.645735 2018] [auth_openidc:debug] [pid 37037:tid 123145389117440] src/authz.c(204): [client 127.0.0.1:58051] oidc_authz_match_claim: evaluating key "memberOf", referer: https://localhost:9031/
[Wed Mar 21 18:59:52.645746 2018] [auth_openidc:debug] [pid 37037:tid 123145389117440] src/authz.c(435): [client 127.0.0.1:58051] oidc_authz_worker24: require claim/expr 'memberOf:ad603398067b43bf8f6049a9ad9c0c1c' matched, referer: https://localhost:9031/
```
same value, different multi-value claim:
```
"memberOf":["ad603398067b43bf8f6049a9ad9c0c1c","1111"],
```
so the error must be in the input

**Comment by wasson5e** [comment]
Im having this same issue.  When I try and filter the groups that are being returned and use:
`"memberof":["CN=<group>,OU=Distribution Lists,OU=Exchange55,DC=CORP,DC=<domain>,DC=com"]` the filter doesn't work.  But when I use:
`"memberof~CN=<group>,OU=Distribution Lists,OU=Exchange55,DC=CORP,DC=<domain>,DC=com` the filter works fine.  Im okay with doing that on a single group, but now I need to filter out an array of around 40 groups.

**Comment by zandbelt** [comment]
can you provide the version of the module you're using, the config file snippet and the server debug logs?

**Comment by wasson5e** [comment]
> can you provide the version of the module you're using, the config file snippet and the server debug logs?

Module Version - (its a little behind) last notes date is 08/18/2021 - release 2.4.9.1

Config:
`OIDCProviderMetadataURL https://<url>:8443/nidp/oauth/nam/.well-known/openid-configuration
OIDCClientID <clientid>
OIDCClientSecret <clientsecrect>
OIDCRedirectURI https://localhost:7777/auth
OIDCCryptoPassphrase <passphrase>
OIDCScope "openid <customscope>"
OIDCResponseType "code id_token token"
urlOIDCProviderUserInfoEndpoint https://<url>:8443/nidp/oauth/nam/userinfo
OIDCProviderTokenEndpoint https://<url>:8443/nidp/oauth/nam/token
OIDCCacheShmEntrySizeMax 500000
#LogLevel debug

<Location "/">
Order deny,allow
AuthType openid-connect
Require claim "memberof~CN=<group>,OU=Distribution Lists,OU=Exchange55,DC=CORP,DC=CHARTERCOM,DC=com"
LogLevel debug
</Location>`

Ill try and send you the log instead of posting it.

**Comment by wasson5e** [comment]
Update:

Looks like I'll have to use multiple "Require claim "memberof~<>" to bypass the array issue. 

Tested this in docker and it worked, regardless of where the groups were arranged. IE: if a group was at the top, and I'm not in it, I'm not blocked out.

**Comment by zandbelt** [comment]
The second form:
```apache
Require claim "memberOf:CN=<group>,OU=Distribution Lists,OU=Exchange55,DC=CORP,DC=<domain>,DC=com"
```
should work; can you try with lowercase "memberof", as you seem to be using in the regexp but not in the literal match?

**Comment by wasson5e** [comment]
> The second form:
> 
> ```apache
> 
> Require claim "memberOf:CN=<group>,OU=Distribution Lists,OU=Exchange55,DC=CORP,DC=<domain>,DC=com"
> 
> ```
> 
> should work; can you try with lowercase "memberof", as you seem to be using in the regexp but not in the literal match?


That did work. Any thoughts on the array?  I have the other way working for now.

**Comment by zandbelt** [comment]
> That did work. Any thoughts on the array? I have the other way working for now.

I was assuming this fixed your issue. If not, what is "that did work" referring to and what is your other question?

**Comment by wasson5e** [comment]
> > That did work. Any thoughts on the array? I have the other way working for now.
> 
> I was assuming this fixed your issue. If not, what is "that did work" referring to and what is your other question?

It worked for a single group, but when I try and apply that toward the array, its not working.  Ive tried around 10~15 different iterations that I could come up with and they didnt seem to work.  Ill have to just stick with a single group per require claim.

**Comment by zandbelt** [comment]
Can you provide server debug logs for both cases that show the full contents of the id_token, the userinfo response and the claim matching process?
