### ISSUE TITLE
Exclude path from auth

### ISSUE THREAD

**Issue by rothgar** [zmartzone/mod_auth_openidc#334]
###### Environment

- mod_auth_openidc version 2.3.3
- Apache version 2.4.6
- platform/distro Centos 7

Sorry for the general question in an issue but I haven't found an example for what I'm looking for after searching the readme and wiki.

Is there a way to exclude a path from authentication if I have the root (/) protected?

I have something like this in my config
```
<Location />
   AuthType oauth20
   Require claim sub:<resource_owner_identifier>
</Location>
```

But I'd also like to add
```
<Location /api>
   AuthType none
</Location>
```

to ignore authentication on a specific path. Is that possible? If so can we please add an example to the wiki?

Thank you

**Comment by lalmeras** [comment]
(not an openidc developer, just a user)

This is more a apache-related question.

Try this (Location is replaced with a LocationMatch, with a regex matching all except /api):

```
<LocationMatch "^/(?!api)">
   AuthType oauth20
   Require claim sub:<resource_owner_identifier>
</LocationMatch>
```

**Comment by rothgar** [comment]
You're right. I found that solution earlier this week. Thanks.
