### ISSUE TITLE
Compatibility with multi-tenant Azure AD

### ISSUE THREAD

**Issue by matteustace** [zmartzone/mod_auth_openidc#336]
Feature request:

I note that this does not work with Azure AD when using https://login.microsoftonline.com/common as the way microsoft have implemented it means the response you get is from a tenant-specific issuer.

This is therefore not a bug, it fails issuer validation and thus correctly fails the login. 

What would be nice would be a means in the config to disable issue validation in order to make this work for the one particular use-case of multi-tenant Azure AD.

If anybody has any tips on how they've made this work, I'd be grateful!

**Comment by zandbelt** [comment]
you need to configure the tenant-specific urls

**Comment by matteustace** [comment]
This does not solve the issue. What I would like is authentication for any tenant, as works with Google, without needing a list of every possible tenant URL.

**Comment by zandbelt** [comment]
that's not possible with MS as unlike Google, they have different `iss` values
