### ISSUE TITLE
Wiki page with tutorials

### ISSUE THREAD

**Issue by cremfert** [zmartzone/mod_auth_openidc#337]
Dear all,

first of all, thanks for this really cool piece of software!
After a few hours of investigation, I finally managed to get mod_auth_openidc, nextcloud and KeyCloak integrated. As I haven't found any tutorial for this combination, I would like to provide one, maybe in mod_auth_openidc's wiki. Hence I would set up a new page "Tutorials" and put it on there, is this ok for you?

Best regards,
Chris

**Comment by zandbelt** [comment]
sure, go ahead

**Comment by coredump4** [comment]
Hi @cremfert, did you ever write up a tutorial?  I am tackling the same situation and am interested in your solution.  Thanks!

**Comment by cremfert** [comment]
Not yet, but I can help you, if needed. I ended up with using another plugin for NC to simplify the interaction between KeyCloak and Nextcloud.

**Comment by coredump4** [comment]
> Not yet, but I can help you, if needed. I ended up with using another plugin for NC to simplify the interaction between KeyCloak and Nextcloud.

Thanks, maybe you can give me a pointer.  I have mod_auth_openidc working partly with NC; when I first hit NC, I am redirected to Keycloak and can authenticate.  However, when redirected back to NC, I am always left at the NC login screen.  Clearly I'm missing the way to pass a user claim to NC and have it start a session.
