### ISSUE TITLE
"Uncaught URIError: URI malformed" when Restoring POST data

### ISSUE THREAD

**Issue by timpuri** [zmartzone/mod_auth_openidc#338]
When I wait more than OIDCSessionInactivityTimeout and send POST form that includes scandinavic characters like "ä", PreservePost Restoring page crashes to JavaScript error:

```
redirect_uri:13 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at postOnLoad (redirect_uri:13)
    at onload (redirect_uri:23)
```

###### Environment

- mod_auth_openidc version 2.3.3
- Apache version 2.2.15
- platform/distro Centos 7
- browser Google Chrome 64.0.3282.186 (Mac OS X 10.12.6)

**Comment by zandbelt** [comment]
Can you try and serve UTF-8 characters? See: https://stackoverflow.com/questions/15326777/uncaught-urierror-uri-malformed-jquery-ui-tabs-on-windows

**Comment by zandbelt** [comment]
@timpuri does the previous suggestion help?

**Comment by timpuri** [comment]
Not tested with UTF-8, but tested this and it works with ISO-8859-1:

`@@ -488,13 +488,21 @@ static int oidc_request_post_preserved_restore(request_rec *r,
        const char *script =
                        apr_psprintf(r->pool,
                                        "    <script type=\"text/javascript\">\n"
+                                       "      function str_decode(string) {\n"
+                                       "        try {\n"
+                                       "          result = decodeURIComponent(string);\n"
+                                       "        } catch (e) {\n"
+                                       "          result =  unescape(string);\n"
+                                       "        }\n"
+                                       "        return result;\n"
+                                       "      }\n"
                                        "      function %s() {\n"
                                        "        var mod_auth_openidc_preserve_post_params = JSON.parse(localStorage.getItem('mod_auth_openidc_preserve_post_params'));\n"
                                        "                localStorage.removeItem('mod_auth_openidc_preserve_post_params');\n"
                                        "        for (var key in mod_auth_openidc_preserve_post_params) {\n"
                                        "          var input = document.createElement(\"input\");\n"
-                                       "          input.name = decodeURIComponent(key);\n"
-                                       "          input.value = decodeURIComponent(mod_auth_openidc_preserve_post_params[key]);\n"
+                                       "          input.name = str_decode(key);\n"
+                                       "          input.value = str_decode(mod_auth_openidc_preserve_post_params[key]);\n"
                                        "          input.type = \"hidden\";\n"
                                        "          document.forms[0].appendChild(input);\n"
                                        "        }\n"
`
There is still problem, that spaces in form data converts to + character because curl_easy_unescape() -function does not convert these..

**Comment by timpuri** [comment]
And here is patch for + character bug:

```
diff --git a/src/util.c b/src/util.c
index 387bcbc..3a7b20b 100644
--- a/src/util.c
+++ b/src/util.c
@@ -318,7 +318,15 @@ char *oidc_util_unescape_string(const request_rec *r, const char *str) {
                oidc_error(r, "curl_easy_init() error");
                return NULL;
        }
-       char *result = curl_easy_unescape(curl, str, 0, 0);
+       int counter = 0;
+       char *replaced = (char *)str;
+       while(str[counter] != '\0') {
+               if(str[counter] == '+') {
+                       replaced[counter] = ' ';
+               }
+               counter++;
+       }
+       char *result = curl_easy_unescape(curl, replaced, 0, 0);
        if (result == NULL) {
                oidc_error(r, "curl_easy_unescape() error");
                return NULL;

```

**Comment by zandbelt** [comment]
thanks! part of 2.3.5
