### ISSUE TITLE
Chained logout is not working after Keycloak SSO idle time is reached

### ISSUE THREAD

**Issue by abhishekraghav** [zmartzone/mod_auth_openidc#339]
Hi

First of all thanks for this wonderful mod.

I ran into a issue with session management for my specific kind of architecture.
I am using mod-auth version 2.3 (latest) and I have two RP protected with that, one uses open id connect and other one is on SAML based authentication.

I am using keycloak as my OP.

Now when i access app1 (openidc type ) , i get a login page to auth and then from app1, i am calling some APIs of app2 which are protected by SAML based auth. Now since I am already logged in and both apps are registered in the same realm, SSO will happen ,no login page is presented and SAML flow is triggered and a SAML token is granted by keycloak for that particular authn request by the app.

So now my browser has two cookies created, one for mod_auth_openidc session and other for my app2 (SAML type client).

Now comes the part where i am facing issue:

Normally when i call a logout URL by calling the standard logout URL of mod_auth_openidc e..g. https://www.example.com/protected/redirect_uri?logout=https%3A%2F%2Fwww.example.com%2Floggedout.html it works fine and it clears the other apps cookie as well because of the fact the keycloak triggers a chain logout here.

But the issue occurs, if the logout URL is triggered after the Keycloak's SSO idle time is reached after the user is successfully logged in. e.g if my keycloak's SSO idle time is set as 30 min and if i call the logout URL at 31st minute, it simply clears the mod_auth cookie and not the SAML one which  keeps it lying on the browser which is why i have seen some inconsistencies in the session management.

So my only doubt here is, how can we keep the Keycloak idle time out or Keycloak_session bumped up, if a user is actively working on the app. Right now if a user is working for more than keycloak SSO idle time out and if a user triggers a logout after that , the chain logout fails. 

Also the refresh token being stored at mod_Auth also getting expired since Keycloak SSO idle timeout says that **tokens and browser sessions are invalidated when a session is expired.**

As per my limited understanding, this might be happening as below:
When a logout is triggered, the id token thats get sent in the request to keycloak might have already been revoked and thus the association of the user to other app session were also lost where this user might be still logged in.

I am not understanding the fact, why mod_auth is not bumping the Keycloak SSO idle time if a user is working actively on the app. Am i missing anything from the configuration perspecitve on mod_auth.

Does it have anything to confgure the with iframe based session management, should i configure that as the of the configuration in auth_openidc.conf says :

[https://github.com/zmartzone/mod_auth_openidc/blob/800160ff1a0ffbea1b0536b6350259bb0c2e7b8e/auth_openidc.conf#L85](url)
 OpenID OP Check Session iFrame URL, for Session Management purposes.
# When not defined, no Session Management will be applied.
# Used when OIDCProviderMetadataURL is not defined or the metadata obtained from that URL does not set it.
#OIDCProviderCheckSessionIFrame <url>

###### Environment

- mod_auth_openidc version : 2.3
- Apache version e.g. 2.4.8
- ubuntu

###### Expected behaviour
Keycloak SSO idle should keep on bumping up if a user is actively working and requests are being intercepted by mod_auth.

###### Actual behaviour
Keycloak SSO idle timeout is not bumping up.

Thanks and Regards
Abhishek

**Comment by zandbelt** [comment]
there's no spec/standard that caters for that behavior

**Comment by abhishekraghav** [comment]
Thanks for your response.

What i observed is that even if i remove the SAML RP from the login flow, the behavior is same. I was wondering, can i configure OIDCUserInfoRefreshInterval on mod_auth_openidc, which can work as a heartbeat call to keycloak as long as the mod_auth session is there for that user. So Keycloak session will not timeout as long as mod_auth session is active.


Hope I am making sense here.

Thanks.

**Comment by zandbelt** [comment]
that would be up to keycloak but I'd argue that this behavior would be wrong: calls to the userinfo endpoint don't need to be related to a user's OP session

**Comment by abhishekraghav** [comment]
what i observed here is that if i add OIDCUserInfoRefreshInterval as say 1 hour and keycloak SSO timeout as 2 hours and access token time as 30min , i found that in every 1 hour their is a call to userinfo endpoint which bump up the KEYCLOAK session (as i could see on keycloak admin console UI by going into that user's session tab).

As per my opinion, that everytime when mod_auth makes a call to userinfoendpoint, mod_auth finds the access token as expired and the refresh token flow comes into the picture which also refreshes the user's OP session.

I could be wrong. 

Thanks.
