### ISSUE TITLE
namespaced claim names get mangled

### ISSUE THREAD

**Issue by pushpabrol** [zmartzone/mod_auth_openidc#344]
###### Environment
- mod_auth_openidc-2.3.4rc4
- Server version: Apache/2.4.18 (Ubuntu)
- platform/distro (e.g. Ubuntu Xenial)

###### Expected behaviour
Expected claim in id_token to be returned in the headers as 

**"http://example.com.role": "group_admin"**

###### Actual behaviour

**"http---example.com-role": "group_admin"**

###### Configuration and Log files

<VirtualHost *:443>
    ServerName app
    DocumentRoot /var/www/app1

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyVia Full
    <Proxy *>
      Require all granted
    </Proxy>

    OIDCProviderMetadataURL https://op/.well-known/openid-configuration
    OIDCSSLValidateServer Off
    OIDCCryptoPassphrase xxxxxxx
    OIDCProviderEndSessionEndpoint https://op/v2/logout
    OIDCClientID xxx
    OIDCClientSecret xxxxx
    OIDCScope "openid profile"
    OIDCClaimPrefix ""
    OIDCRedirectURI https://app/callback
    #OIDCResponseType "id_token"
    OIDCOAuthRemoteUserClaim sub
    OIDCTokenBindingPolicy disabled
    OIDCAuthNHeader SMUSER
    OIDCCookieDomain domain
    OIDCAuthRequestParams connection=Username-Password-Authentication
    OIDCProviderUserInfoEndpoint https://op/userinfo
    OIDCPassIDTokenAs "claims"
    OIDCPassUserInfoAs "claims"
    OIDCPassClaimsAs "both"
    OIDCInfoHook "id_token"
    OIDCResponseType "code id_token"
    <Location /headers.php>
        AuthType openid-connect
        #Require valid-user
        #Require claim Nickname:johnfoo
        #Require claim nickname:johnfoo
        Require claims_expr '.aud == "xxx" and ( ."http://example.com/role" == "admin" or ."http://example.com/role" == "group_admin")'

    </Location>

        <Location /callback>
        AuthType openid-connect
        Require valid-user                                                                                                                                                                   
        AuthType openid-connect
        Require valid-user
    </Location>

     <Location /headers-node>
      ProxyPass http://127.0.0.1:8080
      ProxyPassReverse http://127.0.0.1:8080
      AuthType openid-connect
        Require claims_expr '.aud == "xxx" and ( ."http://example.com/role" == "admin" or ."http://example.com/role" == "group_admin")'
   </Location>

SSLCertificateFile /etc/letsencrypt/live/app/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/app/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

**Comment by zandbelt** [comment]
That is done with a reason: to make names compliant and safe according to rfc 2626.
