### ISSUE TITLE
cjose / jansson dependency issue

### ISSUE THREAD

**Issue by MukundKMallar** [zmartzone/mod_auth_openidc#346]
Trying to work through issue reported in #182 - having trouble installing the package.

Red Hat Enterprise Linux Server release 7.4 (Maipo)

Installers - 
mod_auth_openidc-2.3.3-1.el7.centos.x86_64.rpm
cjose-0.5.1-1.el7.centos.x86_64.rpm

rpm -qa | grep -i jans
jansson-2.10-1.el7.x86_64

Trying to install the available EL7 package (marked as centOS)
**rpm -ivh cjose-0.5.1-1.el7.centos.x86_64.rpm**
error: Failed dependencies:
        pkgconfig(jansson) >= 2.3 is needed by cjose-0.5.1-1.el7.centos.x86_64

OR 
**yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm**
Error: Package: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requires: pkgconfig(jansson) >= 2.3

**Comment by MukundKMallar** [comment]
Tried cjose package install on **CentOS Linux release 7.4.1708** (Core) as well.

**yum localinstall -y cjose-0.5.1-1.el7.centos.x86_64.rpm**
Loaded plugins: fastestmirror, langpacks
Examining cjose-0.5.1-1.el7.centos.x86_64.rpm: cjose-0.5.1-1.el7.centos.x86_64
Marking cjose-0.5.1-1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
RHEL7_u4_base                                                                                                                                         | 1.3 kB  00:00:00
RHEL7_u4_update                                                                                                                                       | 1.3 kB  00:00:00
dockerrepo                                                                                                                                            | 2.9 kB  00:00:00
Determining fastest mirrors
--> Processing Dependency: pkgconfig(libcrypto) >= 1.0.1 for package: cjose-0.5.1-1.el7.centos.x86_64
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
---> Package openssl-devel.x86_64 1:1.0.2k-8.el7 will be installed
--> Processing Dependency: zlib-devel(x86-64) for package: 1:openssl-devel-1.0.2k-8.el7.x86_64
--> Processing Dependency: krb5-devel(x86-64) for package: 1:openssl-devel-1.0.2k-8.el7.x86_64
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
---> Package krb5-devel.x86_64 0:1.15.1-8.el7 will be installed
--> Processing Dependency: libkadm5(x86-64) = 1.15.1-8.el7 for package: krb5-devel-1.15.1-8.el7.x86_64
--> Processing Dependency: libverto-devel for package: krb5-devel-1.15.1-8.el7.x86_64
--> Processing Dependency: libselinux-devel for package: krb5-devel-1.15.1-8.el7.x86_64
--> Processing Dependency: libcom_err-devel for package: krb5-devel-1.15.1-8.el7.x86_64
--> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.15.1-8.el7.x86_64
---> Package zlib-devel.x86_64 0:1.2.7-17.el7 will be installed
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
---> Package keyutils-libs-devel.x86_64 0:1.5.8-3.el7 will be installed
---> Package libcom_err-devel.x86_64 0:1.42.9-10.el7 will be installed
---> Package libkadm5.x86_64 0:1.15.1-8.el7 will be installed
---> Package libselinux-devel.x86_64 0:2.5-11.el7 will be installed
--> Processing Dependency: libsepol-devel(x86-64) >= 2.5-6 for package: libselinux-devel-2.5-11.el7.x86_64
--> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.5-11.el7.x86_64
--> Processing Dependency: pkgconfig(libpcre) for package: libselinux-devel-2.5-11.el7.x86_64
---> Package libverto-devel.x86_64 0:0.2.5-4.el7 will be installed
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
---> Package libsepol-devel.x86_64 0:2.5-6.el7 will be installed
---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed
--> Finished Dependency Resolution
Error: Package: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requires: pkgconfig(jansson) >= 2.3
 You could try using --skip-broken to work around the problem

rpm -qa | grep -i janss
jansson-2.10-1.el7.x86_64

**Comment by MukundKMallar** [comment]
Please advise on how to proceed.

Tried few combinations to understand the impact - 
RHEL7.4 - Cjose0.5.1 or 0.4.1 yum localinstall does not work.
CentOS7.4.1708 (core) - Cjose0.5.1 or 0.4.1 yum localinstall does not work

What works is - 
cjose0.5.1 or 0.4.1 on CentOS7.2.1511 (or 7.3.1611 or latest) on Docker

**Comment by zandbelt** [comment]
using "yum localinstall" consistently for both cjose and mod_auth_openidc works on CentOS 7.4.1708 which automatically installs libjansson as a dependency

**Comment by MukundKMallar** [comment]
Hello Hans - This EL7 just works on centOS and not on RHEL. Would you be adding EL7 for RHEL?
