### ISSUE TITLE
Error Proxying Empty URLs

### ISSUE THREAD

**Issue by skorski** [zmartzone/mod_auth_openidc#348]
###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro  Debian Jessie
- Azure AD is providing the authentication.

I'm using a docker container for httpd2.4 with minimal modifications to contain this plugin.

###### Expected behaviour

Navigating to https://elastic.mydomain.org would return the standard elastic response.

When I remove the authentication requirements I can get the expected response.  I've tried doing a redirect for certain applications but cannot do that for elastic.  Even with a redirect, I cannot seem to do a it before the authentication (probably by design) and therefore am stuck in a loop where I can't get to the server root if authentication is turned on.

If I add anything to the end of the URL ie `https://elastic.mydomain.org/_cat` it works exactly as expected.

###### Actual behaviour

```
Error:

Invalid Request
Description:

You've hit an OpenID Connect Redirect URI with no parameters, this is an invalid request; you should not open this URL in your browser directly, or have the server administrator use a different OIDCRedirectURI setting.
```

###### Minimized example
conf file for a site
```
OIDCProviderMetadataURL https://login.microsoftonline.com/{redacted}.onmicrosoft.com/v2.0/.well-known/openid-configuration
OIDCClientID {redacted}
OIDCClientSecret {redacted}

OIDCCryptoPassphrase {redacted}
OIDCScope "openid"
OIDCResponseType id_token
OIDCCookieDomain {redacted}.org
OIDCRedirectURI https://elastic.{redacted}.org/

<Proxy "*">
   AuthType openid-connect
   Require valid-user
   OIDCPassRefreshToken On
</Proxy>

ProxyPass "/" "http://{redacted}:80/"
ProxyPassReverse "/" "http://{redacted}:80/"
```

Note: the proxy pass is actually sending the request to a traefik backend.  The url, ports, etc are correct and they work.

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
Use a vanity URL for the redirect URI e.g.: OIDCRedirectURI https://elastic.{redacted}.org/redirect_uri/
so that it does not collide with URL content handlers.

**Comment by skorski** [comment]
I think I'm still missing something here.  I tried changing that setting and got the same response.

**Comment by skorski** [comment]
That's black magic.  Do you have a link to some documentation that can help me understand what is going on there a bit better?

Thanks for such a prompt and awesome response!

**Comment by zandbelt** [comment]
See the documentation for the OIDCRedirectURI configuration primitive in the auth_openid.conf file.

**Comment by skorski** [comment]
Thank you.  I didn't see that file before.  It's extremely helpful.

**Comment by acdha** [comment]
Thanks for having an easily-found issue for this. It might be handy if the main page had a message which was visible in the default view — “vanity URL” isn't commonly used to mean a URL which doesn't exist and it's fairly easy not to notice that the key detail requires scrolling to the right to see. Fortunately the text in `auth_openid.conf` is quite explanatory as soon as you see it.

**Comment by AlexyFr** [comment]
You mean that we must copy/paste the exact link or create our own ? Like, we just have to make a fictive one ?
