### ISSUE TITLE
mod_auth_openidc on apache/alpine linux (.apk)

### ISSUE THREAD

**Issue by MukundKMallar** [zmartzone/mod_auth_openidc#350]
Hello Ms. Zandbelt

We are trying to setup openidc module on apache /alpine linux combination. Build of cjose and module itself looks little challenging and we have had no luck so far. Would you be including or providing us with a .apk installer just like .deb ,  .rpm for other combinations?

**Comment by zandbelt** [comment]
this can be provided under a commercial agreement
