### ISSUE TITLE
Azure Redis with SSL

### ISSUE THREAD

**Issue by akrepon** [zmartzone/mod_auth_openidc#351]
Hi,

I configured apache to use a Azure Redis service. Azure Redis is using SSL by default. When apache starts up it's tryin to make a connection with Azure Redis but the connection is reset by peer. Here is the log I have:

[Fri Apr 20 08:42:59.585881 2018] [auth_openidc:error] [pid 9:tid 139644636866304] [client 10.199.208.148:55866] oidc_cache_redis_command: authentication to the Redis server (redis-msw-int-we-01.redis.cache.windows.net:6380) failed, reply == NULL
[Fri Apr 20 08:42:59.585930 2018] [auth_openidc:error] [pid 9:tid 139644636866304] [client 10.199.208.148:55866] oidc_cache_redis_command: redisvAppendCommand/redisGetReply (0) failed, disconnecting: 'Connection reset by peer'

Is it because Azure Redis is using SSL?

Thanks.

**Comment by zandbelt** [comment]
mod_auth_openidc depends on libhiredis which doesn't natively support SSL; you can get around this by using stunnel
