### ISSUE TITLE
Client side cookie & Load balancing

### ISSUE THREAD

**Issue by akrepon** [zmartzone/mod_auth_openidc#352]
Hi,

I've created a setup of 2 apache instances running behind a loadbalancer. These instances use client side cookie as session type and share both the same CryptoPass for encrypting the cookie.

Now, when the user goes to the website without any cookie he will be redirected to the OP. After successful login, the client side cookie is created in the browser. Since the website is load balanced, sometimes user is served by the other apache instance which didn't create this cookie during the authentication. At that moment this instance verifies the cookie with the CyptoPass and creates a new one sets it in the browser.

This causes some perfomance problems dues this verification & validation. 
I always thought that the instances wouldn't recreate the cookie since they can decode it with the shared CryptoPass.

My question is, how can I avoid this problem of different instances creating fresh client side cookies?

I am planning to use Redis caching currently if that helps our problem of load balancing. But due to the SSL problems I was not yet able to test it. As suggested in another issue post, I'll be using stunnel to overcome this problem.

Can you give me some advise on this please?

Thanks.

**Comment by zandbelt** [comment]
questions like this should go to the mailinglist; otherwise you should follow the guidelines in the issue template and provide details and logs

for the record: the cookie value may need to be updated from time to time, it doesn't mean that new cookie is created, just that its value is updated
