### ISSUE TITLE
cjose / jansson dependency issue - Enterprise Linux 7 (EL7)

### ISSUE THREAD

**Issue by MukundKMallar** [zmartzone/mod_auth_openidc#354]
We want to install module on EL7 and not CentOS. Package available doesnt work on EL7. Could you please provide packages for EL7 or advise how we move forward on installing module on enterprise linux 7?

Issues #346 & #182 have been in place and the responses are only for CentOS and not for EL7. Installer complains about the version of libjansson when trying on EL7.

Red Hat Enterprise Linux Server release 7.4 (Maipo)

Installers -
mod_auth_openidc-2.3.3-1.el7.centos.x86_64.rpm
cjose-0.5.1-1.el7.centos.x86_64.rpm

rpm -qa | grep -i jans
jansson-2.10-1.el7.x86_64

Trying to install the available EL7 package (marked as centOS)
rpm -ivh cjose-0.5.1-1.el7.centos.x86_64.rpm
error: Failed dependencies:
pkgconfig(jansson) >= 2.3 is needed by cjose-0.5.1-1.el7.centos.x86_64

OR
yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm
Error: Package: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
Requires: pkgconfig(jansson) >= 2.3

**Comment by zandbelt** [comment]
remove the jansson package first and have it installed as a dependency automatically

**Comment by devantoine** [comment]
@zandbelt It does not work.

**Comment by draeath** [comment]
Installing centos packages on RHEL is not really a good solution...

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/issues/407#issuecomment-440995404

**Comment by mmoossen** [comment]
The problem is that the error message is misleading.
It reads:
Requires: pkgconfig(jansson) >= 2.3
but what is actually meant is that jansson-devel is missing...

**Comment by jrpatterson** [comment]
I just ran into the same issue.   The dependency is for jansson-devel and some hosts do not have the rhel-7-server-optional-rpms/x86_64 repo enabled by default to grab the package.  

--> Running transaction check
---> Package mod_auth_openidc.x86_64 0:2.4.5-1.el7 will be installed
--> Processing Dependency: hiredis for package: mod_auth_openidc-2.4.5-1.el7.x86_64
--> Processing Dependency: cjose for package: mod_auth_openidc-2.4.5-1.el7.x86_64
--> Processing Dependency: libhiredis.so.0.12()(64bit) for package: mod_auth_openidc-2.4.5-1.el7.x86_64
--> Processing Dependency: libcjose.so.0()(64bit) for package: mod_auth_openidc-2.4.5-1.el7.x86_64
--> Running transaction check
---> Package cjose.x86_64 0:0.6.1.5-1.el7 will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.6.1.5-1.el7.x86_64
---> Package hiredis.x86_64 0:0.12.1-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: cjose-0.6.1.5-1.el7.x86_64 (LocalRepo)
           Requires: pkgconfig(jansson) >= 2.3

**Comment by zandbelt** [comment]
this was a longstanding RPM packaging problem in the cjose libraries provided as part of the Releases of this project; that is fixed now
