### ISSUE TITLE
cjose / jansson dependency issue - Enterprise Linux 7 (EL7)

### ISSUE THREAD

**Issue by MukundKMallar** [zmartzone/mod_auth_openidc#355]
Request you to verify this before closing the case. Removing the jansson package and trying to install it as a dependency with cjose EL7_Centos rpm doesnt work.

Please see this - 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

 binaries]# rpm -qa | grep -i jansson
jansson-2.10-1.el7.x86_64

binaries]# yum remove jansson
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Resolving Dependencies
--> Running transaction check
---> Package jansson.x86_64 0:2.10-1.el7 will be erased
--> Finished Dependency Resolution

Removed:
  jansson.x86_64 0:2.10-1.el7
Dependency Removed:
  NetworkManager.x86_64 1:1.8.0-9.el7                                                   NetworkManager-adsl.x86_64 1:1.8.0-9.el7

 binaries]# rpm -qa | grep -i jansson
 binaries]#

 binaries]# yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Examining cjose-0.5.1-1.el7.centos.x86_64.rpm: cjose-0.5.1-1.el7.centos.x86_64
Marking cjose-0.5.1-1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package cjose.x86_64 0:0.5.1-1.el7.centos will be installed
--> Processing Dependency: pkgconfig(jansson) >= 2.3 for package: cjose-0.5.1-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requires: pkgconfig(jansson) >= 2.3

**Comment by marcjay** [comment]
I'm seeing the same issue as well, and have tried the step mentioned above of removing the jansson package first. I see this was closed a day later without response, is there a way to resolve this?

**Comment by zandbelt** [comment]
consistency is the key here:

```
yum remove jansson
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-2.10-1.el7.x86_64.rpm
yum localinstall -y ~/jansson-2.10-1.el7.x86_64.rpm
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-devel-2.10-1.el7.x86_64.rpm
yum localinstall -y ~/jansson-devel-2.10-1.el7.x86_64.rpm
wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.0/cjose-0.5.1-1.el7.centos.x86_64.rpm
yum localinstall -y ~/cjose-0.5.1-1.el7.centos.x86_64.rpm
wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.7/mod_auth_openidc-2.3.8-1.el7.x86_64.rpm
yum localinstall -y ~/mod_auth_openidc-2.3.8-1.el7.x86_64.rpm
```

**Comment by marcjay** [comment]
Ok many thanks @zandbelt
