### ISSUE TITLE
libpcre dependency on amazon linux

### ISSUE THREAD

**Issue by jaiminbhatt7** [zmartzone/mod_auth_openidc#356]
###### Environment

- mod_auth_openidc version 2.3.4
- Apache version 2.2.34
- platform/distro Amazon Linux

###### Expected behaviour
Successfully install mod_auth_openidc on Amazon Linux 2018.03

###### Actual behaviour
I was able to install cjose
```
sudo yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm
```

After that when I try to install mod_auth_openidc
```
Error: Package: mod_auth_openidc-2.3.4-1.el7.centos.x86_64 (/mod_auth_openidc-2.3.4-1.el7.centos.x86_64)
           Requires: libpcre.so.1()(64bit)
```

**Comment by zandbelt** [comment]
As the name suggests, the CentOS packages are for CentOS Linux not for Amazon Linux. There's no binary package for Amazon Linux; building/maintaining one would require a commercial discussion.
