### ISSUE TITLE
Apache segmentation fault when relative URL is set to the logout query parameter

### ISSUE THREAD

**Issue by Sinokra** [zmartzone/mod_auth_openidc#357]
###### Environment

- mod_auth_openidc version 2.3.3
- Apache version 2.4.10
- platform/distro : Red Hat Entreprise Linux Server release 6.9 (Santiago)

###### Example
To reproduce :
OIDCRedirectURI https://**<redirect_uri>**

Request the logout URL : https://**<redirect_uri>**?logout=**/<my_relative_URL>**

###### Expected behaviour
The agent redirects to the relative URL, on the same actual domain, after the logout

###### Actual behaviour
A segmentation fault is throw from Apache and no redirection is done. Depending on the environnment , the Apache can fall down and send HTTP 503 to all requests. In such case, a restart is necessary. 

If I specify the URL domain, the logout works fine : https://**<redirect_uri>?logout=<my_domain>/<my_relative_URL>.**

**Comment by zandbelt** [comment]
This was addressed in 38172c73e027d1348225f6f08809f6e6c95db145 and released with [2.3.4](https://github.com/zmartzone/mod_auth_openidc/releases/tag/v2.3.4).

**Comment by Sinokra** [comment]
Hi,

Thanks for your reactivity.

Regards,
Vivien
