### ISSUE TITLE
Select a claim from the userinfo endpoint to set the REMOTE_USER variable

### ISSUE THREAD

**Issue by phirivet** [zmartzone/mod_auth_openidc#360]
###### Environment

- mod_auth_openidc version current (master branch)
- Apache 2.4
- Ubuntu Xenial

###### Expected behaviour

Select a claim from the userinfo endpoint to set the REMOTE_USER variable on OpenID Connect protected paths.

###### Actual behaviour

Only one of the claims from the jwt token can be selected to set the REMOTE_USER variable.

###### Minimized example

I try to authenticate against a GitLab OAuth2 server but the jwt token has only these claims:
iss
sub
aud
exp
iat
nonce
auth_time

The "sub" claim is a unique alphanumeric identifier not human readable.

The other claims are get from the userinfo endpoint:
name
nickname
email
email_verified
website
profile
picture
groups

I tried to set the configuration below:
OIDCRemoteUserClaim "nickname"
But mod_auth_openidc does not found the claim.

###### Configuration and Log files

[Mon May 14 11:56:53.820161 2018] [auth_openidc:error] [pid 4552:tid 140053581887232] [client XXX.XXX.XXX.XXX:43812] oidc_get_remote_user: OIDCRemoteUserClaim is set to "nickname", but the id_token JSON payload did not contain a "nickname" string

**Comment by zandbelt** [comment]
That should work. Can you paste the full log so it is clear what information is passed in exactly? There should be a "merge" action of id_token and userinfo claims before setting the remote user.

**Comment by zandbelt** [comment]
On closer inspection of the log message  it seems like you're using an old version of mod_auth_openidc, namely <= 1.8.9. This issue was addressed in 1.8.10 and beyond and the log message has changed since then.

See the release notes of 1.8.10 https://github.com/zmartzone/mod_auth_openidc/releases/tag/v1.8.10 and https://github.com/zmartzone/mod_auth_openidc/pull/145 of June 2016.

**Comment by phirivet** [comment]
You're right. I have download the last version from your release page and it works fine.

Thank you for your help and sorry for my mistake.

**Comment by josy1024** [comment]
`OIDCRemoteUserClaim upn
`
this simple apache config line changes the content of REMOTE_USER var to OIDC_CLAIM_**upn**!
THANKS!

(using external authentication backend!)
/etc/icingaweb2/authentication.ini
[autologin]
backend = external
