### ISSUE TITLE
Installing dependencies on OpenSUSE Leap 42

### ISSUE THREAD

**Issue by Amiiya** [zmartzone/mod_auth_openidc#363]
Hi there!

I need to get this to work on Suse. I need to install the dependency "cjose" but it always fails. 
In some StackOverflow Thread it was recommended to create symlinks:
```
sudo ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/libssl.so.10
sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/libcrypto.so.10
```

Is there a better way to install the mod_auth_openidc Module to my Apache2?

###### Environment

- mod_auth_openidc version (e.g. 2.1.5)
- Apache version (e.g. 2.4.8)
- platform/distro (e.g. Ubuntu Xenial or Centos 7)

###### Expected behaviour
Install the Cjose RPM.

###### Actual behaviour
```
opensuse-leap-42:/vagrant/apache-service # rpm -i mod_auth_openidc-2.3.0-1.el7.centos.x86_64.rpm
error: Failed dependencies:
        cjose is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        hiredis is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        httpd is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        libcjose.so.0()(64bit) is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        libcrypto.so.10()(64bit) is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        libcrypto.so.10(libcrypto.so.10)(64bit) is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        libhiredis.so.0.12()(64bit) is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
        libssl.so.10()(64bit) is needed by mod_auth_openidc-2.3.0-1.el7.centos.x86_64
opensuse-leap-42:/vagrant/apache-service # rpm -i cjose-0.5.1-1.el7.centos.x86_64.rpm
error: Failed dependencies:
        libcrypto.so.10()(64bit) is needed by cjose-0.5.1-1.el7.centos.x86_64
        libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit) is needed by cjose-0.5.1-1.el7.centos.x86_64
        libcrypto.so.10(libcrypto.so.10)(64bit) is needed by cjose-0.5.1-1.el7.centos.x86_64
        pkgconfig(libcrypto) >= 1.0.1 is needed by cjose-0.5.1-1.el7.centos.x86_64
```

###### Configuration
Latest Zypper-Version of Openssl:
- OpenSSL 1.0.2j-fips  26 Sep 2016

To get to this point I already installed serveral packages.
- jansson-2.11-1.fc29.x86_64.rpm
- jansson-devel-2.11-1.fc29.x86_64.rpm
- zlib-1.2.11-7.fc29.x86_64.rpm
- zlib-devel-1.2.11-7.fc29.x86_64.rpm

**Comment by zandbelt** [comment]
There are no supported packages for OpenSUSE. Custom builds and non-supported packages can be delivered as part of a commercial support agreement. You can contact info@zmartzone.eu if you want more information on that.

**Comment by Amiiya** [comment]
So there is no way to get this mod for SLES? What Alternatives do i have if I need openid connect for SuSE?  
 
  Am Fr., Mai 18, 2018 at 15:26 schrieb Hans Zandbelt<notifications@github.com>:   
There are no supported packages for OpenSUSE. Custom builds and non-supported packages can be delivered as part of a commercial support agreement. You can contact info@zmartzone.eu if you want more information on that.

**Comment by zandbelt** [comment]
Your options are to purchase commercial support or to compile/build from source code yourself.
