### ISSUE TITLE
OIDC_id_token_{payload,serialized} header keys should be configurable or avoid '_'

### ISSUE THREAD

**Issue by bostrick** [zmartzone/mod_auth_openidc#365]
when using OIDCPassIDTokenAs "claims" or "serialized", the header key seems to be non-configurable.

This causes issues in the python uwsgi world (which for security reasons doesn't honor "_" in header keys.) (see also https://github.com/zmartzone/mod_auth_openidc/issues/71).

It would be nice if these headers were configurable, or avoided problematic "_".  

Thanks!

**Comment by zandbelt** [comment]
Even if this configurable prefix is implemented, you'd still have to deal with the underscores in `<PREFIX>id_token` and `<PREFIX>access_token`. Perhaps it is better to rewrite the headers using mod_headers, converting the underscores to dashes?

**Comment by zandbelt** [comment]
Does using mod_headers work for you?

**Comment by bostrick** [comment]
Indeed, I did a mod_headers rewrite and it worked fine.   Thanks for the suggestion, and the good work!
