### ISSUE TITLE
Access Token is not regenerated after expiry in implicit flow

### ISSUE THREAD

**Issue by GitShaffi** [zmartzone/mod_auth_openidc#366]
###### Environment

- mod_auth_openidc version 2.3.4
- Apache version 2.4.6
- platform/distro Centos 7

###### Expected behaviour
Once the issued access token expires, the module should be able to call the authorize api again and get a new access token in implicit flow

###### Actual behaviour
Access Token is not regenerated after expiry in implicit flow

**Comment by zandbelt** [comment]
What do you mean by "call the authorize API again"? Can you give an example?

**Comment by GitShaffi** [comment]
@zandbelt /authorize endpoint of the Authorization Provider.
So, the issue is, we have the implicit OIDC flow which doesn't have a refresh token.
However we want the access token to be regenerated on expiry!

**Comment by zandbelt** [comment]
Firstly, why would you use the Implicit flow in a web server client whereas the more secure code flow is available? Secondly, the module doesn't "know" when the access token is expired, only the application using it knows. So when your application notices it has expired, it could throw away the session cookie and refresh the page so the users browser would be redirected to the Provider.

**Comment by GitShaffi** [comment]
@zandbelt We have our UI (OPENID) and API (OAUTH) behind the same **mod-auth-openidc**. If the token expires, all our api call fails. So the workaround would be to delete to delete the cookie.
Or to use the 'authorization code' flow, which will give you the refresh token. Do you recommend any other better way?

**Comment by zandbelt** [comment]
For sure using the authorization code flow is the better way. Since you have a refresh token you can then use a module hook to refresh the access token instead of manually deleting the session cooking and generating a redirect, see: https://github.com/zmartzone/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens
