### ISSUE TITLE
Logout of just local session when session management is enabled

### ISSUE THREAD

**Issue by kujenga** [zmartzone/mod_auth_openidc#367]
###### Expected behaviour

We would like to provide our users with the ability to just logout from a specific service that is protected by mod_auth_openidc, and separately, allow them to log out fully using the `end_session_endpoint`. We have discovery setup on our provider, so when the user is directed to `https://example.com/callback?logout=`, then they are directed to the value of the `end_session_endpoint` that is in the discovery document.

I would expect that we could override this behavior of a "full logout" by providing an explicit value to the `logout` query parameter. For example `https://example.com/callback?logout=https://example.com` would just land them back on the homepage.

The reason this is useful to us is that it would allow the user to login on behalf of another account.

###### Actual behaviour

The value of the `logout` query parameter seems to be ignored when there is an `end_session_endpoint` in the discovery metadata.

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

###### Configuration and Log files
*Config and logs for the minimized example, possibly provided as attachments.*

We set `OIDCProviderMetadataURL` for the discovery URL and `OIDCRedirectURI https://example.com/callback` to configure the redirect URI.

**Comment by zandbelt** [comment]
I don't think a local logout would achieve want you describe: it would mean that only the application session is killed, which doesn't imply that the OP session is killed so you would not be able to login as a different user. But you can force that by just removing the mod_auth_openidc session cookie from within your app.

**Comment by kujenga** [comment]
I see, thanks for the quick response! I didn't quite describe the intended effect correctly, going through the OAuth2 flow in our application causes the user to re-select the _organization_ that they are authenticating on behalf of, which causes the resource server that is using `mod_auth_openidc` to display different content to that user after they switch organizations. A similar, more generic situation, might be re-triggering the OAuth2 flow to ask the user to give access to more scopes.

We can look into manually setting the cookie to remove `mod_auth_openidc`, but just to be clear there is not a way to do this using just the functionality of this module itself?

Thanks for pointing out `post_logout_redirect_uri`, I will take a closer look at that.

**Comment by zandbelt** [comment]
Correct, there's no way in mod_auth_openidc to do a local logout when session management is enabled because in an SSO eco-system it is almost pointless to do a local logout (at least security-wise).
