### ISSUE TITLE
id_token signature could not be validated

### ISSUE THREAD

**Issue by skauffmann** [zmartzone/mod_auth_openidc#368]
###### Environment

- mod_auth_openidc version : 2.1.5
- Apache version : 2.4.29
- platform/distro : RED HAT

The module could not validate id_token using keys or cert file.
```
...
[Fri May 25 10:54:49.145929 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/proto.c(1623): [client 138.21.89.192:6867] oidc_proto_parse_idtoken: successfully parsed (and possibly decrypted) JWT with header={"typ":"JWS","alg":"RS256"}, and payload={"iss":"https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam","sub":"64323734326430312d65306635313164622d38303231663833652d6562316564646239","aud":"ecb4f63d-0517-4d29-bf0f-d067a6cc3737","exp":1527242089,"iat":1527238489,"nonce":"TWZf56PcX8RQJpHd-_g-vzdVDU_PehCbxC14dO4A8FU","acr":{"values":["xxxx/arca/dev"]}}, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
...
[Fri May 25 10:54:49.195739 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/util.c(812): [client 138.21.89.192:6867] oidc_util_http_call: response={"keys":[{"kty":"RSA","use":"sig","alg":"RS256","n":"ANUTWBJB+kK6mZTKwaXjbQCrdB/oySHtEbufqJAM5a5YFDLTTinghwxhKeect7qPZvrPVf8jIQdpFo/nmNXgBqnYjIyk5evxo7rvv1gVmNozmZZOnChbrUasfy+gKvaDPNEuGHny7A6BkIulXAZk+KmBjzZM1N/RUd0i/P4zogYOw728tparqJbSBmP7uXl59u747k+w6naWvm1Y90/vAULosfyclzisJlKtp/yHE+mEACyMA9XHAkhAax9s/CXuGaZF1k5zr3jxlmj+uhXgRKGxtnUqId8UW57YeTPF/gV3qLF3QhFtHf1LRNJaS1TvsnjM3gkxRjlUbB9CH4MVDKE=","e":"AQAB"}]}, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.195877 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/cache/common.c(626): [client 138.21.89.192:6867] oidc_cache_set: enter: https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/keys (section=j, len=412, encrypt=0, ttl(s)=3599, type=shm), referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.195942 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/cache/common.c(653): [client 138.21.89.192:6867] oidc_cache_set: successfully stored 412 bytes in shm cache backend for key https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/keys, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.195960 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/proto.c(1381): [client 138.21.89.192:6867] oidc_proto_get_key_from_jwks: search for kid "(null)" or thumbprint x5t "(null)", referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.196720 2018] [auth_openidc:warn] [pid 2119572:tid 140262011561728] [client 138.21.89.192:6867] oidc_proto_get_key_from_jwks: oidc_jwk_parse_json failed: [src/jose.c:316: oidc_jwk_parse]: JWK parsing failed: invalid argument [file: jwk.c, function: _cjose_jwk_import_RSA, line: 1459]\n\n, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.196746 2018] [auth_openidc:debug] [pid 2119572:tid 140262011561728] src/proto.c(1512): [client 138.21.89.192:6867] oidc_proto_get_keys_from_jwks_uri: returning 0 key(s) obtained from the (possibly cached) JWKs URI, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.196845 2018] [auth_openidc:error] [pid 2119572:tid 140262011561728] [client 138.21.89.192:6867] oidc_proto_jwt_verify: JWT signature verification failed: [src/jose.c:970: oidc_jwt_verify]: could not verify signature against any of the (1) provided keys\n, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
[Fri May 25 10:54:49.196863 2018] [auth_openidc:error] [pid 2119572:tid 140262011561728] [client 138.21.89.192:6867] oidc_proto_parse_idtoken: id_token signature could not be validated, aborting, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/
```

I got the following error "id_token signature could not be validated".

I have tried with the cert file by replacing OIDCProviderJwksUri by OIDCOAuthVerifyCertFiles but I got the same result.

cert file :
```
-----BEGIN CERTIFICATE-----
MIIFDDCCA/SgAwIBAgIkAhwR/6b9XD+hhJYvNkuy7tEClGEl4W1R4u5lFh2UAgIpCa6vMA0GCSqG
SIb3DQEBCwUAMDYxGjAYBgNVBAsTEU9yZ2FuaXphdGlvbmFsIENBMRgwFgYDVQQKFA92aXJ0dWFs
ODcyX3RyZWUwHhcNMTUxMTAyMTA0NzA3WhcNMTcxMTAyMTA0NzA3WjAVMRMwEQYDVQQDEwp2aXJ0
dWFsODcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1RNYEkH6QrqZlMrBpeNtAKt0
H+jJIe0Ru5+okAzlrlgUMtNOKeCHDGEp55y3uo9m+s9V/yMhB2kWj+eY1eAGqdiMjKTl6/Gjuu+/
WBWY2jOZlk6cKFutRqx/L6Aq9oM80S4YefLsDoGQi6VcBmT4qYGPNkzU39FR3SL8/jOiBg7Dvby2
lquoltIGY/u5eXn27vjuT7Dqdpa+bVj3T+8BQuix/JyXOKwmUq2n/IcT6YQALIwD1ccCSEBrH2z8
Je4ZpkXWTnOvePGWaP66FeBEobG2dSoh3xRbnth5M8X+BXeosXdCEW0d/UtE0lpLVO+yeMzeCTFG
OVRsH0IfgxUMoQIDAQABo4ICITCCAh0wHQYDVR0OBBYEFKkLDTfjwqOQcThhd6WWeMw/bfSxMB8G
A1UdIwQYMBaAFIIuSBUptuErEWF4Cph2e7h5P4gnMAsGA1UdDwQEAwIEsDCCAcwGC2CGSAGG+DcB
CQQBBIIBuzCCAbcEAgEAAQH/Ex1Ob3ZlbGwgU2VjdXJpdHkgQXR0cmlidXRlKHRtKRZDaHR0cDov
L2RldmVsb3Blci5ub3ZlbGwuY29tL3JlcG9zaXRvcnkvYXR0cmlidXRlcy9jZXJ0YXR0cnNfdjEw
Lmh0bTCCAUigGgEBADAIMAYCAQECAUYwCDAGAgEBAgEKAgFpoRoBAQAwCDAGAgEBAgEAMAgwBgIB
AQIBAAIBAKIGAgEXAQH/o4IBBKBYAgECAgIA/wIBAAMNAIAAAAAAAAAAAAAAAAMJAIAAAAAAAAAA
MBgwEAIBAAIIf/////////8BAQACBAbw30gwGDAQAgEAAgh//////////wEBAAIEBvDfSKFYAgEC
AgIA/wIBAAMNAEAAAAAAAAAAAAAAAAMJAEAAAAAAAAAAMBgwEAIBAAIIf/////////8BAQACBBH/
pv0wGDAQAgEAAgh//////////wEBAAIEEf+m/aJOMEwCAQICAQACAgD/Aw0AgAAAAAAAAAAAAAAA
AwkAgAAAAAAAAAAwEjAQAgEAAgh//////////wEBADASMBACAQACCH//////////AQEAMA0GCSqG
SIb3DQEBCwUAA4IBAQATta864F/T2aS0MV/7WmhDuYgqPJpJvFkcuzlPgzonc8r6r+T+e5xlsSTE
gDqU6TCNzZV1dIt6oeqfWVk8KCzLZY9z77ibRSAujyQ0W8kG4k0LNO0pwHqgA2tb+a5nyGq/t1ak
fUXjJEL7pEtwgbJV9sQEObxJr2O2oDu1BfZpOyWrj9rsYM+tv8OVB0khA+9H7qRDtWM2vsvSUiXh
y39Aoa+eM8ovJ3Rq15RErTCOXL+IyqS1oBPhv5DduaIHmivR433ifk0lL0SwDYq6jaUGxTAj7oOX
Em7mPeXMz1J6FKxUzuC0DngAVOQkvD512WfN73NIyEekXdlJUZI00aZC
-----END CERTIFICATE-----

```

I was able to valide the id_token with this public key from https://jwt.io/ so I don't understand why the module can't validate the id_token...

###### Configuration

```
OIDCProviderIssuer "https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/namz"
OIDCProviderAuthorizationEndpoint "https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/authz"
OIDCProviderTokenEndpoint "https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/token?resourceServer=IdentityProvider"
OIDCClientID "ecb4f63d-0517-4d29-bf0f-d067a6cc3737"
OIDCClientSecret "XXXXXXXXXXXXXXXXXXXXX"
OIDCRedirectURI "http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/OPX2/glpproint3.intra.xxxx:17100/"
OIDCCryptoPassphrase "XXXXXXXXXXXXXXX"
OIDCSSLValidateServer Off
LogLevel debug

OIDCProviderJwksUri "https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/keys"
```
Full logs are available in attachment [error.log](https://github.com/zmartzone/mod_auth_openidc/files/2038719/error.log)

**Comment by zandbelt** [comment]
It seems that the content returned from the JWKS URI `https://virtual872.labtech.pls.xxxx:8443/nidp/oauth/nam/keys` is invalid; please check the "e" value of the first RSA signing key in there.

**Comment by zandbelt** [comment]
Did that help?

**Comment by skauffmann** [comment]
Unfortunatly not.
The JWKS file is generated by MicroFocus NetIQ Access Manager 4.4.
Since you have said the key could be corrupted I have tried to use the PEM file directly but have the same issue.

**Comment by zandbelt** [comment]
Can you paste the contents of the JWKs URL?

**Comment by skauffmann** [comment]
`{"keys":[{"kty":"RSA","use":"sig","alg":"RS256","n":"ANUTWBJB+kK6mZTKwaXjbQCrdB/oySHtEbufqJAM5a5YFDLTTinghwxhKeect7qPZvrPVf8jIQdpFo/nmNXgBqnYjIyk5evxo7rvv1gVmNozmZZOnChbrUasfy+gKvaDPNEuGHny7A6BkIulXAZk+KmBjzZM1N/RUd0i/P4zogYOw728tparqJbSBmP7uXl59u747k+w6naWvm1Y90/vAULosfyclzisJlKtp/yHE+mEACyMA9XHAkhAax9s/CXuGaZF1k5zr3jxlmj+uhXgRKGxtnUqId8UW57YeTPF/gV3qLF3QhFtHf1LRNJaS1TvsnjM3gkxRjlUbB9CH4MVDKE=","e":"AQAB"}]}`

**Comment by zandbelt** [comment]
the value for "n" is not base64url encoded (rather seems base64 only), neither is NetIQ a certified OIDC library so you'll have to look for the solution on that side

**Comment by skauffmann** [comment]
Thanks for your reply and your time.
Even if the JWK doesn't work, I dont' understand why the cert file doesn't work too :

I got the same error in log :
`[Fri Jun 01 15:55:16.003414 2018] [auth_openidc:debug] [pid 2679047:tid 139824265860864] src/util.c(2003): [client 138.21.89.91:23555] oidc_util_create_symmetric_key: key_len=86, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/`

`[Fri Jun 01 15:55:16.003486 2018] [auth_openidc:debug] [pid 2679047:tid 139824265860864] src/proto.c(1529): [client 138.21.89.91:23555] oidc_proto_jwt_verify: "jwks_uri" is not set, signature validation will only be performed against statically configured keys, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/`

`[Fri Jun 01 15:55:16.003913 2018] [auth_openidc:error] [pid 2679047:tid 139824265860864] [client 138.21.89.91:23555] oidc_proto_jwt_verify: JWT signature verification failed: [src/jose.c:974: oidc_jwt_verify]: could not verify signature against any of the (1) provided keys\n, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/`

`[Fri Jun 01 15:55:16.003930 2018] [auth_openidc:error] [pid 2679047:tid 139824265860864] [client 138.21.89.91:23555] oidc_proto_parse_idtoken: id_token signature could not be validated, aborting, referer: http://glpproint3.sax.xxxx:17000/GPS_PRO_INT3/`

I have tried to add some trace to know where the issue is and seems to be here on the cjose lib :
https://github.com/cisco/cjose/blob/master/src/jws.c#L922
`jwk->kty != CJOSE_JWK_KTY_RSA`

Did you have any idea about the issue with the cert file ?

**Comment by zandbelt** [comment]
Why do you think you've configured it with a trusted cert? That's not possible in the OIDC case. From the log it seems that you've now not set any JWKs URI which means that it only has the client_secret to check HS256 signatures against, but that's not what the Provider uses.

You'll need to fix the JWKs URI representation.

**Comment by zandbelt** [comment]
NetIQ is working on OIDC certification which will solve this issue as well.
