### ISSUE TITLE
Access Token Revocation and Cache Invalidation

### ISSUE THREAD

**Issue by maureen2018** [zmartzone/mod_auth_openidc#375]
Hello.
I have a problem with access token revocation and cache invalidation.
I want to revoke access token by request <redirect_uri>?remove_at_cache=<access_token>.
But there was a 404 error.
response：
       The requested URL /portal/callback was not found on this server.
I checked the error log file.
error log:
`[Wed Jul 11 11:40:56.243412 2018] [auth_openidc:debug] [pid 16081] src/mod_auth_openidc.c(3320): [client  ] oidc_check_user_id: incoming request: "/portal/callback?remove_at_cache=301192f3-8989-48b0-bdd8-3236cd49a344", ap_is_initial_req(r)=1
[Wed Jul 11 11:40:56.243424 2018] [auth_openidc:debug] [pid 16081] src/util.c(2191): [client  ] oidc_util_hdr_in_get: Cookie=i18next=zh-CN; amlbcookie=01; iPlanetDirectoryProOld=AQIC5wM2LY4SfcyPF6ZVBNjXf-S3VOpkDqKMkY8brtcP2ro.*AAJTSQACMDEAAlNLABQtODE5MTg5NzQ5NjI1NDk5ODE0OQACUzEAAA..*; mod_auth_openidc_session=06e53567-7ff0-4225-a341-de1608447685; iPlanetDirectoryPro=301192f3-8989-48b0-bdd8-3236cd49a344; sso-access-token=301192f3-8989-48b0-bdd8-3236cd49a344; js.headfoot.logon.name=%u9808%u85E4%20%u91CD
[Wed Jul 11 11:40:56.243434 2018] [auth_openidc:debug] [pid 16081] src/util.c(1001): [client  ] oidc_util_get_cookie: returning "mod_auth_openidc_session" = "06e53567-7ff0-4225-a341-de1608447685"
[Wed Jul 11 11:40:56.243439 2018] [auth_openidc:debug] [pid 16081] src/cache/common.c(567): [client  ] oidc_cache_get: enter: 06e53567-7ff0-4225-a341-de1608447685 (section=s, decrypt=1, type=shm)
[Wed Jul 11 11:40:56.243517 2018] [auth_openidc:debug] [pid 16081] src/cache/common.c(601): [client  ] oidc_cache_get: cache hit: return 2019 bytes from shm cache backend for encrypted key Sa9XR4r46n1Hd0bOs-2kxcaOo70jEAPKiT3VEbybRyg
[Wed Jul 11 11:40:56.243614 2018] [auth_openidc:debug] [pid 16081] src/util.c(1153): [client  ] oidc_util_request_matches_url: comparing "/portal/callback"=="/portal/callback"
[Wed Jul 11 11:40:56.243732 2018] [auth_openidc:debug] [pid 16081] src/cache/common.c(567): [client  ] oidc_cache_get: enter: 301192f3-8989-48b0-bdd8-3236cd49a344 (section=a, decrypt=1, type=shm)
[Wed Jul 11 11:40:56.243817 2018] [auth_openidc:debug] [pid 16081] src/cache/common.c(603): [client  ] oidc_cache_get: cache miss from shm cache backend for encrypted key oxg2iaPfCVbbYx6fA-vQvszzWQsfJG5sdkrPK-LPhRs
[Wed Jul 11 11:40:56.243840 2018] [auth_openidc:error] [pid 16081] [client  ] oidc_handle_remove_at_cache: no cached access token found for value: 301192f3-8989-48b0-bdd8-3236cd49a344
`
It prompts not to find the cache.But there is a value for the accesstoken in the cache.
Is there a problem with my configuration? Is there any need to configure this method about remove_at_cache?

Thank you.

**Comment by zandbelt** [comment]
Though not really explicit in the docs, this feature is only used in an OAuth 2.0 Resource Server setup. It removes the cache access token introspection results. It seems you've configured an OpenID Connect RP setup in which the access token is not introspected at all but only used towards e.g. the userinfo endpoint. So I'd say this is not applicable here.

**Comment by maureen2018** [comment]
Thank you for your help.
I see.
In addition, I want to logout user.
So i logout the user with <redirect_uri>?remove_at_cache.
But I found that method only achieves the effect of closing the session, and the accesstoken is still valid.
I want to prompt to log in again after logout，but it can not.

auth_openidc.conf:

`

### openID Connect用設定
OIDCProviderMetadataURL https://{opensso}/opensso/oauth2/.well-known/openid-configuration
OIDCClientID openIG
OIDCClientSecret 123456
OIDCCryptoPassphrase test
OIDCResponseType "id_token token"
OIDCScope "openid profile userinfo email"

OIDCRedirectURI https://{opensso}/portal/callback


# require login on re-connect
OIDCPathAuthRequestParams "prompt=login"

### OAuth2.0用設定
OIDCOAuthIntrospectionEndpoint      https://{opensso}/opensso/oauth2/tokeninfo

OIDCOAuthIntrospectionTokenParamName access_token
OIDCOAuthIntrospectionEndpointMethod GET

OIDCOAuthRemoteUserClaim access_token


OIDCOAuthSSLValidateServer Off
OIDCOAuthAcceptTokenAs cookie:access_token
OIDCOAuthClientID openIG
OIDCOAuthClientSecret 123456

### add access-token to cookie to Request Header on first time
SetEnvIf Cookie "(^|;\ *)access_token=([^;\ ]+)" exist_access_token
SetEnvIf Cookie "(^|;\ *)mod_auth_openidc_session=([^;\ ]+)" exist_openidc_session

RequestHeader set exist_access_token  "%{exist_access_token}e" 

#RequestHeader set exist_sso-user-id  "%{exist_sso-user-id}e"

RequestHeader set exist_openidc_session  "%{exist_openidc_session}e"

<If "%{Env:exist_access_token} != 1">
  RequestHeader set cookie "%{exist_cookie}e; access_token=%{OIDC_access_token}e" env=OIDC_access_token
  </If>


### add Header to Responce Header
Header Add Set-Cookie "access_token=%{OIDC_access_token}e;Path=/" env=OIDC_access_token

# no operation timeout
OIDCSessionInactivityTimeout 1800

# session timeout
OIDCSessionMaxDuration 28800`


Is there a way to log out and re-login in mod_auth_openidc?

Thank you very much.

**Comment by maureen2018** [comment]
And is there a way to revoke the accesstoken in mod_auth_openidc?
Thank you.
