### ISSUE TITLE
openidc requires one of OIDCProviderIssuer, OIDCProviderMetadataURL, or OIDCMetadataDir

### ISSUE THREAD

**Issue by VxJasonxV** [zmartzone/mod_auth_openidc#379]
I was trying to set up openidc to delegate auth to GitHub and I came up short. I primarily attempted to follow the "OAuth-APIs" section at https://github.com/zmartzone/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server#oauth-apis , but this example does not include one of the three required fields present in my error string

```
[Fri Aug 10 09:56:13.649632 2018] [auth_openidc:error] [pid 9277] oidc_check_config_openid_openidc: one of 'OIDCProviderIssuer', 'OIDCProviderMetadataURL' or 'OIDCMetadataDir' must be set
```

The fields I had set were:

```
OIDCOAuthClientID		
OIDCOAuthClientSecret		
OIDCOAuthIntrospectionEndpoint	
OIDCOAuthIntrospectionEndpointMethod
OIDCOAuthSSLValidateServer	
OIDCOAuthRemoteUserClaim	
OIDCOAuthIntrospectionTokenParamName
OIDCRedirectURI		
OIDCCryptoPassphrase		
```

But none of the aforementioned 3 fields seem to be relevant to add in additionally. Is the documentation out of date?

###### Environment

- mod_auth_openidc version: 2.3.3-1build1
- Apache version: 2.4.34-1+ubuntu18.04.1+deb.sury.org+7
- platform/distro: Ubuntu Bionic

**Comment by zandbelt** [comment]
I don't think Github supports OpenID Connect for "delegate auth". Setting up a Resource Server probably does not what you need. What are you trying to achieve?

**Comment by VxJasonxV** [comment]
I'm trying to delegate authentication for an internal protected resource to GitHub using OAuth. The resource itself doesn't have a login system, it relies on the web server serving it to manage it.

**Comment by zandbelt** [comment]
Github is not OpenID Connect compliant so this module cannot interface with it. For some reason Github decided to roll their their own proprietary protocol that builds on top of OAuth 2.0 (just as OpenID Connect does).
