### ISSUE TITLE
Client authentication (if the client has credentials) or the client_id parameter is required for an authorization request using the code grant type

### ISSUE THREAD

**Issue by patricklunney** [zmartzone/mod_auth_openidc#384]
Hi Hans, 

I'm using a Dockerfile to test out mod_auth_openidc to give to some customers but I'm hitting some errors. The module works when going up against Google, but when I go against our internal IDP I get this error: 

`client authentication (if the client has credentials) or the client_id parameter is requiredfor an authorization request using the code grant type.","error":"invalid_client"`

###### Environment

Here is the Dockerfile to install mod_auth_openidc:
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install php -y
RUN apt-get install libapache2-mod-php -y
RUN apt-get install libcurl3 -y
RUN apt-get install libjansson4 -y
RUN apt-get install wget -y
RUN wget http://ftp.us.debian.org/debian/pool/main/liba/libapache2-mod-auth-openidc/libapache2-mod-auth-openidc_1.6.0-1_amd64.deb
RUN dpkg -i libapache2-mod-auth-openidc_1.6.0-1_amd64.deb
RUN a2enmod auth_openidc
RUN a2dismod ssl

Apache.conf contains the correct information as well:
`#OIDC config

<Location />
	AuthType openid-connect
	Require valid-user
</Location>

OIDCProviderMetadataURL ${METADATA}
OIDCClientID ${CLIENT_ID}
OIDCClientSecret ${CLIENT_SECRET}
OIDCRedirectURI ${REDIRECT_URI}
OIDCScope ${SCOPE}
OIDCCryptoPassPhrase P@ssw0rd
OIDCRemoteUserClaim sub
OIDCOAuthSSLValidateServer Off
OIDCSSLValidateServer Off
`

I think this is the error: 
`
https://...com/as/token.oauth2, data=grant_type=authorization_code&code=dce3H6JOhDIQ6SCfOSacVUDZOhftJFphi6rSAAAB&redirect_uri=http%3A%2F%2Flocalhost%2Fredirect, content_type=application/x-www-form-urlencoded, basic_auth=sampleclient:test123test, bearer_token=(null), ssl_validate_server=0, referer: http://localhost/
`

Should it be posting the client_id and secret in basic?

###### Configuration and Log files
Log files:
`[Fri Aug 24 01:16:05.528792 2018] [auth_openidc:debug] [pid 14] src/util.c(562): [client 172.17.0.1:40706] oidc_util_http_post_form: post data="grant_type=authorization_code&code=dce3H6JOhDIQ6SCfOSacVUDZOhftJFphi6rSAAAB&redirect_uri=http%3A%2F%2Flocalhost%2Fredirect", referer: http://localhost/

[Fri Aug 24 01:16:05.528797 2018] [auth_openidc:debug] [pid 14] src/util.c(427): [client 172.17.0.1:40706] oidc_util_http_call: url=https://...com/as/token.oauth2, data=grant_type=authorization_code&code=dce3H6JOhDIQ6SCfOSacVUDZOhftJFphi6rSAAAB&redirect_uri=http%3A%2F%2Flocalhost%2Fredirect, content_type=application/x-www-form-urlencoded, **basic_auth=sampleclient:test123test**, bearer_token=(null), ssl_validate_server=0, referer: http://localhost/

[Fri Aug 24 01:16:06.079298 2018] [auth_openidc:debug] [pid 14] src/util.c(516): [client 172.17.0.1:40706] oidc_util_http_call: response={"error_description":"Client authentication (if the client has credentials) or the client_id parameter is requiredfor an authorization request using the code grant type.","error":"invalid_client"}\r\n, referer: http://localhost/

[Fri Aug 24 01:16:06.080615 2018] [auth_openidc:error] [pid 14] [client 172.17.0.1:40706] oidc_util_json_string_print: oidc_util_check_json_error: response contained a "error" key with string value: "invalid_client", referer: http://localhost/

[Fri Aug 24 01:16:06.080633 2018] [auth_openidc:error] [pid 14] [client 172.17.0.1:40706] oidc_util_json_string_print: oidc_util_check_json_error: response contained a "error_description" key with string value: "Client authentication (if the client has credentials) or the client_id parameter is required for an authorization request using the code grant type.", referer: http://localhost/`

**Comment by patricklunney** [comment]
NOTE - the clientid/secret are correct, because I can get a client_credentials bearer token from them.

**Comment by zandbelt** [comment]
You really must not use version 1.6.0 which almost 4 years old now and has known bugs and security issues. Support for such an old version can only be delivered on a commercial basis. Having said that, to me it looks like the server hasn't  configured any authentication method for the client or perhaps a different authentication method than `client_secret_basic`.
