### ISSUE TITLE
Handle Apache maintained session on logout

### ISSUE THREAD

**Issue by manglade** [zmartzone/mod_auth_openidc#386]
Hello, 

It would be very handy to be able to explicitly request the module to destroy only the Apache session only during a logout. Currently the only way to achieve such a result is to avoid setting the OIDCProviderEndSessionEndpoint parameter. This parameter is in conflict with the OIDCProviderMetadataURL. 

If you want to have an Apache only logout, the only way is to remove the OIDCProviderMetadataURL parameter and redefine every subsequent parameter by hand. 

It would be much easier and much more flexible to be able to request an Apache logout only no matter the values specified in OIDCProviderMetadataURL. 

Regards,

**Comment by zandbelt** [comment]
One may argue that destroying an Apache session locally doesn't make any sense in an SSO system since hitting it again will just log you in since there's an ongoing IDP SSO session that was not destroyed. Would you care to list your arguments as to why destroying a local session is useful?

**Comment by manglade** [comment]
Hello, 

Actually, it does makes sense when your IdP is used as a multi-service auth provider (like Google connect). Then you end up on such use-cases that a user may logout from one of the service without being logged out from the others.

**Comment by zandbelt** [comment]
And what happens if the user clicks their bookmark or type in the URL of the service again?

**Comment by zandbelt** [comment]
Why not just redirect to the master portal? When logging out from master it would trigger single logout and kill the session in you application too by virtue of session management and the usage of `OIDCProviderEndSessionEndpoint`. That is the point of introducing session management based logout.

**Comment by manglade** [comment]
If we only redirect to the master and disconnect from the master and come back to the child portal without relogging we are still connected.

**Comment by zandbelt** [comment]
not if "disconnect" from master triggers SLO as it should: the fix is to make master do global logout instead of have the application do local logout

**Comment by zandbelt** [comment]
I forgot to mention that you can create you own local logout by killing the `mod_auth_openidc_session` cookie.
