### ISSUE TITLE
Inconsistent behavior with OAuth2 login

### ISSUE THREAD

**Issue by amdonov** [zmartzone/mod_auth_openidc#388]
When using oauth20 authtype, login with a default access_token generated from Keycloak fails after the first request (this is a bit inconsistent). I see the following in /var/www/html/error_log

oidc_cache_shm_get_key: could not construct cache key since key size is too large (1987 >= 512)

###### Environment

- mod_auth_openidc-2.3.7-1.el7.x86_64
- httpd-2.4.6-80.el7.centos.1.x86_64
- CentOS 7 Docker
###### Expected behaviour

Successful login with headers populated

###### Actual behaviour

Login in first attempt with 401 on subsequent attempts

###### Minimized example

OIDCProviderMetadataURL https://idp.127.0.0.1.xip.io/auth/realms/master/.well-known/openid-configuration
OIDCRedirectURI https://api-gateway.127.0.0.1.xip.io/example/oauth2callback
OIDCCryptoPassphrase E3C26B8359784E97BEC67C5939C4FCEC
OIDCClientID api-gateway
OIDCClientSecret cfcc117b-0b6e-48d7-9fde-0a8f154d3846
OIDCProviderTokenEndpointAuth client_secret_basic
OIDCInfoHook userinfo
OIDCRemoteUserClaim email
OIDCScope "openid email"
OIDCPassUserInfoAs json
OIDCPassIDTokenAs payload

<Location /example>
  AuthType openid-connect
  Require valid-user
</Location>

OIDCOAuthIntrospectionEndpoint https://idp.127.0.0.1.xip.io/auth/realms/master/protocol/openid-connect/token/introspect
OIDCOAuthClientID api-gateway
OIDCOAuthClientSecret cfcc117b-0b6e-48d7-9fde-0a8f154d3846
OIDCOAuthRemoteUserClaim email
<Location /api>
  AuthType oauth20
  Require valid-user
</Location>

###### Configuration and Log files

/var/www/html/example/index.php contains the following
<?php
phpinfo();
?>

I use the value of OIDC_access_token to construct a curl command like the following

curl -k -v -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPOTZCeHRIb2EySldPT3J0YlQ2WENMMkVma0JHZkFUQXd4YkxRenJRZTBzIn0.eyJqdGkiOiIzYmMzN2M3Mi1kYmY3LTQ0NGQtODY4Yy02MmNmMmE2NTYzNDMiLCJleHAiOjE1MzY3MTc5NDMsIm5iZiI6MCwiaWF0IjoxNTM2NzE3ODgzLCJpc3MiOiJodHRwczovL2lkcC4xMjcuMC4wLjEueGlwLmlvL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFwaS1nYXRld2F5Iiwic3ViIjoiMmQwZDAxNmYtMWUxNC00M2YyLWExMDUtMDgyZjA5ODc1ZTk3IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBpLWdhdGV3YXkiLCJub25jZSI6Im0zUHk0ZkxDSzUzUkdsb1dtS2JybGJ3R3BERGV3VFBjaXpaRzNYUF9FNGMiLCJhdXRoX3RpbWUiOjE1MzY3MTUyNTEsInNlc3Npb25fc3RhdGUiOiJjYjY2OTQwMy1jMTAwLTRmODQtOWYwOC01NjA1MzYzZmE3MzkiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vYXBpLWdhdGV3YXkuMTI3LjAuMC4xLnhpcC5pbyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiQWFyb24gRG9ub3ZhbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkFhcm9uIiwiZmFtaWx5X25hbWUiOiJEb25vdmFuIiwiZW1haWwiOiJkb25vdmFuX2Fhcm9uQGJhaC5jb20ifQ.TEX5idHhjqb-QDYv0c6-84ZqJBZPy33Xd-hldPjEvtyY5Rk4IwV77fFbNVSv1ZsssNkFtm9uucM6-riN2UPc57hRR3ecOTttvCY97eO-AzR86AOU3pQU1QZbscZocJcX6C2kijpTfqb-KTgGOp3wT6P9jF2Ik6kwcsE4ry5PcK5n5rTFG6duX3WWJnWKzbsM0BXGcl1Npm8Wjx3Vv9admRmYkMM0C1YoB-9aC7645bUsvwiGux20RVvttJk22yWAU38gW5f1tjBPMO1fFTUuzxt6MW30f2AvYYTcFiycXnQX3j6qSYw6-xQ_s_-RApEes6nFSE1foNbIlcl50Qwmkw' https://api-gateway.127.0.0.1.xip.io/api/

It usually works the first time that I make the request, but it fails on subsequent attempts with the reported error

Should I attempt to reduce the claims in the access_token? I didn't add any beyond the default.

**Comment by zandbelt** [comment]
This is *sort of a known* issue that has to do with the size of reference-style access tokens vs. JWT-based access tokens but I'd advise you to change your setup to avoid this:

In your setup Keycloak returns JWT access tokens in the token response/auth-flow. That means those tokens actually don't need to be introspected but can be validated locally since all information is already embedded in the JWT. See: https://github.com/zmartzone/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server#local-validation-1

a) So rather than setting:
```
OIDCOAuthIntrospectionEndpoint https://idp.127.0.0.1.xip.io/auth/realms/master/protocol/openid-connect/token/introspect
OIDCOAuthClientID api-gateway
OIDCOAuthClientSecret cfcc117b-0b6e-48d7-9fde-0a8f154d3846
```
you'd set:
```
OIDCOAuthVerifyJwksUri https://idp.127.0.0.1.xip.io/auth/realms/master/protocol/openid-connect/certs
```
and the JWT token will be verified locally, just by checking a signature with keys downloaded (cached and refreshed) from the JWKS URL, rather than calling out to Keycloak.

b) Alternatively you could start encrypting the cache so the cache keys are hashed with:
```
OIDCCacheEncrypt On
```

c) or even set:
```
OIDCOAuthTokenExpiryClaim
```
to a bogus value so that no expiry claims is found and the token will not be cached. Of course the latter comes at the cost of lookup overhead.

**Comment by amdonov** [comment]
Thanks! Your suggestions solved my issue.
