### ISSUE TITLE
Invalid Authorization Header can cause Segmentation fault

### ISSUE THREAD

**Issue by amdonov** [zmartzone/mod_auth_openidc#389]
I was doing some negative testing and deleted a portion of my valid access token, a JWT token, and passed it in an Authorization Header via curl. It caused the httpd child process to have a segmentation fault and exit.

###### Environment

- mod_auth_openidc-2.3.7-1.el7.x86_64
- httpd-2.4.6-80.el7.centos.1.x86_64
- CentOS 7 Docker

###### Expected behaviour

401 Unauthorized

###### Actual behaviour

Server crash

###### Minimized example

Make a request like the following with this header value. Different random values for the token behaved as expected. This one caused problems.

curl -k -v -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJPOTZCeHRIb2EySldPT3J0YlQ2WENMMkVma0JHZkFUQXd4YkxRenJRZTBzIn0.eyJqdGkiOiJiN2RjNDYyNy00N2ZmLTQ2M2YtOGE1Yy00Yzg4NTQ2MmQ2NjgiLCJleHAiOjE1MzY3Nzg2NjcsIm5iZiI6MCwiaWF0IjoxNTM2NzQ5ODY3LCJpc3MiOiJodHRwczovL2lkcC4xMjcuMC4wLjEueGlwLmlvL2F1dGgvcmVhbG1zL21hc3RlciIsImF1ZCI6ImFwaS1nYXRld2F5Iiwic3ViIjoiMmQwZDAxNmYtMWUxNC00M2YyLWExMDUtMDgyZjA5ODc1ZTk3IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBpLWdhdGV3YXkiLCJub25jZSI6IkR2SFJVczI0eFhPZU1XZXo0NmZ0NDFOOUItTl9lNVU3SnlhaFpreHdWOWMiLCJhdXRoX3RpbWUiOjE1MzY3NDg3NDgsInNlc3Npb25fc3RhdGUiOiIwMmVlMDU0My1mNzY1LTQ0MDAtODQ5Yy0wOTQxZjhkMjA5NjYiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vYXBpLWdhdGV3YXkuMTI3LjAuMC4xLnhpcC5pbyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY3JlYXRlLXJlYWxtIiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1Zc2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZW1haWwiOiJkb25vdmFuX2Fhcm9uQGJhaC5jb20ifQ.GOhte_Yq09xcC9s7dIClt-QIw-uhH03Zw4LBzdJAHtL7rYCWlWjFA9ouXWqlUlhSvfI-Gpqw6ob7v6vsFcPHPM2IY8E-1Y3jhOs7gBO3Ebg6BbERrEGXPNwtx8HEjlJV3zTDVgwgTrTdfTxEmbwmhfpbzhfJ8oYU77YUH4Ofty8D13iwkKQDQICO0FK6WxoXWexVpCfVeHdVMUZDGBJ8j14uic4nD7asy8VNm-1lvkmRZnUjz_VyX4EQW8SgNbK7FJjSEIYigh7RkQPLDykn9tzgFvUU-uwpHrkLkoEgVlVgiUpPJOxqe-2nzOXkfeIAdTXtgKP3nc0wYl_mx6RjEg' https://api-gateway.127.0.0.1.xip.io/api/

###### Configuration and Log files

OIDCProviderMetadataURL https://idp.127.0.0.1.xip.io/auth/realms/master/.well-known/openid-configuration
OIDCRedirectURI https://api-gateway.127.0.0.1.xip.io/example/oauth2callback
OIDCCryptoPassphrase E3C26B8359784E97BEC67C5939C4FCEC
OIDCClientID api-gateway
OIDCClientSecret cfcc117b-0b6e-48d7-9fde-0a8f154d3846
OIDCProviderTokenEndpointAuth client_secret_basic
OIDCInfoHook userinfo
OIDCRemoteUserClaim email
OIDCScope "openid email"

<Location /example>
  AuthType openid-connect
  Require valid-user
</Location>

OIDCOAuthVerifyJwksUri https://idp.127.0.0.1.xip.io/auth/realms/master/protocol/openid-connect/certs
OIDCOAuthRemoteUserClaim email
OIDCCacheEncrypt On
<Location /api>
  AuthType auth-openidc
  Require valid-user
</Location>

You can see from the following log where other errors in the token were handled properly just prior to this example that causes the crash.

[Wed Sep 12 11:01:50.323076 2018] [auth_openidc:error] [pid 377] [client 10.1.0.9:41954] oidc_oauth_validate_jwt_access_token: could not parse JWT from access_token: [src/jose.c:749: oidc_jwt_parse]: cjose_jws_import failed: invalid argument [file: jws.c, function: cjose_jws_import, line: 778]\n\n
[Wed Sep 12 11:02:21.681645 2018] [auth_openidc:error] [pid 378] [client 10.1.0.9:42048] oidc_oauth_validate_jwt_access_token: could not parse JWT from access_token: [src/jose.c:749: oidc_jwt_parse]: cjose_jws_import failed: invalid argument [file: jws.c, function: cjose_jws_import, line: 798]\n\n
[Wed Sep 12 11:03:18.123456 2018] [core:notice] [pid 376] AH00052: child pid 379 exit signal Segmentation fault (11)
[Wed Sep 12 11:03:18.123555 2018] [core:notice] [pid 376] AH00052: child pid 380 exit signal Segmentation fault (11)
[Wed Sep 12 11:03:18.123582 2018] [core:notice] [pid 376] AH00052: child pid 381 exit signal Segmentation fault (11)

**Comment by zandbelt** [comment]
Thanks for catching this! I'll submit a fix asap and release a new version soon after that.

**Comment by zandbelt** [comment]
That's now part of a fresh 2.3.8 release: https://github.com/zmartzone/mod_auth_openidc/releases

I'll add the CentOS 7 RPM later today, thanks again!

**Comment by zandbelt** [comment]
Thank you for your contribution! As a courtesy I have added the CentOS RPM to the 2.3.8 release already ;-)

Keep stuff like this coming...!
