### ISSUE TITLE
PassUserInfoAs option for OAuth 2.0 Resource Server

### ISSUE THREAD

**Issue by amdonov** [zmartzone/mod_auth_openidc#391]
This is an enhancement request. I really like the ability to pass user info as json option that's available via the OIDCPassUserInfoAs option. Would it be possible to get a similar OIDCOPassUserInfoAs option for oauth2 authentication? Thanks

**Comment by zandbelt** [comment]
Please define "oauth2 authentication".

**Comment by amdonov** [comment]
Intended to say oauth20, as in "AuthType oauth20". I'm actually using AuthType auth-openidc. When I access a page with a cookie such as "Cookie: mod_auth_openidc_session=3f3338d5-4e3e-4547-b4d1-c4f51a591511", the claims headers are displayed according to the value of OIDCPassUserInfoAs. However, when I access the same page without the cookie but present a token in an Authorization header, claims are always displayed as individual values. I'm now using "OIDCPassUserInfoAs claims" for consistency, but I'd like to use OIDCPassUserInfoAs json.

**Comment by zandbelt** [comment]
No there's no such option today. What you can do is pickup the `OIDC_access_token` from the envvars/header and apply a simple base64url decode operation on the 2nd part separated by dots. That gives you the JSON payload you're looking for.

**Comment by amdonov** [comment]
Based on your comment, I dug into the code a bit. Looks like only claims from the access_token are available when using token/oauth20 authentication. Is that correct? Our access_tokens only contain a subset of user claims. I'd like to also have access to the userinfo claims too. Is it it possible to add that functionality?

**Comment by zandbelt** [comment]
in `oauth20` mode there is no user info endpoint to call, that's an OpenID Connect feature
