### ISSUE TITLE
Support for nested claims with arrays

### ISSUE THREAD

**Issue by hpbieker** [zmartzone/mod_auth_openidc#392]
With Keycloak you get claims that that contain arrays. These are not supported in mod_auth_openidc, however it would be very usefull if this could be matched with `Require claim resource_access.someClient.roles:someRole4`.
```
"realm_access": {
    "roles": [
      "someRole1",
      "someRole2"
    ]
  },
  "resource_access": {
    "someClient": {
      "roles": [
      "someRole3",
      "someRole4"
      ]
    }
  }
```

**Comment by zandbelt** [comment]
Sounds useful indeed and perhaps not that hard. I'll take a look shortly.

**Comment by zandbelt** [comment]
Added support in the commits referenced above; please confirm e.g. by downloading 2.3.9rc0 from https://mod-auth-openidc.org/download/?C=M;O=D

**Comment by hpbieker** [comment]
Looks good to me, thanks!

**Comment by zandbelt** [comment]
I added a test that shows this works:
https://github.com/zmartzone/mod_auth_openidc/commit/c30d3e8fdc9d696727b3af1004a4fe6d29c02af9

check your log files to see what comes in from the OP

**Comment by hpbieker** [comment]
I had to configure KeyCloak to insert the role claim into the ID token.

**Comment by Kali-** [comment]
i guest about the roles was on the reply beacuse is present in the jwt token, and this is probably wrong

**Comment by ChristianCiach** [comment]
Using the current release 2.3.10.1, this doesn't seem to work for me. I've tripple checked that my access_token does indeed contain the realm_access-role:

```
  "realm_access": {
    "roles": [
      "my_role"
    ]
  },
```

And it is configured as such:

```
<Location /login>
        AuthType openid-connect
        <RequireAll>
                Require claim realm_access.roles:my_role
        </RequireAll>
        ProxyPass http://127.0.0.1:20202/oauthlogin
        ProxyPassReverse http://127.0.0.1:20202/oauthlogin
</Location>
```

But still, I get 401 errors. Is it necessary that the claims are contained in the id_token instead of the access_token?

Here is something that I understand even less: Since over a year we are using this config:

```
<Location /login>
        AuthType openid-connect
        <RequireAll>
                Require claim roles:my_role
        </RequireAll>
        ProxyPass http://127.0.0.1:20202/oauthlogin
        ProxyPassReverse http://127.0.0.1:20202/oauthlogin
</Location>
```

As you can see, we are referring to the "roles" claim as if it were a top-level claim, but this is not and never was the case. Still, it works. Why is this so? Are nested claims-objects and -arrays flattened?

**Comment by zandbelt** [comment]
your server debug log would tell you everything you need

**Comment by FarrynDE** [comment]
Is there any way to claim more than one group maybe via regex or concat?
So Something like realm_access.roles:GroupA,GroupB or realm_access.roles:~(GroupA|GroupB)

**Comment by zandbelt** [comment]
> Is there any way to claim more than one group maybe via regex or concat? So Something like realm_access.roles:GroupA,GroupB or realm_access.roles:~(GroupA|GroupB)

you should be able to do that with Apache 2.4's `RequireAny` directive or revert to https://github.com/zmartzone/mod_auth_openidc/wiki/Authorization#complex-expressions
