### ISSUE TITLE
The requested URL /login was not found on this server

### ISSUE THREAD

**Issue by ultimoamore** [zmartzone/mod_auth_openidc#393]
I've set up mod_auth_openidc without problems in the past, but this time it just won't work; I get redirected to the proper auth provider, login, but then:

The requested URL /login was not found on this server

This must be a silly thing, but I just can't figure it out

**Comment by ultimoamore** [comment]
can you please give me an hint about it???

**Comment by zandbelt** [comment]
Can you please read the text that you've ignored and deleted in the issue template
