### ISSUE TITLE
The requested URL /login was not found on this server

### ISSUE THREAD

**Issue by ultimoamore** [zmartzone/mod_auth_openidc#394]
###### Environment

- mod_auth_openidc version 2.3.7-1
- Apache version 2.4.34-1
- debian sid

###### Expected behaviour
redirect to oauth loging page, login, redirect to required application

###### Actual behaviour
redirect to oauth loging page, login -> The requested URL /login was not found on this server

###### Minimized example

in /etc/apache2/mods-enabled/auth_openidc.conf, set properties:

OIDCProviderIssuer <value>
OIDCProviderAuthorizationEndpoint <value>
OIDCClientID <value>
OIDCClientSecret <value>
OIDCRedirectURI http://myhost:45678/login
OIDCScope "openid profile"
OIDCCryptoPassphrase <value>
OIDCAuthNHeader SM_USER
OIDCRemoteUserClaim sub
OIDCClaimPrefix <value>

Oauth set up to redirect to  http://myhost:45678/login

Never had any problem setting up mod_auth_openidc in other machines

###### Configuration and Apache server log files

apache log file:

[Mon Oct 08 09:13:24.981650 2018] [auth_openidc:warn] [pid 31000] oidc_check_config_openid_openidc: the URL scheme (http) of the configured OIDCRedirectURI SHOULD be "https" for security reasons (moreover: some Providers may reject non-HTTPS URLs)
[Mon Oct 08 09:13:24.984829 2018] [mpm_prefork:notice] [pid 31000] AH00163: Apache/2.4.34 (Debian) configured -- resuming normal operations
[Mon Oct 08 09:13:24.984858 2018] [core:notice] [pid 31000] AH00094: Command line: '/usr/sbin/apache2'

(but no problem at all using the same provider with http in another setup)

**Comment by zandbelt** [comment]
Please read the text again (and send this type of question to the mailing list) then read the README.md and the auth_openidc.conf about the `OIDCRedirectURI` setting,  then protect /login with 'AuthType openid-connect'
