### ISSUE TITLE
Current URL not constructed properly on forward proxy

### ISSUE THREAD

**Issue by archzone** [zmartzone/mod_auth_openidc#395]
When `AuthType openid-connect` is used to protect a resource on Apache configured as a forward proxy, the browser is presented with an invalid Location header in the legitimate 302 response to a callback?.. request after successful login to an OIDC Provider. This happens due to `<Proxy>` directive containing an absolute URI of the protected resource, e.g. `<Proxy "http://remotehost:8380">` (as it should). In the meantime, `oidc_get_current_url(request_rec *r)` function always expects the URI to be relative to the host, so it constructs the current URL by concatenating `oidc_get_current_url_base(r)`, `r->uri` and `r->args`,

As a result, the browser (Firefox) panics with the "Corrupted Content Error" (as it probably should). The browser is configured to use forward proxy at `proxyhost:8180` and the URL typed in the address bar is `http://remotehost:8380/private/` (and `index.html` exists on that server).

Note that the same configuration works perfectly well on Apache configured as a reverse proxy, given the resource URI is relative, e.g. `<Location "/private">`, so it is not mod_auth_openidc or OIDC Provider configuration issue. In this scenario, the browser has no proxy configured.

###### Environment

- mod_auth_openidc version: 2.3.8
- Apache version: 2.4.34
- platform/distro: Win64/Lounge

###### Expected behaviour

[Response header returned by callback?..]
`Location: http://remotehost:8380/private/`

###### Actual behaviour

[Response header returned by callback?..]
`Location: http://remotehost:8380http://remotehost:8380/private/`

###### Minimized example

[Forward proxy configuration]
`<VirtualHost _default_:8180>`
`  ProxyRequests On`
`  LogLevel auth_openidc:debug`
`  <Proxy "http://remotehost:8380">`
`    AuthType openid-connect`
`    Require valid-user`
`  </Proxy>`
`  OIDCProviderMetadataURL [url]`
`  OIDCRedirectURI http://remotehost:8380/callback`
`  OIDCCryptoPassphrase [pp]`
`  OIDCClientID [id]`
`  OIDCClientSecret [secret]`
`  OIDCScope "openid"`
`</VirtualHost>`

###### Configuration and Apache server log files

`[Sun Oct 07 23:39:30.202971 2018] [auth_openidc:debug] [pid 13164:tid 1212] util.c(501): [client 127.0.0.1:62765] oidc_get_current_url: current URL 'http://remotehost:8380http://remotehost:8380/private/'`
`...`
`[Sun Oct 07 23:39:48.221229 2018] [auth_openidc:debug] [pid 13164:tid 1196] mod_auth_openidc.c(2006): [client 127.0.0.1:62783] oidc_handle_authorization_response: session created and stored, returning to original URL: http://remotehost:8380http://remotehost:8380/private/, original method: get`
`[Sun Oct 07 23:39:48.221229 2018] [auth_openidc:debug] [pid 13164:tid 1196] util.c(2273): [client 127.0.0.1:62783] oidc_util_hdr_table_set: Location: http://remotehost:8380http://remotehost:8380/private/`

**Comment by zandbelt** [comment]
I'm trying to wrap my head around your setup: you have setup a forwarding proxy to which you need to authenticate using OpenID Connect? If so, is the IDP excluded from the forwarding proxy?

**Comment by archzone** [comment]
Correct: need to protect URIs with OpenID Connect on the forward proxy, and IDP is running on another server. If I may suggest a simple fix, the `oidc_get_current_url(request_rec *r)` function or alternatively, the `oidc_get_current_url_base(r)` function that it calls, needs to check if the supplied `r->uri` is absolute, i.e. starts with a protocol scheme, and construct the current URL accordingly.

**Comment by zandbelt** [comment]
Just to make sure: the configuration of your forward proxy in the browser makes an exception for the IDP URL(s)?

**Comment by archzone** [comment]
In the most simple case, yes. But it works either way: as the IDP URIs are open and can be accessed either directly or through a forward proxy - it would not make any difference for the IDP server.

**Comment by zandbelt** [comment]
welll the latter is what I'm wondering about: if you're authenticating through a forward proxy to an IDP that is not excluded from the forward proxy, how will your requests ever reach the IDP; the issue is not with the IDP server, the issue is with the browser config and the forward proxy

**Comment by archzone** [comment]
By default, Apache configured as a forward proxy will forward requests to any destination specified in the browser address bar, even without explicit `<Proxy>` directives, including those to the IDP, provided the browser is configured to go through the proxy in the first place. But let's take the most simple case, where the IDP base URL is excluded in the proxy settings, just to rule the concern out.

**Comment by zandbelt** [comment]
I'd like you to test 510721e which is part of 2.3.9rc4; since you're on Windows you probably need a binary build to do so?

**Comment by zandbelt** [comment]
the Windows build of 2.3.9rc4 is here: https://mod-auth-openidc.org/download/mod_auth_openidc-2.3.9rc4-apache-2.4.x-win64.zip

**Comment by zandbelt** [comment]
@archzone  thanks for helping out and testing so swiftly
