### ISSUE TITLE
Unable to cache JWT (inconsistent)

### ISSUE THREAD

**Issue by arsci** [zmartzone/mod_auth_openidc#397]
I'm running into an issue where my Apache reverse proxy is unable to consistently cache the JWT. With a basic configuration I'm running into the following error after successfully retrieving the token from the auth endpoint:

```
[Wed Oct 17 01:03:22.100973 2018] [auth_openidc:warn] [pid 1676:tid 140480511694592] [client ] oidc_cache_set: could NOT store 263 bytes in shm cache backend for key < key >
```

I've tried alternate caching options as described here:
https://github.com/zmartzone/mod_auth_openidc/wiki/Caching 

However whenever I use any of the options (Redis, Memcache, File all do not work) Apache seg faults immediately when trying to cache the token. The most information I can get from the logs looks like this:

```
[Wed Oct 17 00:44:54.232726 2018] [auth_openidc:debug] [pid 7592:tid 140440414099200] src/util.c(809): [client 107.3.136.234:47758] oidc_util_http_call: HTTP response code=200, referer: <referer url>

[Wed Oct 17 00:44:54.232832 2018] [auth_openidc:debug] [pid 7592:tid 140440414099200] src/util.c(814): [client 107.3.136.234:47758] oidc_util_http_call: response= { auth response here }

[Wed Oct 17 00:44:54.234140 2018] [auth_openidc:debug] [pid 7592:tid 140440414099200] src/oauth.c(342): [client 107.3.136.234:47758] oidc_oauth_parse_and_cache_token_expiry: expiry_claim_name=exp, expiry_format_absolute=1, expiry_claim_is_mandatory=0, referer: <referer url>

[Wed Oct 17 00:44:54.234203 2018] [auth_openidc:debug] [pid 7592:tid 140440414099200] src/oauth.c(390): [client ] oidc_oauth_cache_access_token: caching introspection result, referer: <referer url>

[Wed Oct 17 00:44:54.234255 2018] [auth_openidc:debug] [pid 7592:tid 140440414099200] src/cache/common.c(627): [client 107.3.136.234:47758] oidc_cache_set: enter: <token> (section=a, len=263, encrypt=1, ttl(s)=332, type=file), referer: <referer url>

[Wed Oct 17 00:44:55.176565 2018] [core:notice] [pid 7589:tid 140440933730176] AH00051: child pid 7592 exit signal Segmentation fault (11), possible coredump in /etc/apache2/dump
```

I'm unable to find any coredump information, I've tried changing the log level down to trace and am still unable to get any further useful information. I haven't tried using a shared filesystem yet, but considering it is segfaulting with every other option including writing locally to /tmp, my guess is the result will be similar.

###### Environment

- mod_auth_openidc version 2.3.8-1
- Apache version 2.4.18
- Ubuntu 16.04.5 LTS

These are the Apache modules I have loaded:

 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 auth_openidc_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 remoteip_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 substitute_module (shared)
 xml2enc_module (shared)

**Comment by zandbelt** [comment]
Could you send me a more complete log file (at least a few hundred lines before and after the cache failure, and a few hundred before the segfault) that includes the token as well? You can send it to support@zmartzone.eu if it contains too sensitive information for a public forum.

**Comment by arsci** [comment]
Thanks, I've emailed 2 log files to you. The 'key too large' logs with the default configuration, and the segfault logs when configured for file.

**Comment by zandbelt** [comment]
The first error is sort of OK: you're introspecting JWT access tokens which are better off with local validation. Encrypted cache would hash the key so it is not a problem, but the "shm" backend does not encrypt by default so it is a problem there.

I cannot reproduce the segfault even with the literal values of the JWT token and the introspection result. I suspect a local setup issue, to confirm we'd need to try a few things.

Firstly, can you try "shm" cache with `OIDCCacheEncrypt On`? That solves the key length issue and I'm interested to see if that also produces the segfault.

Then: can you try "file" cache with `OIDCCacheEncrypt On`? If that works it would suggest that the issue is with the OpenSSL encryption routines.

**Comment by arsci** [comment]
Apache segfaults with 'shm' cache and `OIDCCacheEncrypt On`, as well as 'file' cache and `OIDCCacheEncrypt On`.

**Comment by zandbelt** [comment]
sorry I meant "file" with `OIDCCacheEncrypt Off`

**Comment by arsci** [comment]
That works, and I now see a file in the directory (/tmp that I specified in the apache config) called `mod-auth-openidc-cache-file-last-cleaned`

**Comment by zandbelt** [comment]
I'd be interested in the OpenSSL version on your system then; also do you use a pre-built package?

**Comment by arsci** [comment]
`OpenSSL 1.0.2g  1 Mar 2016`

As for prebuilt package, do you mean prebuild package of mod_auth_openidc? For openssl I just have installed whatever comes on the AWS Ubuntu 16.04 AMI.

**Comment by arsci** [comment]
Is there a way to fix the segfault? A version of openssl I should upgrade or downgrade that might get around the issue I'm running into?

**Comment by zandbelt** [comment]
- are you using a pre-built mod_auth_openidc package? if so, from where?
- are there multiple versions of openssl installed?

**Comment by arsci** [comment]
1) Yes, from here: https://github.com/zmartzone/mod_auth_openidc/releases

The installer I used was this: libapache2-mod-auth-openidc_2.3.8-1.xenial+1_amd64.deb
And I also needed to install this to get it to work: libcjose0_0.5.1-1.xenial.1_amd64.deb

2) Not that I can tell. 1.0.2g is the only one that appears to be installed.

**Comment by zandbelt** [comment]
Can you reproduce this in a clean Xenial environment, e.g. a docker environment (since I cannot...)?

**Comment by zandbelt** [comment]
Any progress with that?

**Comment by zandbelt** [comment]
assuming this fixed itself...
