### ISSUE TITLE
HTTPS protection not working properly on forward proxy

### ISSUE THREAD

**Issue by archzone** [zmartzone/mod_auth_openidc#398]
When `AuthType openid-connect` is used to protect an HTTPS resource on Apache configured as a forward proxy, the module does not redirect to the IDP login page, and lets the server return 407 instead.

What makes this scenario different from accessing an HTTP resource, is the use of `CONNECT` method instead of `GET` in the latter case. The browser sends `CONNECT` to the forward proxy, which in turn sends `CONNECT` to the origin server, essentially creating a tunnel for the browser to communicate with the origin server directly using HTTPS. The proxy does not have visibility into the encrypted traffic, but it not required in our scenario: the OpenID Connect authentication needs to happen before the HTTPS resource is accessed.

When other types of Apache authentication are tried, such as `AuthType Basic`, everything works as expected: the authentication happens first, followed by the actual HTTPS resource access.

###### Environment

- mod_auth_openidc version: 2.3.9rc4
- Apache version: 2.4.34
- platform/distro: Win64/Lounge

###### Expected behaviour

The browser is redirected to the IDP login page (similar to how HTTP access is handled).

###### Actual behaviour

The server responds with `407 Proxy Authentication Required` to the browser.

###### Minimized example

[Forward proxy configuration]
`<VirtualHost _default_:8180>`
`  ProxyRequests On`
`  AllowConnect 8343`
`  LogLevel auth_openidc:debug`
`  <Proxy "remotehost:8343">`
`    AuthType openid-connect`
`    Require valid-user`
`  </Proxy>`
`  OIDCProviderMetadataURL [url]`
`  OIDCRedirectURI https://remotehost:8343/callback`
`  OIDCCryptoPassphrase [pp]`
`  OIDCClientID [id]`
`  OIDCClientSecret [secret]`
`  OIDCScope "openid"`
`</VirtualHost>`

###### Configuration and Apache server log files

[HTTPS resource accessed in the browser]
`https://remotehost:8343/private/`

[Forward proxy access log]
`127.0.0.1 - - [18/Oct/2018:18:03:59 -0400] "CONNECT remotehost:8343 HTTP/1.1" 407 415`

[Forward proxy error log]
`[Thu Oct 18 18:03:59.170114 2018] [auth_openidc:debug] [pid 14444:tid 1204] mod_auth_openidc.c(3645): [client 127.0.0.1:55336] oidc_check_user_id: incoming request: "(null)?(null)", ap_is_initial_req(r)=1`
`[Thu Oct 18 18:03:59.170114 2018] [auth_openidc:debug] [pid 14444:tid 1204] util.c(1024): [client 127.0.0.1:55336] oidc_util_get_cookie: returning "oidc_session" = <null>`
`[Thu Oct 18 18:03:59.170114 2018] [auth_openidc:debug] [pid 14444:tid 1204] util.c(1176): [client 127.0.0.1:55336] oidc_util_request_matches_url: comparing "(null)"=="/callback"`

**Comment by archzone** [comment]
This issue is somewhat related to #395 in a sense that some Apache variables are set up differently on the forward proxy. When the HTTPS resource is requested, such environment variables are as follows:

`HTTP_HOST=remotehost:8343`
`REQUEST_SCHEME=http`
`REQUEST_METHOD=CONNECT`
`REQUEST_URI=remotehost:8343`

Unlike the case of HTTP access, `REQUEST_URI` does not start with a protocol scheme, as the actual protocol (HTTPS, in our case) is going to be layered over the HTTP tunnel established by `CONNECT` but a bit later. Perhaps, the module can treat such `REQUEST_METHOD` as a special case, and assume `REQUEST_URI` of `"/"` and `REQUEST_SCHEME` implied from `OIDCRedirectURI` (or anyhow), to match to the normal behavior (redirect to the IDP login page, similar how HTTP requests are handled).

**Comment by zandbelt** [comment]
I looked into this a bit but it seems it is impossible to return `state` and `code` to the `redirect_uri`: the `CONNECT` request will not contain those parameters, they will only be sent after the proxied connection has been established. That's a chicken/egg problem.

For `AuthType auth20` it is different since one can send the bearer token in a proxy header if the client allows it, e.g. with cURL you'd use `--proxy-header Authorization: bearer <token>`.

Anyway, in an unmodified client both won't work.
