### ISSUE TITLE
Configure exceeding state cookie disposal

### ISSUE THREAD

**Issue by HenriLefevrePro** [zmartzone/mod_auth_openidc#399]
We would like to be able to setup the behavior of mod_auth_openidc while reaching the limit number of cookies defined in **OIDCStateMaxNumberOfCookies** since v2.3.8 (see : https://github.com/zmartzone/mod_auth_openidc/issues/331). 

The idea is to add a new configuration parameter to choose between :

- Returning a HTTP 503 error code (as current 2.3.8 behavior)
- Deleting the oldest state cookie (Activated via the new parameter)

Example : A user will never have to kill cookies or to close his browser (to avoid 503) if he has more than OIDCStateMaxNumberOfCookies tabs open on the same authentication page.

This can occur for a user having many tabs open on a same domain, in that case UX will be improved.

**Comment by zandbelt** [comment]
Can you try 46758a7 and provide feedback?

**Comment by HenriLefevrePro** [comment]
Hi Hans,

Thanks a lot for this developement, I will test it as soon as possible an give a feedback.

Best Regards,

Henri

**Comment by zandbelt** [comment]
any luck with that?

**Comment by zandbelt** [comment]
well, it is now in [2.3.10](https://github.com/zmartzone/mod_auth_openidc/releases/tag/v2.3.10)
