### ISSUE TITLE
Dynamic Query String Parameters to Generic OIDC

### ISSUE THREAD

**Issue by rithoria** [zmartzone/mod_auth_openidc#401]
###### Environment

- mod_auth_openidc version (e.g. 2.3.3)
- Apache version (e.g. 2.4)
- platform/distro (RHEL 6.7)

###### Expected behaviour
Send String query parameters to OP while redirecting for authentication.
User request to website's protected path as per below
https://<my-site>/welcome?opentoken=<opentoken-dynamic-value>
Plugin redirects with below query strings
access_token_manager_id: <token_manager_id>
IdAdapterId: <IdAdapterID>
response_type: id_token token
scope: openid
client_id: <clientid>
state: XXXXXX
redirect_uir: https://<my-site>/callback
nonce: XXXXX

###### Actual behavior
Want to send opentoken=<opentoken-dynamic-value>
Went through https://github.com/zmartzone/mod_auth_openidc/wiki but could not figure out how to use this.

###### Minimized example
OIDCProviderMetadaURL https://<op-provider:9031>/.well-known/openid-configuration
OIDCProviderAuthorizationEndpoint https://<op-provider:9031>/as/authrization.oauth2?access_token_manager_id=XXXX&IdAdapterId=XXXX
OIDCClientID XXX
OIDCAuthClientID XXX
OIDCAuthClientSecret XXX
OIDCRedirectURI https://<my-site>/callback
OIDCCryptoPassphrase XXX
OIDCSessionType "client-cookie"
OIDCResponseTyppe "id_token token"
OIDCStateTimeout 3600
OIDCProviderAuthRequestMethod GET
OIDCOAuthIntrospectionEndpoint https://<op-provider:9031>/as/token.oauth2
OIDCOAuthIntrospectionEndpointAuth client_secret_basic
OIDCOAuthIntrospectionEndpointParams grant_tupe=urn%3Apingindentity.com%3Aoauth2%3Agrant_type%3Avalidate_bearer@access_token_manager_id=XXXX
OIDCOAuthRemoteUserClaim username
OIDCOAuthAcceptTokenAs cookie:access_token

###### Configuration and Apache server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Comment by zandbelt** [comment]
For the record: this would rely on a bilateral agreement between RP and OP to support additional parameters in the authorization request outside of the ones that are standardized. So it would only work with "customized" OPs.

**Comment by rithoria** [comment]
Yes, it's a customized OP and I'm trying below suggestion.
OIDCRedirectURI https://<my-site>/callback?target_link_uri=<my-site>&iss=<my-op>:9031&auth_request_params=**opentoken=xyz**

Now, opentoke=<open-token> value is a variable which I'm getting on Apache in very request by user. 
Can you please suggest how to use url encoding.

**Comment by rithoria** [comment]
Can you please help here.

**Comment by zandbelt** [comment]
Help with what? Passing on parameters that are dynamically determined is not possible today, that's why this is a feature request. Feel free to submit a PR>
