### ISSUE TITLE
Cannot load module: undefined symbol: oidc_authz_match_claim

### ISSUE THREAD

**Issue by dstefanMSFT** [zmartzone/mod_auth_openidc#403]
###### Environment

- mod_auth_openidc newest version
- Apache version 2.4
- platform/distro - Oracle Enterprise Linux (RHEL fork)

###### Expected behaviour
after compiling the module and loading it works

###### Actual behaviour
during the load Apache throws an error: missing symbol oidc_authz_match_claim
###### Minimized example
OEL requires modules to be complied and loaded using apxs2. we followed all the steps and during ther startup we get this:
<2018-11-07 19:54:21> <INFO> <OHS-4018> <Starting server ohs-01>
<2018-11-07 19:54:21> <INFO> <OHS-0> <Running /opt/webapps/Oracle12cR2/Middleware/Oracle_Home/wlserver/../ohs/bin/launch httpd -DOHS_MPM_EVENT -d /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/config/fmwconfig/components/OHS/instances/ohs-01 -k start -f /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/config/fmwconfig/components/OHS/instances/ohs-01/httpd.conf>
**<2018-11-07 19:54:21> <INFO> <OHS-0> <httpd: Syntax error on line 1101 of /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/config/fmwconfig/components/OHS/instances/ohs-01/httpd.conf: Cannot load /opt/webapps/Oracle12cR2/Middleware/Oracle_Home/ohs/modules/mod_auth_openidc.so into server: /opt/webapps/Oracle12cR2/Middleware/Oracle_Home/ohs/modules/mod_auth_openidc.so: undefined symbol: oidc_authz_match_claim>
<2018-11-07 19:54:22> <SEVERE> <OHS-0> </opt/webapps/Oracle12cR2/Middleware/Oracle_Home/wlserver/../ohs/bin/launch httpd -DOHS_MPM_EVENT -d /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/config/fmwconfig/components/OHS/instances/ohs-01 -k start -f /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/config/fmwconfig/components/OHS/instances/ohs-01/httpd.conf: exit status = 1>**
<2018-11-07 19:54:22> <INFO> <OHS-4005> <Check the instance log file for more information: /opt/webapps/OHS12cR2/Middleware/Oracle_Home/user_projects/domains/OHS_domain/servers/ohs-01/logs/ohs-01.log>
<2018-11-07 19:54:22> <SEVERE> <OHS-0> <Failed to start the server ohs-01>

**Comment by zandbelt** [comment]
I guess that's it: Oracle's Linux flavor is just not supported. Should you want support that requires a commercial discussion with support@zmartzone.eu
