### ISSUE TITLE
[Question] Can I leverage this for simple OAuth2.0 Client credential grant auth flow on proxy?

### ISSUE THREAD

**Issue by jeremyjpj0916** [zmartzone/mod_auth_openidc#405]
@zandbelt I see you have other interesting repo's, I made an issue in your lua oidc repo just the other day that you helped me out with. This should be my last question for a bit. I am playing with an Apache httpd server and was hoping this awesome plugin can meet my needs.

I need to call a gateway and get back an OAuth2.0 token from the gateways token url, cache that token for the time its valid and add it to a header when I  proxy, leveraging the proxy_module + proxy_http_module. Also needs to generate a new token when time is up or 401 unauthorized cause stale token occurs. 

I feel like this plugin can achieve that but based on documentation I can't find a basic config i need anywhere exactly. Documentation led me to these potential fields probably:

OIDCRedirectURI https://<hostname>/redirect_uri 
**(What point would this  have in my design/what should I set it to???, I don't want to redirect since not true OIDC, more OAuth2.0 client credential grant flow.)**

OIDCProviderTokenEndpoint https:gateway.com/my/token/url
(makes sense, no metadata endpoint for me, so configure directly to my OAuth2.0 token call endpoint)

OIDCClientID my_oauth2_clientid 

OIDCClientSecret my_oauth2_secret

OIDCProviderTokenEndpointAuth client_secret_post ?

OIDCCryptoPassphrase password (I can add this, guess it is like a salt or something of that nature as it lives in the cache?)

Bold is where my largest confusion is, also wondering if I will need anything else or a config that tells your plugin to add the token as Authorization: Bearer <token> in headers automagically ?

If manual, maybe in the rewrites.conf file can I just do 
RequestHeader set Authorization "Bearer "${OIDC_access_token} 
or something you expose that is accessible? Like I said, not super familiar with apache webserver 😆 

Thanks in advance if you have seen this case in the past.

**Comment by zandbelt** [comment]
as indicated in the text that you deleted from the issue template: please don't use the issue tracker for questions; having said that you probably want to take a look at https://github.com/zmartzone/mod_sts and use that in combination with mod_auth_openidc

**Comment by jeremyjpj0916** [comment]
Sorry man, you would be correct I was in a hurry this evening didn't read the template. Thanks for your assistance anyways, will review the mod_sts as well.

**Comment by rajavijaysingh** [comment]
@jeremyjpj0916  were you able to achieve this. I am looking to setup a proxy at apache for doing the oauth client credential flow
