### ISSUE TITLE
scope and group in access token

### ISSUE THREAD

**Issue by belvederechennai** [zmartzone/mod_auth_openidc#406]
###### Environment

- mod_auth_openidc version 2.3.8
- Apache version 2.4.34
- platform/distro Centos 7

###### Expected behaviour

The authorization claim check for scope should be performed in a access token
###### Actual behaviour

The authorization claim check for scope should be performed in a ID token.

###### Minimized example

Access authorization should be in a access token instead of ID token, does mod openidc allows to validate claims from access token?

**Comment by zandbelt** [comment]
the access token is meant to be presented to the user info endpoint or elsewhere, mod_auth_openidc is the Client and the `access_token` is opaque to the Client

**Comment by belvederechennai** [comment]
I understand the standard, but having not scope part of the ID token is also nice way to provide distinction between the tokens composition. There are many organization which don’t send scopes part of ID token, then leveraging mod_openidc along with scope as a way to authorize via require claim would result in bottleneck.
