### ISSUE TITLE
Cannot install latest version on RHEL7

### ISSUE THREAD

**Issue by devantoine** [zmartzone/mod_auth_openidc#407]
Hi,

I've followed multiples issues to try to install the latest RPM for RHEL7 without any luck.

So, when I run:

`sudo yum localinstall mod_auth_openidc-2.3.9-1.el7.x86_64.rpm`

I've got a dependency issue with cjose.

Following the instructions to install the release I've then downloaded https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.0/cjose-0.5.1-1.el7.centos.x86_64.rpm and run:

`sudo yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm`

But YUM says it requires jansson >= 2.3.

`yum info jansson` tells me the 2.10 package is already installed.

Following this issue: https://github.com/zmartzone/mod_auth_openidc/issues/354#issuecomment-385439379 I've removed jansson and re run `sudo yum localinstall cjose-0.5.1-1.el7.centos.x86_64.rpm` but I still have the same error regarding the jansson dependency. `yum localinstall` is not able to resolve it by itself.

What am I missing? How can I install this RPM on a RHEL7 system? The package in the officiel repo is the 1.8.8, way to old for our needs.

**Comment by zandbelt** [comment]
your package management is mixed up: do [1] and if that does not help do [2]

[1]
```
yum remove jansson
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-2.10-1.el7.x86_64.rpm
yum localinstall -y ~/jansson-2.10-1.el7.x86_64.rpm
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-devel-2.10-1.el7.x86_64.rpm
yum localinstall -y ~/jansson-devel-2.10-1.el7.x86_64.rpm
wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.0/cjose-0.5.1-1.el7.centos.x86_64.rpm
yum localinstall -y ~/cjose-0.5.1-1.el7.centos.x86_64.rpm
wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.9/mod_auth_openidc-2.3.9-1.el7.x86_64.rpm
yum localinstall -y ~/mod_auth_openidc-2.3.9-1.el7.x86_64.rpm
```
[2]
```
rpm -iv ~/cjose-0.5.1-1.el7.centos.x86_64.rpm --nodeps
rpm -iv ~/mod_auth_openidc-2.3.9-1.el7.x86_64.rpm --nodeps
```

**Comment by mmoossen** [comment]
The problem is that the error message is misleading. 
It reads:
`Requires: pkgconfig(jansson) >= 2.3`
but what is actually meant is that jansson-devel is missing...

**Comment by zandbelt** [comment]
> The problem is that the error message is misleading. It reads: `Requires: pkgconfig(jansson) >= 2.3` but what is actually meant is that jansson-devel is missing...

and that in its turn was a longstanding RPM packaging problem in the cjose libraries provided as part of the Releases of this project; that is fixed now
