### ISSUE TITLE
The authorization request exceeding the OIDCStateTimeout should be regarded as unsuccessful

### ISSUE THREAD

**Issue by hkgobreak** [zmartzone/mod_auth_openidc#409]
###### Environment

- mod_auth_openidc version 2.3.9
- Apache version 2.4.6
- platform/distro RHEL 7

###### Expected behaviour
The authorization request exceeding the OIDCStateTimeout should be regarded as unsuccessful, so no session cookie would be provided and the user should not be able to access the protected URL/resource after that without login again.

###### Actual behaviour
When the authorization request exceeds the OIDCStateTimeout, Error message is shown "message: Invalid Authentication Response description: This is due to a timeout;......"

If I reload the protected URL/resource in the same browser, the protected URL/resource can be accessed without being redirected to login page again.

As a workaround, I try to provide a OIDCHTMLErrorTemplate to provide a hyperlink to call the logout URL
```
<html>
<body>
there was an error<br>
message: %s<br>
description: %s<br><br>
<a id="myLink" href="/redirect_uri?logout=">Logout</a>
</body>
</html>
```

After I had clicked the Logout hyperlink, "Logged Out" text was shown. But when I reloaded the protected URL/resource in the same browser, the protected URL/resource could still be accessed without being redirected to login page again.

It is a problem since the users may not know the login is successful even there is a timeout error. Also the logout out URL ("/redirect_uri?logout=") is not working when calling from OIDCHTMLErrorTemplate.

If the users just close the tab (browser process remains) and walk away, other people could gain access to the protected resources.
###### Configuration and Apache server log files
The OIDCStateTimeout  is set to a short duration for the convenience of testing a timeout.

```
OIDCHTMLErrorTemplate /etc/httpd/conf.d/OIDCHTMLErrorTemplate.html
OIDCStateTimeout 5
```

**Comment by zandbelt** [comment]
I suspect the following is happening:

1. you're logging in and waiting more than 5 secs to authenticate
2. you authenticate successfully and create an SSO session on the OP
3. you return to mod_auth_openidc with an expired state and an error is presented
4. you hit the protected application again and get redirected to the OP
5. you still have a valid SSO session with the OP since you authenticated successfully shortly before
6. you get redirected to mod_auth_openidc within 5 seconds, a non-expired state and all is good

Perhaps you can confirm 4.-6.

Also: you should not include a logout URL in the error template, that serves no purpose.

**Comment by hkgobreak** [comment]
Yes, It is such a simple scenario. I agree 1-6 is happening. But it is not a good result in view of application security. I think the use case would be better either the login is revoked after a timeout error or the request is redirect to a pre-configured URL as a proper successful login when state cookie is not present. Now seems this is no workaround for the abandoned successful session when timeout happened.

**Comment by zandbelt** [comment]
You seem to suggest that the login on the OP needs to be revoked but that is independent of a specific application timeout. Also, it would require single-logout features which can only security-wise work if the user is successfully logged in and both parties support it. I believe you perceive a security problem where there isn't.

**Comment by hkgobreak** [comment]
Thank you for your prompt reply. 

I think the error handling of OIDCStateTimout may trigger more issues in some similar simple login scenario. Actually it is not rare that users hold on at the login page for 5 minutes just like click for a login page, go get a coffee and finally input the credentials some minutes later.

As the login is actually successful, I also suggested if it is possible to redirect the request to a preconfigured URL for your consideration

**Comment by zandbelt** [comment]
if you think that is common for your use case, then please increase `OIDCStateTimout`.

There is no way to logout with the Provider and kill the SSO session there no matter to which URL you'd redirect. But as you wish you can set `OIDCDefaultURL`, see: https://github.com/zmartzone/mod_auth_openidc/blob/master/auth_openidc.conf#L603

**Comment by hkgobreak** [comment]
I had set the OIDCDefaultURL, but it seems the URL is just shown as a part of error message only but not for redirection when state cookie is expired.

———————————————-////
	/* check that the timestamp is not beyond the valid interval */
	if (apr_time_now() > ts + apr_time_from_sec(c->state_timeout)) {
		oidc_error(r, "state has expired");
		oidc_util_html_send_error(r, c->error_template,
				"Invalid Authentication Response",
				apr_psprintf(r->pool,
						"This is due to a timeout; please restart your authentication session by re-entering the URL/bookmark you originally wanted to access: %s",
						oidc_proto_state_get_original_url(*proto_state)),
						DONE);
		oidc_proto_state_destroy(*proto_state);
		return FALSE;
	}

**Comment by hkgobreak** [comment]
Thank you for the suggestion. I would like to share the workaround here for my case mentioned.

As I saw the header OIDC_HTTP_HDR_LOCATION is set
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L2038-L2047

which is after generating the error html "oidc_util_html_send_error" to the browser, 
https://github.com/zmartzone/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L838-L848

I amended the OIDCHTMLErrorTemplate to do reloading when hitting the state timeout.
By reloading, it brings me to the OIDCDefaultURL
```
<script>
var err="%s";
var desc="%s";

function reload() {
        document.getElementById("err").innerHTML=err;
        document.getElementById("desc").innerHTML=desc;

        if (err=="Invalid Authentication Response") {
                location.reload();
        }
}
</script>
<body onload="reload()">
.......
```
