### ISSUE TITLE
Relative path not working for OIDCRedirectURI

### ISSUE THREAD

**Issue by pieterlukasse** [zmartzone/mod_auth_openidc#413]
The documentation at https://github.com/zmartzone/mod_auth_openidc/blob/master/auth_openidc.conf#L11 states the following about `OIDCRedirectURI`:
>  You can use a relative URL like /protected/redirect_uri if you want to

However, I get the following error when doing this:
```
AH00526: Syntax error on line 571 of /usr/local/apache2/conf/httpd.conf:
'/oid/redirect_uri' cannot be parsed as a URL (no scheme set)
```

###### Environment

- use the openid library installed via `apt-get` (i.e. `apt-get install -y --no-install-recommends libapache2-mod-auth-openidc`)

###### Expected behaviour

I expect to be able to use relative URLs, like documented.

###### Actual behaviour

See error above.

###### Configuration and Apache server log files

Use this in apache conf file:
```
  OIDCRedirectURI /oid/redirect_uri
```

**Comment by zandbelt** [comment]
which version of the module are you using?

**Comment by pieterlukasse** [comment]
I am guessing it should be this one https://packages.debian.org/stretch/libapache2-mod-auth-openidc, since my docker image starts with `FROM httpd:2.4` which is based on `FROM debian:stretch-slim`.

**Comment by zandbelt** [comment]
I guess you meant to comment here:
https://github.com/zmartzone/mod_auth_openidc/issues/268#issuecomment-447881023
you're using version 2.1.6 and support for relative URLs was only introduced in

**Comment by zandbelt** [comment]
you're on 2.1.6 then and support for relative URLs was only introduced in 2.3.0:
https://github.com/zmartzone/mod_auth_openidc/releases/tag/v2.3.0
I guess you want to use the latest from: https://github.com/zmartzone/mod_auth_openidc/releases
