### ISSUE TITLE
hiredis no longer in epel-6

### ISSUE THREAD

**Issue by davidsmith1307** [zmartzone/mod_auth_openidc#414]
- mod_auth_openidc 2.3.9, 2.3.10
- Apache 2.2.15
- RHEL 6

mod_auth_openidc RHEL 6 RPM depends on hiredis. This used to be available in the epel-6 repo but isn't any longer meaning that installation is not possible without retrieving an old copy from an archive of unknown provenance.

**Comment by zandbelt** [comment]
Please get it from http://springdale.math.ias.edu/data/puias/unsupported/6/x86_64/hiredis-0.12.1-1.sdl6.x86_64.rpm
