### ISSUE TITLE
Upgrading from mod_auth_openidc_1.8.3 to latest version

### ISSUE THREAD

**Issue by ashishjayaswal** [zmartzone/mod_auth_openidc#415]
Hi,
We have mod_auth_openidc version 1.8.3 currently setup and configured. In that version, we are seeing issues mentioned in https://github.com/zmartzone/mod_auth_openidc/issues/321.

As this is resolved with latest version, we wanted to upgrade but unable to find steps related to upgrading the mod_auth_openidc with all current configuration. Only below link for installation though we have everything configured.
https://gluu.org/docs/ce/2.4.4/integration/openidc-rp/

Please help us with the documentation for upgrading with the existing config settings.
Thanks!

**Comment by zandbelt** [comment]
please read the text you deleted when opening this ticket

**Comment by ashishjayaswal** [comment]
sorry didn't get. I have not deleted anything.

**Comment by ashishjayaswal** [comment]
ah, my bad! Got it!
