### ISSUE TITLE
Documentation of "mandatory" attributes does not seem accurate

### ISSUE THREAD

**Issue by pieterlukasse** [zmartzone/mod_auth_openidc#416]
###### Environment

- mod_auth_openidc version (2.3.10 - taken from https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.10/libapache2-mod-auth-openidc_2.3.10-1.stretch+1_amd64.deb)
- Apache version (2.4)
- platform/distro (debian stretch)

###### Description

Documentation at https://github.com/zmartzone/mod_auth_openidc/blob/master/auth_openidc.conf#L7 mentions two "Mandatory" attributes: `OIDCRedirectURI` and `OIDCCryptoPassphrase`, but I got a working OAuth configuration without these. Now I am wondering whether it is a bug or just a documentation mistake. See sections below (also for some extra related questions).

###### Minimized example

This is the configuration at `httpd.conf`:

```
<VirtualHost *:8443>
  # reverse proxy settings:
   ....

  # mod_auth_openidc settings:
  OIDCOAuthVerifyJwksUri https://mykeycloak.com/auth/realms/${KC_REALM}/protocol/openid-connect/certs
  OIDCIDTokenIatSlack 120
  
  # Specific for /api endpoints:
  <Location /api >
    AuthType oauth20
    Require claim azp:${CLIENT_ID}
  </Location>

</VirtualHost>
```

The goal is to let command line clients request a token from Keycloak and then call the /api endpoints using the token with something like
```
curl -k -L 'https://myappserver:8443/api/v3/platform/public/association/filter?target=ENSG00000139618' \
-H 'Authorization: Bearer eyJhbGci...'
```

###### Extra questions

This also brings me to a related question: the [documentation](https://github.com/zmartzone/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server) seems to imply that I have to use OAuth for such a scenario. Is this correct? Or can I also use `AuthType openid-connect`? If openid is also possible for this /api scenario, where can I find an example in the documentation?

**Comment by zandbelt** [comment]
About your first question: technically it is not mandatory but it is hard to document two separate (OIDC and OAuth 2.0) in a single conf file. So`OIDCRedirectURI` is also used in an OAuth 2.0 setup where tokens are asymmetrically encrypted and `OIDCCryptoPassphrase` is used to encrypt other-than-shared-memory cached token values in the OAuth 2.0 case. So it seemed about right on the average across the two configs where OIDC is usually the one in play....

About your first question:  yes, OAuth 2.0 is the correct scenario.

**Comment by pieterlukasse** [comment]
Thanks for the quick reply @zandbelt :+1:  Just a doubt I had based on your reply: does this mean the configuration/setup I am proposing here is rather unusual? Or is my scenario perhaps not so common? I am new to OpenID and OAuth, so if there is a more common configuration, please let me know.

**Comment by zandbelt** [comment]
no, it is fine and common for OAuth 2.0 setups
