### ISSUE TITLE
OAuth not working as documented?

### ISSUE THREAD

**Issue by pieterlukasse** [zmartzone/mod_auth_openidc#418]
###### Environment

- mod_auth_openidc version (e.g. 2.3.10)
- Apache version (e.g. 2.4)
- platform/distro (debian stretch)

###### Description

Documentation at https://github.com/zmartzone/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server states that:
> The Resource Server behavior is triggered for a particular path by protecting it with:
```
<Location /api>
  AuthType oauth20
</Location>
```

However, if I follow this, the result is that no token is required at all and I can just call my api. Only when adding an extra line with `Require ...` will it start expecting a token:

```
  <Location /api >
    AuthType oauth20
    Require claim azp:${CLIENT_ID}
  </Location>
```

###### Minimized example

This is the configuration at `httpd.conf`:

```
<VirtualHost *:8443>
  # reverse proxy settings:
   ....

  # mod_auth_openidc settings:
  OIDCOAuthVerifyJwksUri https://mykeycloak.com/auth/realms/${KC_REALM}/protocol/openid-connect/certs
  OIDCIDTokenIatSlack 120
  
  # Specific for /api endpoints:
  <Location /api >
    AuthType oauth20
    Require claim azp:${CLIENT_ID}
  </Location>

</VirtualHost>
```

**Comment by zandbelt** [comment]
yeah, that's sort of standard Apache speak but the docs could be more clear about it so I've added text to your suggestion:
https://github.com/zmartzone/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server/_compare/013d168771759cd6ed315045d5b085af942d279d...15779f48ac91435885791c4b23aa333f03e6973d
thanks (also: feel free to edit the Wiki yourself if you have more improvements)

**Comment by pieterlukasse** [comment]
@zandbelt thanks for the clarification :+1:
