### ISSUE TITLE
double request parameters

### ISSUE THREAD

**Issue by jreynaert** [zmartzone/mod_auth_openidc#420]
###### Environment
- mod_auth_openidc version  2.3.10
- Apache/2.4.6 (CentOS)
- CentOS 7 (on mesos/marathon)

###### Expected behaviour
redirect after authentication exact URL + querystring (as before the login)
###### Actual behaviour
return URL + querystring + querystring
###### Minimized example
Start: https://host.com:8443/somedir/file?param1=a
Authentication - callback etc....
End (or return): https://host.com:8443/somedir/file?param1=a?param=a

###### Solution
Revert to version 2.3.9

**Comment by zandbelt** [comment]
a big oops fixed in 2.3.10.1, thank you
