### ISSUE TITLE
shm cache code does not properly handle alignment

### ISSUE THREAD

**Issue by gco** [zmartzone/mod_auth_openidc#422]
The use of `OIDC_CACHE_SHM_ADD_OFFSET` results in every structure in the cache after the first not being properly aligned and causing:

- performance degradation on some architectures that allow unaligned loads and stores but implement them with lower performance than properly aligned loads and stores

- and, worse, SEGV on architectures that _require_ aligned loads and stores (RISC)

**Comment by gco** [comment]
The rules are different from architecture to architecture, but here's what the Intel rules are:
https://software.intel.com/en-us/articles/coding-for-performance-data-alignment-and-structures

I modified that macro to round up the incoming size argument to a multiple of 16 to be overly cautious.

**Comment by zandbelt** [comment]
@gco just bumping my (2) questions above to you.

**Comment by zandbelt** [comment]
without further comments/insights I'll close this issue as invalid shortly
