### ISSUE TITLE
Nextcloud configuration

### ISSUE THREAD

**Issue by loxK** [zmartzone/mod_auth_openidc#426]
Apache 2.4.29
mod-auth-openidc 2.3.3

I am trying to figure out the proper way to authenticate against nextcloud. Here is my configuration so far:
```

        OIDCClientID [redacted]

        OIDCClientSecret [redacted]

        OIDCProviderIssuer [redacted]

        OIDCProviderAuthorizationEndpoint https://[redacted]/apps/oauth2/authorize

        OIDCProviderTokenEndpoint https://[redacted]/apps/oauth2/api/v1/token

        OIDCScope "openid"

        OIDCRedirectURI https://[redacted]/redirect_uri

        OIDCCryptoPassphrase [redacted]

        OIDCProviderUserInfoEndpoint https://[redacted]/ocs/v2.php/cloud/user?format=json
```

When I connect I am redirected to the nextcloud's auth screens then, after being redirected to the redirect_uri, I get an error:

```
[Tue Feb 05 16:09:12.320240 2019] [auth_openidc:error] [pid 9367] [client 10.22.237.1:34806] oidc_proto_validate_code_response: requested flow is "code" but no "id_token" parameter found in the code response
[Tue Feb 05 16:09:12.320363 2019] [auth_openidc:error] [pid 9367] [client 10.22.237.1:34806] oidc_proto_resolve_code_and_validate_response: code response validation failed
```

**Comment by loxK** [comment]
Wow ok ... I guess that means that I shouldn't have ask for help

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid

The very title of this issue itself suggests it is better asked elsewhere.

**Comment by loxK** [comment]
I'll just give up on that module then.

**Comment by zandbelt** [comment]
LOL, you haven not even read the last bullet in that link :-)))
