### ISSUE TITLE
Why port 8080 is being set by oidc_util_hdr_table_set ?

### ISSUE THREAD

**Issue by roopannava** [zmartzone/mod_auth_openidc#427]
###### Environment

- platform/distro (Sles12)
- mod_auth_openidc version : apache2-mod_auth_openidc           | package    | 2.3.3-1.2 
- Apache version    2.4.23-29.13.1 

###### Expected behaviour
https://portal-test.mydomain.no/minside

###### Actual behaviour
The port 8080 is being added. Why ?
https://portal-test.mydomain.no:8080/minside

###### Minimized example
Log : 

[Thu Feb 14 10:37:17.534802 2019] [auth_openidc:debug] [pid 49592] src/mod_auth_openidc.c(1673): [client 127.0.0.1:36086] oidc_save_in_session: session management disabled: "check_session_iframe" is not set in provider configuration
[Thu Feb 14 10:37:17.534805 2019] [auth_openidc:debug] [pid 49592] src/mod_auth_openidc.c(1042): [client 127.0.0.1:36086] oidc_store_userinfo_claims: enter
[Thu Feb 14 10:37:17.534821 2019] [auth_openidc:debug] [pid 49592] src/mod_auth_openidc.c(1713): [client 127.0.0.1:36086] oidc_save_in_session: provider->session_max_duration = 28800, session_expires=1550165837534819
[Thu Feb 14 10:37:17.534825 2019] [auth_openidc:debug] [pid 49592] src/mod_auth_openidc.c(900): [client 127.0.0.1:36086] oidc_log_session_expires: session max lifetime: Thu, 14 Feb 2019 17:37:17 GMT (in 28799 secs from now)
[Thu Feb 14 10:37:17.534829 2019] [auth_openidc:debug] [pid 49592] src/util.c(2192): [client 127.0.0.1:36086] oidc_util_hdr_in_get: Host=portal-test.mydomain.no
[Thu Feb 14 10:37:17.534934 2019] [auth_openidc:debug] [pid 49592] src/cache/common.c(626): [client 127.0.0.1:36086] oidc_cache_set: enter: xxx-xxxx-xxx-xx-xx (section=s, len=3118, encrypt=0, ttl(s)=299, type=shm)
[Thu Feb 14 10:37:17.534985 2019] [auth_openidc:debug] [pid 49592] src/cache/common.c(653): [client 127.0.0.1:36086] oidc_cache_set: successfully stored 3118 bytes in shm cache backend for key xxx-xxxx-xxx-xx-xx
[Thu Feb 14 10:37:17.534993 2019] [auth_openidc:debug] [pid 49592] src/util.c(2246): [client 127.0.0.1:36086] oidc_util_hdr_err_out_add: Set-Cookie: mod_auth_openidc_session=xxx-xxxx-xxx-xx-xx; Path=/; Secure; HttpOnly
[Thu Feb 14 10:37:17.535006 2019] [auth_openidc:debug] [pid 49592] src/mod_auth_openidc.c(1945): [client 127.0.0.1:36086] oidc_handle_authorization_response: session created and stored, returning to original URL: https://portal-test.mydomain.no:8080/minside, original method: get
[Thu Feb 14 10:37:17.535009 2019] [auth_openidc:debug] [pid 49592] src/util.c(2224): [client 127.0.0.1:36086] oidc_util_hdr_table_set: Location: https://portal-test.mydomain.no:8080/minside

###### Configuration and Apache server log files
Varnish is running on port 80
Apache is running on port 8080

Apache :
.conf file :

   <VirtualHost *:8080>
    ServerName https://portal-test.mydomain.no

    
    OIDCClientID xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    OIDCClientSecret xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    OIDCRedirectURI https://portal-test.mydomain.no/minside/redirect_uri
    OIDCResponseType code
    OIDCScope "openid profile"
    OIDCSSLValidateServer Off
    OIDCCryptoPassphrase (a-random-seed-value)
    OIDCPassClaimsAs environment
    OIDCClaimPrefix USERINFO_
    OIDCPassIDTokenAs payload
    OIDCSSLValidateServer Off

    <Location ~ /minside>
        Require valid-user 
        AuthType openid-connect
        LogLevel debug 
    </Location>

</VirtualHost>

**Comment by zandbelt** [comment]
Apparently your instance is behind a proxy and the external port differs from the internal port. In that case your frontend proxy needs to pass `X-Forwarded-Host` and/or `X-Forwarded-Port` as documented in: https://github.com/zmartzone/mod_auth_openidc/wiki#8-how-do-i-run-mod_auth_openidc-behind-a-reverse-proxy

**Comment by zandbelt** [comment]
as suggested in the issue template: this type of questions should be discussed on the e-mail list
