### ISSUE TITLE
Require claim doesn't work

### ISSUE THREAD

**Issue by lukasmatta** [zmartzone/mod_auth_openidc#428]
Hello,

I am trying to use mod_auth_openidc as a resource server and validate access token passed by client. 

When I use following configuration, everything works as expected.
```
<Location /oidc-api>
  AuthType oauth20
  Require valid-user
  LogLevel debug
</Location>
```
However, when I try to require claim instead of valid-user, it doesn't work.
```
<Location /oidc-api>
  AuthType oauth20
  Require claim groupNames:group1
  LogLevel debug
</Location>
```

I found out that if I log in using ```Require valid-user``` configuration and then change it to ```Require claim groupNames:group1``` while staying logged in, it works.

###### Environment

- mod_auth_openidc version (e.g. 2.3.9)
- Apache version (e.g. 2.4.25)
- platform/distro (e.g. Debian)

###### Expected behaviour
Authorize user using ```Require claim groupNames:group1``` when he tries to log in.

###### Actual behaviour
Unable to authorize user using ```Require claim groupNames:group1``` when he tries to log in. However, I can do it, when the user has already logged in using ```Require valid-user```.

###### Configuration and Apache server log files
```[Mon Feb 18 14:55:30.896907 2019] [auth_openidc:debug] [pid 2972:tid 140238072547072] src/mod_auth_openidc.c(3540): [client 10.0.2.2:64186] oidc_authz_checker: enter, referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896911 2019] [auth_openidc:debug] [pid 2973:tid 140238212945664] src/oauth.c(293): [client 10.0.2.2:64185] oidc_oauth_get_bearer_token: no bearer token found in the allowed methods: ['header'], referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896919 2019] [authz_core:debug] [pid 2972:tid 140238072547072] mod_authz_core.c(809): [client 10.0.2.2:64186] AH01626: authorization result of Require claim groupNames:group1: denied (no authenticated user yet), referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896926 2019] [auth_openidc:debug] [pid 2973:tid 140238212945664] src/mod_auth_openidc.c(3540): [client 10.0.2.2:64185] oidc_authz_checker: enter, referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896931 2019] [authz_core:debug] [pid 2972:tid 140238072547072] mod_authz_core.c(809): [client 10.0.2.2:64186] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896939 2019] [authz_core:debug] [pid 2973:tid 140238212945664] mod_authz_core.c(809): [client 10.0.2.2:64185] AH01626: authorization result of Require claim groupNames:group1: denied (no authenticated user yet), referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896943 2019] [authz_core:error] [pid 2972:tid 140238072547072] [client 10.0.2.2:64186] AH01629: authorization failure (no authenticated user): /oidc-api/oidc-protected/panel_groups/, referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896952 2019] [authz_core:debug] [pid 2973:tid 140238212945664] mod_authz_core.c(809): [client 10.0.2.2:64185] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://localhost:4200/index.html
[Mon Feb 18 14:55:30.896963 2019] [authz_core:error] [pid 2973:tid 140238212945664] [client 10.0.2.2:64185] AH01629: authorization failure (no authenticated user): /oidc-api/oidc-protected/panels/, referer: http://localhost:4200/index.html```

**Comment by zandbelt** [comment]
it seems you're using some sort of SPA and conflating user logon with OpenID Connect with accessing OAuth 2.0 protected paths with an access token

**Comment by lukasmatta** [comment]
I am trying to validate access token received by SPA client. Validation by```Require valid-user``` works properly, however it doesn't work when using ```Require claim groupNames:group1```. I've tested sending access token manually to the introspection endpoint, I got JSON response which contains the requesting group - everything looks fine. Where could be a problem?

**Comment by zandbelt** [comment]
this may set you on the right path: https://github.com/zmartzone/mod_auth_openidc/wiki/Single-Page-Applications#allowing-both-oauth-20-and-openid-connect

**Comment by lukasmatta** [comment]
My SPA is sending the access token in the header. Validation works when disabling CORS in the web browser - it seems like when using ```Require claim``` and ```Require valid-user``` CORS is behaving differently.

**Comment by zandbelt** [comment]
you may want to use `AuthType auth-openidc`

**Comment by lukasmatta** [comment]
I was exploring response headers sent by the server as a reply to preflight requests. I realized that when using ```Require claim groupNames:group1``` configuration, response of the server is 401. However, when configuration is ```Require valid-user``` the server responds properly allowing CORS.

I fixed the problem by adding ```OIDCUnAuthAction pass``` to config.

**Comment by zandbelt** [comment]
for future reference: this type of discussion should happen on the mailing list as suggested in the issue template
