### ISSUE TITLE
REMOTE_USER not set?

### ISSUE THREAD

**Issue by pieterlukasse** [zmartzone/mod_auth_openidc#429]
###### Environment

- mod_auth_openidc version: 2.3.10.2 https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.10.2/libapache2-mod-auth-openidc_2.3.10.2-1.stretch+1_amd64.deb
- Apache version: 2.4
- platform/distro: apache in Docker (`FROM httpd:2.4`) 

###### Expected behaviour

Documentation at https://github.com/zmartzone/mod_auth_openidc#overview states that
> By default the module sets the REMOTE_USER variable...

###### Actual behaviour

Apparently `REMOTE_USER` is not set. 

###### Minimized example

Set this in the Apache conf:
```
  Header set MyHeader ${REMOTE_USER}
```
The response in the browser shows up like this:

![image](https://user-images.githubusercontent.com/2900303/53482636-f8be7600-3a7f-11e9-8f15-16fa03285a2b.png)

**Comment by zandbelt** [comment]
look here http://httpd.apache.org/docs/current/mod/mod_headers.html for docs on mod_headers; `${REMOTE_USER}` is incorrect syntax for it

**Comment by pieterlukasse** [comment]
Thanks @zandbelt ! I had also tried with 
```
  Header set MyHeader %{REMOTE_USER}e
```
but that was also not working. It turned out I had to use
```
  Header set MyHeader %{REMOTE_USER}s
```
because mod_ssl was enabled in my case. Problem solved! Thanks for your help :+1:
