### ISSUE TITLE
passing id_token as cookie

### ISSUE THREAD

**Issue by Franz8wask** [zmartzone/mod_auth_openidc#430]
###### Environment

- mod_auth_openidc-1.8.8-3.el7.x86_64
- httpd-2.4.6-88.el7.centos.x86_64
- CentOS Linux release 7.6.1810 (Core)

###### Expected behaviour
Hi,
we like to configure Apache with mod_auth_openidc to provide to make login over SSO and redircet tu application passing ID_token as a cookie

###### Actual behaviour
actually we find id_token inside the header url
http://portal.apps.domain.priv/home#state=xxxxxxxxxxxxxxxxxxxxxxxxxxx&session_state=yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy&id_tokenid_token=<JWT>&not-before-policy=1550512415

###### Minimized example
*Minimal, complete configuration that reproduces the behavior. Use the mailing list or get commercial support to discuss your own (full) setup.*

<VirtualHost *:80>

    ServerName fe.localdomain
    ServerAlias www.yourserver.net
    DocumentRoot /var/www/html/
    DirectoryIndex yourpage.html
    DirectoryIndex yourpage.html
    LogLevel debug
    ErrorLog /var/log/oidc/error.log
    CustomLog /var/log/oidc/access.log combined

    OIDCProviderMetadataURL  https://sso.apps.domain.priv/auth/realms/XXXXXXXX/.well-known/openid-configuration
    OIDCClientID wwwwwwwwwwwwwwwwwww
    OIDCClientSecret zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    OIDCRedirectURI http://portal.apps.domain.priv
    OIDCResponseType id_token
    OIDCPassIDTokenAs payload
    OIDCAuthNHeader nome
    OIDCCryptoPassphrase password
    OIDCJWKSRefreshInterval 3600

    OIDCSSLValidateServer Off
    OIDCOAuthSSLValidateServer Off
    OIDCOAuthAcceptTokenAs cookie
    OIDCCookieDomain apps..domain.priv

    OIDCScrubRequestHeaders Off

    <Location />
       AuthType openid-connect
       Require valid-user
    </Location>
</VirtualHost>

###### Configuration and Apache server log files
*Config and logs for the minimized example, possibly provided as attachments.*

LOG:
[Tue Mar 05 11:05:51.557418 2019] [authz_core:debug] [pid 24410] mod_authz_core.c(809): [client xxx.xxx.xxx.xxx:7711] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Tue Mar 05 11:05:51.557671 2019] [authz_core:debug] [pid 24410] mod_authz_core.c(809): [client xxx.xxx.xxx.xxx:7711] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Tue Mar 05 11:05:51.557809 2019] [auth_openidc:debug] [pid 24410] src/mod_auth_openidc.c(2585): [client xxx.xxx.xxx.xxx:7711] oidc_check_user_id: incoming request: "/?(null)", ap_is_initial_req(r)=1
[Tue Mar 05 11:05:51.558371 2019] [auth_openidc:debug] [pid 24410] src/util.c(772): [client xxx.xxx.xxx.xxx:7711] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Tue Mar 05 11:05:51.558428 2019] [auth_openidc:debug] [pid 24410] src/session.c(83): [client xxx.xxx.xxx.xxx:7711] oidc_session_load: <null>
[Tue Mar 05 11:05:51.558468 2019] [auth_openidc:debug] [pid 24410] src/util.c(811): [client xxx.xxx.xxx.xxx:7711] oidc_util_request_matches_url: comparing "/"=="(null)"
[Tue Mar 05 11:05:51.558506 2019] [auth_openidc:debug] [pid 24410] src/util.c(374): [client xxx.xxx.xxx.xxx:7711] oidc_get_current_url: current URL 'http://fe.localdomain/'
[Tue Mar 05 11:05:51.558533 2019] [auth_openidc:debug] [pid 24410] src/mod_auth_openidc.c(1715): [client xxx.xxx.xxx.xxx:7711] oidc_authenticate_user: enter
[Tue Mar 05 11:05:51.558572 2019] [auth_openidc:debug] [pid 24410] src/cache/shm.c(156): [client xxx.xxx.xxx.xxx:7711] oidc_cache_shm_get: enter, section="provider", key="https://sso.apps.domain.priv/auth/realms/XXXXXXXX/.well-known/openid-configuration"
[Tue Mar 05 11:05:51.562490 2019] [auth_openidc:debug] [pid 24410] src/util.c(440): [client xxx.xxx.xxx.xxx:7711] oidc_util_http_call: url=https://sso.apps.domain.priv/auth/realms/XXXXXXXX/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=0
[Tue Mar 05 11:05:51.790003 2019] [auth_openidc:debug] [pid 24410] src/util.c(564): [client xxx.xxx.xxx.xxx:7711] oidc_util_http_call: response={"issuer":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX","authorization_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/auth","token_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/token","token_introspection_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/userinfo","end_session_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/logout","jwks_uri":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/certs","check_session_iframe":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["RS256"],"userinfo_signing_alg_values_supported":["RS256"],"request_object_signing_alg_values_supported":["none","RS256"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://sso.apps.domain.priv/auth/realms/XXXXXXXX/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post"],"token_endpoint_auth_signing_alg_values_supported":["RS256"],"claims_supported":["sub","iss","auth_time","name","given_name","family_name","preferred_username","email"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"scopes_supported":["openid","offline_access"],"request_parameter_supported":true,"request_uri_parameter_supported":true}
[Tue Mar 05 11:05:51.790462 2019] [auth_openidc:debug] [pid 24410] src/cache/shm.c(213): [client xxx.xxx.xxx.xxx:7711] oidc_cache_shm_set: enter, section="provider", key="https://sso.apps.domain.priv/auth/realms/XXXXXXXX/.well-known/openid-configuration", value size=%lu
[Tue Mar 05 11:05:51.790563 2019] [auth_openidc:debug] [pid 24410] src/mod_auth_openidc.c(143): [client xxx.xxx.xxx.xxx:7711] oidc_get_browser_state_hash: enter
[Tue Mar 05 11:05:51.790754 2019] [auth_openidc:debug] [pid 24410] src/util.c(732): [client xxx.xxx.xxx.xxx:7711] oidc_util_set_cookie: adding outgoing header: Set-Cookie: mod_auth_openidc_state_1BamLHwDIDv0pc4BHru_CDCdB9A=XljmW7T-npVH60XrfYRRyh_OoiINkrFDTmfLtguXoFsfZyq-R5D7cHn4CNkXuLK2MgGuFF0v443kIHyMS_lSA9mhfWJ6oyiRa__V4o9-id3ac6H8Y_C_ncKV64df-yQKQcslBJnmzMsGRZbNP56dhFnKoPlDT8qztrhZVDuVRV5WEM8-kwg5XCdgQSFulm_pfz0RU7yx_m7VUVLZA48a2wOhdUlkVxM0pzUo04CRAnXizXvJThbOtV_YYYYY_XXXXX_zeO6kOXzvJdufNuWYmCgSzb9J79P3Eo8kjxDC33k5F8nt9kw_ZcXPcDPELynaeg2hjZZVR06eH8oI3GFBxfS_ZZZZZ-wn1PNvD5LtOtc;Path=/;Domain=apps.domain.priv;HttpOnly
[Tue Mar 05 11:05:51.790858 2019] [auth_openidc:debug] [pid 24410] src/proto.c(113): [client xxx.xxx.xxx.xxx:7711] oidc_proto_authorization_request: enter, issuer=https://sso.apps.domain.priv/auth/realms/XXXXXXXX, redirect_uri=http://portal.apps.domain.priv, state=1BamLHwDIDv0pc4BHru_CDCdB9A, proto_state={"original_url": "http://fe.localdomain/", "original_method": "get", "issuer": "https://sso.apps.domain.priv/auth/realms/XXXXXXXX", "response_type": "id_token", "nonce": "Ik3c4Fc5A0lzTJN7SGUnAhp3E-I1L-6rCXZsiTf4Cgw", "timestamp": 1551780351}, code_challenge=(null)
[Tue Mar 05 11:05:51.790942 2019] [auth_openidc:debug] [pid 24410] src/proto.c(220): [client xxx.xxx.xxx.xxx:7711] oidc_proto_authorization_request: adding outgoing header: Location: https://sso.apps.domain.priv/auth/realms/XXXXXXXX/protocol/openid-connect/auth?response_type=id_token&scope=openid&client_id=wwwwwwwwwwwwwwwwwww&state=1BamLHwDIDv0pc4BHru_CDCdB9A&redirect_uri=http%3A%2F%2Fportal.apps.domain.priv&nonce=Ik3c4Fc5A0lzTJN7SGUnAhp3E-I1L-6rCXZsiTf4Cgw

regards

**Comment by zandbelt** [comment]
when brought up on the mailing list as suggested in the issue template you may have been pointed to the existing documentation on this feature
