### ISSUE TITLE
Support for keycloak 'multivalued' claims

### ISSUE THREAD

**Issue by CRCinAU** [zmartzone/mod_auth_openidc#433]
###### Environment
- mod_auth_openidc version: 2.3.11
- Apache version: httpd-2.4.6-67
- platform/distro Centos 7

###### Expected behaviour
Allow access if claim is in the returned list.

###### Actual behaviour
Access is denied.

###### Minimized example
Using the following apache config:
Require claim docname:project1

If the claim comes back as:
'OIDC_CLAIM_docname' => 'project1,project2'

Auth will fail.

Multivalued mappings in Keycloak will return lists as comma separated fields. The equiv within keycloak is to list the user attribute as project1##project2 etc.

There does not seem to be a way to filter based on a value in the list.

**Comment by CRCinAU** [comment]
Managed to figure this out....

Using: Require claim "docname~project1"

As long as this can't match anything else, like aproject1, then I guess this does what I need.

**Comment by zandbelt** [comment]
Please post questions like this to the mailing list before opening an issue: https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
