### ISSUE TITLE
using mod_auth_openidc from curl to return access token

### ISSUE THREAD

**Issue by orivat** [zmartzone/mod_auth_openidc#434]
Hi,

I have a platform with:
ubuntu 18.04
apache configured mod_auth_openidc
Keycloak

I have set the feature OIDCInfoHook userinfo in auth_openidc.conf file
I have been able to authenticate successfully from the browser, using teh above platform and to retrive successfully userinfo information using hook redirect?info=json

Now, I would like to perform to authenticate from the command line, providing username password on the command line with something like this

curl -X POST \
-d "client_id=app1" \
-d "client_secret=22e0bf75-f769-4fdf-8bae-7e8384aaae44" \
-d "username=user1" -d "password=password" -d "grant_type=password" \
http://example.com/demo1

I am able to authenticate, but I am not able to use the info hook to retrieve userinfo.

My question:
is there a way with auth_openidc module to be able to log from command line and retrieve userinfo (i.e teh same as what as been done through the browser).

Regards, 
Olivier Rivat
olivier.rivat@gmail.com

**Comment by orivat** [comment]
Hi,
How is it possible to do this ? (if it is possible ) ?

Regards,
Olivier

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
