### ISSUE TITLE
Enforcing algorithm values

### ISSUE THREAD

**Issue by jalauros** [zmartzone/mod_auth_openidc#435]
###### Environment
 Any

###### Expected behaviour

When using primitives like OIDCUserInfoSignedResponseAlg  the RP should verify that the received response has actually been signed with the listed algorithm(s).

###### Actual behaviour

If one sets for instance value RS256 for the OIDCUserInfoSignedResponseAlg the RP is able to handle the incoming signed response and validate it but it does not verify the algorithm is actually RS256.

**Comment by zandbelt** [comment]
It turns out that this is actually a spec requirement, as follows out of this discussion: https://github.com/openid-certification/oidctest/issues/207 so I'm reclassifying as a bug that needs to be addressed for the next release.

**Comment by zandbelt** [comment]
@jalauros can you try with https://mod-auth-openidc.org/download/mod_auth_openidc-2.4.1rc2-1.el7.x86_64.rpm ?

**Comment by zandbelt** [comment]
now released in 2.4.1
