### ISSUE TITLE
State parameter not being sent

### ISSUE THREAD

**Issue by TMMJonS** [zmartzone/mod_auth_openidc#436]
###### Environment

- mod_auth_openidc version 2.3.11
- Apache/2.4.37
- Centos 7

###### Expected behaviour
The state parameter being sent
###### Actual behaviour
The state parameter not being sent

###### Configuration and Apache server log files
        OIDCSSLValidateServer Off
        OIDCProviderMetadataURL https://Authdomain/.well-known/member-openid-configuration
        OIDCClientID <clientid>
        OIDCClientSecret <secret>
        OIDCScope openid
        OIDCCryptoPassphrase cryptoPass
        OIDCUserInfoSignedResponseAlg RS256
        OIDCRemoteUserClaim username
        OIDCUserInfoRefreshInterval 0
        OIDCTokenBindingPolicy disabled
        OIDCSessionInactivityTimeout 30
        OIDCSessionMaxDuration 0
        OIDCRedirectURI https://endpoint/vanity.php
        OIDCRemoteUserClaim sub
[Thu Mar 14 15:57:52.785067 2019] [auth_openidc:error] [pid 83564:tid 140036393580288] [client xxxxxxxxxx] oidc_authenticate_user: the URL scheme (https) of the configured OIDCRedirectURI does not match the URL scheme of the URL being accessed (http): the "state" and "session" cookies will not be shared between the two!

**Comment by zandbelt** [comment]
that is because "the URL scheme (https) of the configured OIDCRedirectURI does not match the URL scheme of the URL being accessed (http)"...

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
