### ISSUE TITLE
Invalid Request access the sso path (OIDCRedirectURI)

### ISSUE THREAD

**Issue by marcelodcp** [zmartzone/mod_auth_openidc#437]
###### Environment

- mod_auth_openidc - version 2.3.10.1
- Apache version - Apache/2.4.6
- platform/distro - CentOS

###### Expected behaviour
Error in the first access or logged user

If the user access the sso url, the same that I configure in the OIDCRedirectURI, the cookie is not setted with mod_auth_openidc_state_ and the user is not redirected to login page.
https://{domain}/sso

I see that setting OIDCDefaultURL it works on IE.
I need to aceess the OIDCRedirectURI end to be redirect to OIDCDefaultURL
 <p>Submitting...</p> Script need to executed
 
###### Actual behaviour
On Chrome or Firefox if the final user access the OIDCRedirectURI direct, he will see the invalid request error.

In IE it  is working but in Chrome or Firefox I have a error:
Error:
Invalid Request
Description:
You've hit an OpenID Connect Redirect URI with no parameters, this is an invalid request; you should not open this URL in your browser directly, or have the server administrator use a different OIDCRedirectURI setting.

ap_headers_error_filter()
###### Minimized example

    OIDCRedirectURI https://{domain}/sso
    OIDCProviderMetadataURL https://{some domain/openid-configuration
    OIDCClientID xxx
    OIDCClientSecret xxx
    OIDCResponseType 'code'
    OIDCPreservePost On
    OIDCProviderAuthorizationEndpoint xxx
    OIDCProviderTokenEndpoint xxx
    OIDCProviderTokenEndpointAuth client_secret_post
    OIDCProviderEndSessionEndpoint xxx
    OIDCProviderUserInfoEndpoint xxx
    OIDCCryptoPassphrase random1234
    OIDCResponseMode form_post
    OIDCPassIDTokenAs payload
    OIDCPathAuthRequestParams xxx
    OIDCCacheShmEntrySizeMax 65536
    #OIDCStateTimeout 28800
    OIDCStateMaxNumberOfCookies 7 true
    OIDCDefaultURL https://{domain}

    <Location />
        AuthType openid-connect
        Require valid-user
        SetHandler dispatcher-handler

        RequestHeader set "X-KO-SALT" "S4LT_K3Y_G03S_H3R3"
    </Location>

###### Configuration and Apache server log files
*Config and logs for the minimized example, possibly provided as attachments.*

**Logs**
log with error in chorme
[log-qa.txt](https://github.com/zmartzone/mod_auth_openidc/files/3015206/log-qa.txt)

log working in IE
[log-from-IE-working.txt](https://github.com/zmartzone/mod_auth_openidc/files/3015342/log-from-IE-working.txt)

**Request** from Chrome 
Request URL: https://{domain}/sso
Request Method: POST
Status Code: 200 OK
Remote Address: 35.232.24.166:443
Referrer Policy: no-referrer-when-downgrade
**Response Header**
Connection: Keep-Alive
Content-Length: 541
Content-Type: text/html
Date: Wed, 27 Mar 2019 21:33:44 GMT
Keep-Alive: timeout=15, max=91
Server: 
**request Header**
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 22
Content-Type: application/x-www-form-urlencoded
Cookie: mod_auth_openidc_session={..}
Host: {domain}
Origin: https://{domain}
Pragma: no-cache
Referer: https://{domain}/sso
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
**form data**
response_mode: fragment

**Request from IE Eorking**
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
https://{domain}/sso	HTTPS	POST	302	text/html	229 B	247.61 ms	document
**request header**
Accept: text/html, application/xhtml+xml, image/jxr, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 24
Content-Type: application/x-www-form-urlencoded
Cookie: mod_auth_openidc_state_XiBDKppwryTgibylRWyqo-HYh1U={...}
Host: {domain}
Referer: https://{domain}/sso
**response header**
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Connection: Keep-Alive
Content-Length: 229
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 27 Mar 2019 21:39:49 GMT
Keep-Alive: timeout=15, max=99
Location: https://{domain}/
Server: 
Strict-Transport-Security: max-age=31536000; includeSubDomains
**Response payload**
Connection: Keep-Alive
Content-Length: 229
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 27 Mar 2019 21:39:49 GMT
Keep-Alive: timeout=15, max=99
Location: https://{domain}
Server: 
Strict-Transport-Security: max-age=31536000; includeSubDomains

**Comment by zandbelt** [comment]
please set the server log level to debug and inspect the logs to find out what is happening in the case of "sometimes" as opposed to the regular case; there's not much more to be done with this info
