### ISSUE TITLE
requested an invalid redirect URL

### ISSUE THREAD

**Issue by chickarg** [zmartzone/mod_auth_openidc#439]
THIS ISSUER TRACKER IS NO LONGER USED!
DON'T CREATE ANY NEW ISSUES AS THEY WILL BE CLOSED IMMEDIATELY AS INVALID!
QUESTIONS SHOULD GO TO THE MAILINGLIST AT: mod_auth_openidc@googlegroups.com

**Comment by zandbelt** [comment]
thanks for bringing this up
