### ISSUE TITLE
(Sometimes) not restoring params in POST 

### ISSUE THREAD

**Issue by janul** [zmartzone/mod_auth_openidc#441]
Hi,
Sometimes (could not find any pattern)  POST requests to protected location losing params in the final  stage. Looks that for some reason doesn't restore the original state.
- Tested with v2.3.3 and v2.3.11
- environment: docker (ubuntu bionic) : apache + oidc module behind edge proxy
- cache: tested with both shm and memcache
- debug in file when issue occurred  
Thanks,

[oidc-post-issue.txt](https://github.com/zmartzone/mod_auth_openidc/files/3281258/oidc-post-issue.txt)

**Comment by zandbelt** [comment]
Seems like you're doing something interfering with SAML requests? The form post preserve is meant just for simple user-filled forms. I don't think typically users would enter SAML requests manually and then hit the inactivity timeout?

**Comment by janul** [comment]
This SAML request (POST) is triggered by SPs so enduser doesn't do anything manually. 
~8/10 works fine - oidc module restores original POST params. Could it be something like not storing postdata correctly in cache ?

**Comment by zandbelt** [comment]
My guess is that it has to do with "weird" characters in the (SAML) POST data. But I don't have the time to dig into it unless someone is willing to get into a commercial agreement for this :-\

**Comment by janul** [comment]
That's fine. I will try to dig into it. what i found is that when that issue happens postdata still existed in localStorage.

**Comment by zandbelt** [comment]
could you send the localstorage contents to me directly?

**Comment by janul** [comment]
thanks, will do. Before I will modify source code to get more accurate details and then send it to you .

**Comment by zandbelt** [comment]
any progress there?

**Comment by zandbelt** [comment]
closing due to lack of progress

**Comment by janul** [comment]
hi, sorry been busy.
I tested today again (2.4.0). It looks like issue is only in Firefox in private mode.
tested javascipt from mod_auth_openidc/src/mod_auth_openidc.c   line 465
and whatever I'm trying to store in localStorage or sessionStorage I'm getting null after getItem.
So it looks like there is an issue with accessing storage in Firefox (priv mode)

**Comment by janul** [comment]
hi @zandbelt 
Finally I had a chance to sit down and investigate this issue,
Tested with recent 2.4.0
Browsers: Chrome, Firefox
Affected browser: Firefox in private mode in new session
   mod_auth_openidc/src/mod_auth_openidc.c
- block: 464 - 473
  javascript stores mod_auth_openidc_preserve_post_params in localStorage correctly as I can get item after inside that function
- block: 498 - 521
  localStorage.getItem('xyz')  gives me null

I tested with static value with the same result.
No issess in public mode and chrome (incognito and public)

Solution which worked for me was changing from localStorage to sessionStorage.
