### ISSUE TITLE
Office Documents and IE redirecting to home page.

### ISSUE THREAD

**Issue by marcelodcp** [zmartzone/mod_auth_openidc#442]
When we are using Microsoft Office document, we may experience issues before open the page that we requested, we can be redirected to home page or error page clicking in some link inside the doc.

The Office session is independent of the Web browser session. Is there some configuration that we can use to have links inside doc works?

Steps to reproduce:
1) open the Office document in edit mode outside the Web browser.
2) Click in some link that redirect to some deep path in the site that have SSO.
Result: You will be redirect to home page.

Expected behavior:
To be redirect for the deep path that is inside the Office document

Thanks

Marcelo de Castro

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
