### ISSUE TITLE
Authentication require when Cookies not sent on OPTIONS requests

### ISSUE THREAD

**Issue by olopost** [zmartzone/mod_auth_openidc#455]
For an Angular 1 app my team working on, openidc authentication is used. The problem is: when making OPTIONS calls, cookies are not sent and the server tries to redirect user to login again.

**How can i configure my mod_auth_openidc protected virtual host to accept OPTIONS call ?**

W3 specification https://www.w3.org/TR/cors/#preflight-request

> Otherwise, make a preflight request. Fetch the request URL from origin source origin using referrer source as override referrer source with the manual redirect flag and the block cookies flag set, using the method OPTIONS, and with the following additional constraints … Exclude user credentials.

Thanks for your feedback

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
