### ISSUE TITLE
pattern match on groups claim

### ISSUE THREAD

**Issue by jansmets** [zmartzone/mod_auth_openidc#462]
Hi
Could  you please tell me how I can do a pattern/wildcard match on groups.

oidc_util_json_merge: result dst={"sub":"b6ae18eb-3831-4aab-89f
1-24cfa43bc9a2","email_verified":true,"name":"Jan Smets","groups":["/testgroup/subgroup1","offline_access","uma_authorization"]

Works:
Require claim expr "groups:/testgroup/subgroup1"
Does not:
Require claim expr "groups:/testgroup/*"
(also tried something like claim expr group in { '/testgroup/* } - but I'm not sure that's even valid syntax.)

Thank you.

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
