### ISSUE TITLE
make X-Frame-Options configurable

### ISSUE THREAD

**Issue by zandbelt** [zmartzone/mod_auth_openidc#464]
> Have setup mod_auth_openidc v2.4.1 (though the issue seems to predate this version) to authenticate to an IdentityServer4 OP.
> 
> I've setup the OP to use /redirect?logout=get  as the front-channel logout as mentioned here https://github.com/zmartzone/mod_auth_openidc/wiki#9-how-do-i-logout-users
> 
> Whenever I attempt an OP initiated Sign-out, IdentityServer4 uses iframes in order to contact each RP in order to perform the logouts.
> 
> However, in mod_auth_openidc.c, oidc_handle_logout_request sets the X-Iframe-Options:DENY header
> oidc_util_hdr_err_out_add(r, OIDC_HTTP_HDR_X_FRAME_OPTIONS, "DENY");
> 
> This prevents the OP from calling the logout URL via iframe.
> 
> RP initiated logouts work fine, as the logout parameter isn't set to "get", but a post logout url instead.
> 
> Removing the line, and compiling from source fixes my issue, though I'm wondering if this was added for some spec/security reason?

**Comment by zandbelt** [comment]
the idea was that the OP should call logout URLs in a full browser, one by one; allowing it in an iframe makes it more vulnerable to clickjack attacks, see:https://www.keycdn.com/blog/x-frame-options; making it configurable makes most sense

**Comment by dortamur** [comment]
We have this same issue using Microsoft AzureAD, which does Single Sign-Out callbacks to all apps in iframes. 
It would be really useful to disable the Deny header, or configure it to whitelist certain calling domains.
