### ISSUE TITLE
RFE: Add CentOS / RHEL 8 package to releases

### ISSUE THREAD

**Issue by CRCinAU** [zmartzone/mod_auth_openidc#465]
With RHEL8 now going full swing, it would be nice to have packages for the releases available for both EL7 and EL8.

**Comment by tbouvetgh** [comment]
Is there any backports available for centos 6.10 mod_auth_openidc 2.x?

**Comment by VonNao** [comment]
I encounter the same problem with CentOS 8 lately. In the Documentation is written that it should be available in appstream but it isn't. Even the cjose dependacies are missing so no luck installing the rpm either. Is their any update on the release?

**Comment by CRCinAU** [comment]
So a bit of an update.... EL8 is a bit.... special... along the lines of the kids that sit in the corner and eats crayons all the time... They do have a mod_auth_openidc package - but its hidden in a module - which has 1-2 packages at most.

So, enable the module - otherwise you have no idea it even exists: `dnf module enable mod_auth_openidc`

Then install it as you would normally: `dnf install mod_auth_openidc`

You should get version 2.3

**Comment by eponafyrefly** [comment]
I am encountering an issue when attempting to install this module on RHEL 8.  RHEL 8 requires modules to have default profiles, or it will not install them.  Since this mod has no profile we receive an error:

```
yum module install mod_auth_openidc
No default profiles for module mod_auth_openidc:2.3
Error: Problems in request:
missing groups or modules: mod_auth_openidc

yum module info mod_auth_openidc
Name             : mod_auth_openidc
Stream           : 2.3
Version          : 8020020200604180605
Context          : 4cda2c84
Architecture     : x86_64
Profiles         : 
Default profiles : 
Repo             : rhel-8-for-x86_64-appstream-rpms
Summary          : Apache module suporting OpenID Connect authentication
Description      : This module enables an Apache 2.x web server to operate as an OpenID Connect Relying Party and/or OAuth 2.0 Resource Server.
Requires         : platform:[el8]
Artifacts        : cjose-0:0.6.1-2.module+el8+2454+f890a43a.src
                 : cjose-0:0.6.1-2.module+el8+2454+f890a43a.x86_64
                 : cjose-debuginfo-0:0.6.1-2.module+el8+2454+f890a43a.x86_64
                 : cjose-debugsource-0:0.6.1-2.module+el8+2454+f890a43a.x86_64
                 : cjose-devel-0:0.6.1-2.module+el8+2454+f890a43a.x86_64
                 : mod_auth_openidc-0:2.3.7-4.module+el8.2.0+6919+ac02cfd2.3.src
                 : mod_auth_openidc-0:2.3.7-4.module+el8.2.0+6919+ac02cfd2.3.x86_64
                 : mod_auth_openidc-debuginfo-0:2.3.7-4.module+el8.2.0+6919+ac02cfd2.3.x86_64
                 : mod_auth_openidc-debugsource-0:2.3.7-4.module+el8.2.0+6919+ac02cfd2.3.x86_64
```

Thanks,
Christine Shepherd, TSE at Red Hat.

**Comment by zandbelt** [comment]
@eponafyrefly that's a Redhat packaging issue... https://bugzilla.redhat.com/show_bug.cgi?id=1780095

**Comment by zandbelt** [comment]
A CentOS 8 package is now provided for release 2.4.4 https://github.com/zmartzone/mod_auth_openidc/releases/tag/v2.4.4
