### ISSUE TITLE
Multiple Location and session context 

### ISSUE THREAD

**Issue by an2deg** [zmartzone/mod_auth_openidc#481]
I'm experimenting with mod_auth_openidc and trying to make [OpenID Connect Session Management](https://github.com/zmartzone/mod_auth_openidc/wiki/OpenID-Connect-Session-Management) setup work.

I would like to clarify few things which are not clear for me. Imaging I have the following configuration:

```
<VirtualHost>
        ProxyPass / http://legacy-backend:8000/
        ProxyPassReverse /  http://legacy-backend:8000/
        OIDCRedirectURI https://dev.local/openid/callback
        OIDCProviderMetadataURL https://our-dev.oktapreview.com/oauth2/default/.well-known/openid-configuration
...
       <Location />
               AuthType openid-connect
               Require valid-user
       </Location>

       <Location /some/spefic/location>
               AuthType openid-connect
               Require valid-user
               AddOutputFilterByType SUBSTITUTE text/html
               Substitute "s|</body>|<iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-op' src='/openid/callback?session=iframe_op'></iframe><iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-rp' src='/openid/callback/redirect_uri?session=iframe_rp\&amp;poll=5000'></iframe></body>|i"
       </Location>
</VirtualHost>
```

My questions here:

1. Does having 2 locations with `AuthType openid-connect` mean that I have 2 different mod_openidc session contexts and 2 different mod_openidc sessions?
2. Do I need to specify `AuthType openid-connect` and `Require valid-user` for `/some/spefic/location`? In my case I only need it for injecting iframes into specific HTML page.

Thanks in advance!

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
