### ISSUE TITLE
REMOTE_USER not accessible in IF directive 

### ISSUE THREAD

**Issue by kuwars98** [zmartzone/mod_auth_openidc#483]
Hello 

To begin thank you for your excellent work on this module!
REMOTE_USER environment variable is not used with IF module 

I want implement same ACL for some user but i'm not able to find solution, My URL is protected with SSO. There are added some users in SSO level from that user would be access URL but from the list of user i need to block access for single user. i know I can block access of user from SSO if i have removed user from SSO so that user will not be able to access but i want to achieve this think through httpd.conf file. 
Could it be possible to implement my requirement if yes so please help me ?  
```
<Location "/">
      order allow,deny
      <If "%{REMOTE_USER} == 'testuser'">
      allow from all
      </If>
      <Else>
      deny from all
      </Else>
</Location>
```

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
