### ISSUE TITLE
Protecting a folder behind a reverse proxy using .htaccess file

### ISSUE THREAD

**Issue by biligee** [zmartzone/mod_auth_openidc#490]
I have two PCs 192.168.0.1 and 192.168.0.2. keycloak runs at the 192.168.0.1. I want to protect folder "1" in 192.168.0.2 using the settings in .htaccess by accessing through http://192.168.0.1/1 (proxied to 192.168.0.2). mod_auth_openidc is installed in 192.168.0.2. If I use <location /1> directive in 192.168.0.1, it is working. However, I want to use .htaccess at 192.168.0.2. It is looping and ends with too many redirects.  Is there any chance to use .htaccess at the 192.168.0.2 rather than <location /1> directive in 192.168.0.1?

apache settings in 192.168.0.1:
```
ProxyPass /1 http://192.168.0.2/1
ProxyPassReverse 1/ http://192.168.0.2/1

ProxyPreserveHost On
ProxyRequests Off
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"

ProxyPass /auth http://192.168.0.1:8080/auth
ProxyPassReverse /auth http://192.168.0.1:8080/auth

<Location "/oidc">
  AuthType openid-connect
  Require valid-user
</Location>
```

auth_openidc.conf settings at the 192.168.0.2

```
OIDCRedirectURI http://192.168.0.1/oidc
OIDCCryptoPassphrase xyz
OIDCProviderMetadataURL http://192.168.0.1/auth/realms/test/.well-known/openid-configuration
OIDCClientID basic
OIDCClientSecret xxxxxx
OIDCRemoteUserClaim preferred_username
OIDCSSLValidateServer Off
OIDCOAuthSSLValidateServer Off
OIDCAuthNHeader X-Forwarded-User
```

.htaccess at the 192.168.0.2

```
AuthType openid-connect
<Files ~ "^.(htpasswd|htaccess)$">
Require all denied
</Files>
Require user test 
```

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
