### ISSUE TITLE
segmentation fault on cache encryption

### ISSUE THREAD

**Issue by zandbelt** [zmartzone/mod_auth_openidc#494]
> Finally, I have a question when using token introspection with JWT access token.
> (There are a few test cases revoking access token in FAPI conformance test. Need to use token introspection to pass the cases.)
> It looks working but it outs the following error in my environment.
> 
> api_gateway_apache2_1  | [Tue Oct 27 01:53:14.411408 2020] [auth_openidc:error] [pid 51] [client 172.24.0.8:42530] oidc_cache_shm_get_key: could not construct cache key since key size is too large (2235 >= 512) (a:eyJhbGciOiJSUzI1NiIsInR5cC...)
> api_gateway_apache2_1  | [Tue Oct 27 01:53:14.411478 2020] [auth_openidc:warn] [pid 51] [client 172.24.0.8:42530] oidc_cache_get: error retrieving value from shm cache backend for key eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ...
> 
> I found the workaround in the following old issue, but couldn't improve it.
> https://github.com/zmartzone/mod_auth_openidc/issues/388#issuecomment-420544583
> 
> * OIDCCacheEncrypt On
> => Segmentation fault

**Comment by wadahiro** [comment]
@zandbelt I made a docker image for the reproducing issue. Could you check it?

https://github.com/wadahiro/mod_auth_openidc_issue_494

**Comment by zandbelt** [comment]
turns out `OIDCCryptoPassphrase` is missing; I'll work on a fix to signal this
