### ISSUE TITLE
Multiple ClientID/Secrets per OP

### ISSUE THREAD

**Issue by mk0** [zmartzone/mod_auth_openidc#496]
In order to utilize one web server for multiple applications, it is important to be able to provide dedicated client IDs and secrets per Location directive, which is currently not possible.

The feature of using multiple providers will not help on this topic, since it will be the same provider.

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid

**Comment by mk0** [comment]
This is a feature request and there is no reasoning to simply close this issue. I will ask my colleague Mr. Vogler to get back to you, if we cannot manage this using the issue tracker on GitHub.
