### ISSUE TITLE
does the mod_auth_openidc support Apache 2.0? 

### ISSUE THREAD

**Issue by 2168028160** [zmartzone/mod_auth_openidc#498]
Hello, does the mod_auth_openidc support Apache 2.0? Or can you tell me which version of mod_auth_openidc is supported by Apache 2.0 and 2.2 respectively?

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
