### ISSUE TITLE
autodetection of UserInfo JWT responses

### ISSUE THREAD

**Issue by chrisFrodo** [zmartzone/mod_auth_openidc#525]
Hello,

I'm using mod_auth_openidc 2.4.5 on Apache 2.4.38. Mod_auth_openidc is configured to use JWS signature with `OIDCPublicKeyFiles`, `OIDCPrivateKeyFiles` and a JWKS exposed by the client.
When I'm authenticating on Apache, it works but logs show the following error :

```
oidc_util_decode_json_object: JSON parsing returned an error: '[' or '{' expected near 'eyJhbGciOiJSUzI' (eyJhbGciOiJSUzIa ... ddC-2cpLWvGY0z91BVHNA4r7Y)
oidc_retrieve_claims_from_userinfo_endpoint: resolving user info claims with the existing/provided access token failed, nothing will be stored in the session
```

I've created a local infrastructure to use full HTTP and sniff the network. This is what I've seen :

1. Mod_auth_openidc requests `/auth/realms/REALM/protocol/openid-connect/userinfo` with a Bearer token
2. Keycloak answers with a JWS and `Content-Type: application/jwt`
3. mod_auth_openidc tries to Json-decode the body and generates an error.

The OpenID Connect Specs say, I quote :

```
If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be application/jwt.
```
Source: https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse

I think that mod_auth_openidc doesn't manage the Content-Type `application/jwt` for the UserInfo Response and always presumes it's a JSON body.

What do you think ?

Thank you.

**Comment by zandbelt** [comment]
you are correct, auto-detection is probably a good idea, but decoding a signed JWT returned from the user info endpoint is supported in principle by setting `OIDCUserInfoSignedResponseAlg ` https://github.com/zmartzone/mod_auth_openidc/blob/v2.4.5/auth_openidc.conf#L286-L290

**Comment by chrisFrodo** [comment]
Hello,

I've tried `OIDCUserInfoSignedResponseAlg` and it resolved my issue. Thanks.

Are you going to implement signature and encryption auto-detection for userinfo endpoint and id_token in the future ?

**Comment by zandbelt** [comment]
I don't think there's a good case for auto-detection: it should be clear from the OP what it returns beforehand.
