### ISSUE TITLE
Collision on default session cookie name(mod_auth_openidc_session) causes infinite/endless loop

### ISSUE THREAD

**Issue by taojing10** [zmartzone/mod_auth_openidc#560]
Hi!

Our app was facing infinite/endless loop issue when using OpenID(mod_auth_openidc) on apache. This issue is randomly happened so it is really hard to track it down.

We found the root cause and the fix, but we want to see if any action can be taken here.

# Root Cause
Lets say we have two apps using OpenID with default `OIDCCookie` which is mod_auth_openidc_session
appA have set `OIDCCookieDomain` as aaa.com even they are using subdomain bbb.aaa.com
appB with none of them setup and they are using ccc.aaa.com

If a user use both of the apps in a short time, he will have two `mod_auth_openidc_session` cookies in Brower, one is for `aaa.com`(appA) and other is `ccc.aaa.com`(appB). It will cause infinite/endless loop for appB because the appB server will use appA's cookie to validate (failed to validate -> get a new one -> still failed)

# The fix
The fix can be setup correct `OIDCCookieDomain` or use unique `OIDCCookie` on config. But if any app uses default cookie name and setup a top-level domain will mess up all other apps who have default config.

Can we add a filter feature on session validation? For example, 

check the come-in domain on request and validate the matched-domain cookie.
Or
When validation happens, make the subdomain as higher priority.
Or
Validate all the cookies under same top-level domain.

Thanks

**Comment by zandbelt** [comment]
the default behaviour is -as documented - a server wide cookie; that will also allow sharing the sessions between different vhosts, which is also a typical setup; your case requires a more specific `OIDCCookieDomain` setting, that's why this primitive exists; if you feel that the documentation on this should be improved, feel free to do so, but code-wise these defaults make most sense
