### ISSUE TITLE
Multiple OIDCRedirectURI not working

### ISSUE THREAD

**Issue by gabhinandan** [zmartzone/mod_auth_openidc#578]
Hi,
I have gone through Multiple redirect URIs for multiple tomcat instances #281 , however its not working in my case.

I have LB and an Apache server (behind LB) which are performing the authentication.
If I put OIDCRedirectURI = https://LB/secure/redirect_uri  in vHost, then it will work only when I use LB url i.e. https://LB/apps/myapp.html
however if I want to check the server url (without LB), then it wont work. I have to disable above OIDCRedirectURI, replace LB with actual hostname, bounce apache and then it will work, but in that case, it does not work for LB url. 

The need is both of the URL should work simultaneously. Also In Production I have around 10 Apache server, so it is cumbersome to maintain these many URL (for separate web server based) at Azure end.

**Comment by gabhinandan** [comment]
Since I am trying to access same application https://LB/apps/myapp.html, https://Apache/apps/myapp.html , I can not use two different vHosts, since DocumentRoot is same. Correct me if wrong.

**Comment by gabhinandan** [comment]
Checked this as well -

Relative path not working for OIDCRedirectURI #413

Not working, getting the same error. My current version is 2.4.7

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
