### ISSUE TITLE
Release 2.4.8.4 depends on libhiredis0.13

### ISSUE THREAD

**Issue by drentha** [zmartzone/mod_auth_openidc#621]
Hi, in Ubuntu 20.04 

sudo dpkg -i libapache2-mod-auth-openidc_2.4.8.4-1.bionic+1_amd64.deb

It needs libhiredis0.13.  However Ubuntu 20.04 uses libhiredis0.14.  (Error message below)

How do I resolve this?

Thanks

(Reading database ... 130912 files and directories currently installed.)
Preparing to unpack libapache2-mod-auth-openidc_2.4.8.4-1.bionic+1_amd64.deb ...
Unpacking libapache2-mod-auth-openidc (2.4.8.4-1~bionic+1) over (2.4.8.4-1~bionic+1) ...
dpkg: dependency problems prevent configuration of libapache2-mod-auth-openidc:
 libapache2-mod-auth-openidc depends on libhiredis0.13 (>= 0.13.1); however:
  Package libhiredis0.13 is not installed.

dpkg: error processing package libapache2-mod-auth-openidc (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libapache2-mod-auth-openidc

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
