### ISSUE TITLE
curl_easy_perform failed

### ISSUE THREAD

**Issue by akitzing** [zmartzone/mod_auth_openidc#662]
I have built an image according to the dockerfile-alpine. When calling the URL the logfile shows the error: 

> oidc_util_http_call: curl_easy_perform() failed on <OpenID-Provider> (SSL certificate problem: self signed certificate in certificate chain).

How do I get curl in the build process (configure/make) to include the CA certificate that was already copied into the image.

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
