### ISSUE TITLE
Memory leak when multiple graceful

### ISSUE THREAD

**Issue by boucho-o** [zmartzone/mod_auth_openidc#667]
Hi,

I've notice a memory leak with the module mod_auth_openidc when i use graceful restart my HTTPD server with all MPM .

> Method used
> -----------
> for i in {1..100}; do echo $i; systemctl reload httpd; sleep 1; done
> during the loop i perform some auth in browser.
>
> Content of "reload" parts on systemd file httpd 
> ...
> ExecReload=/usr/sbin/httpd $OPTIONS -k graceful
> ...

I found it in OS Centos / Fedora with those RPM.

- httpd-2.4.48-1.fc34.x86_64
- mod_auth_openidc-2.4.9-1.fc34.x86_64

I also compile and try the latest version 2.4.9.3 and some previous version >=2.3, same issue.

My first analysis with valgrind show some leak with libcurl and a lot of other stuff ! does it ring a bell to you ?
I'am not an expert with valgrind and i try a lot of different parameter, i thing i reach my limit.

Currently i used this line :

`valgrind --leak-check=full --show-reachable=yes --trace-children=yes --gen-suppressions=all --suppressions=/tmp/not_interesting_error.supp --tool=memcheck --log-file=memleak.log /usr/sbin/httpd -DFOREGROUND`

> content of not_intersting_error.supp is build with all error found when the module mod_auth_openidc is not loaded/used

i would like to dig more on this subject but i need help to be guide through memory leak solution/software in order to found something relevant.

thanks

btw, i love your work on this module ;-)

**Comment by zandbelt** [comment]
what makes you think memory is leaking?

**Comment by boucho-o** [comment]
Thanks Zandbelt,

When i use my method (describe previously) i follow the memory

- 6.34Go ram before start httpd
- 6.44 Go when started
- 9.61 Go after 10 gracefull
- 6.36 Go after stop httpd

Have you succeed to reproduce this issue ?

thanks,

**Comment by zandbelt** [comment]
I'm not sure what command you're using to find out about this but: 
- this doesn't mean that there's a memory leak as apache can buffer/cache things
- even if there's a leak it could be anything, not necessarily mod_auth_openidc
- I'm not able to reproduce this using valgrind: graceful restarts with incoming requests in between them do not result in memory leaks in mod_auth_openidc

Unless you can show a valgrind stat with "memory definitely leaked" in mod_auth_openidc, I'll assume this is a red herring. Please follow up in Discussions if you need to.
