### ISSUE TITLE
Autotools usage is .... unorthodox

### ISSUE THREAD

**Issue by alerque** [zmartzone/mod_auth_openidc#674]
I understand autotools is a mean and ugly piece of dark magic that nobody likes and at best only beat into submission and then move on and hope it doesn't break. That being said I have to ask (with a laugh): Where did you come up with the autotools implementation for this project? No personal offense meant of course, but this stuff is crazy-pants:

https://github.com/zmartzone/mod_auth_openidc/blob/c675949ca3609c9fe7dc0bccdaa093021ac59cbe/Makefile.in#L70-L71

https://github.com/zmartzone/mod_auth_openidc/blob/c675949ca3609c9fe7dc0bccdaa093021ac59cbe/Makefile.in#L85-L86

(There is more), but the entire Makefile template looks like it is re-implementing stuff from scratch that automake is supposed to do by itself, and in the process breaking the normal usage patterns.

Would you be open to a PR that completely overhauls this if I were to clean it up a bit?

**Comment by zandbelt** [comment]
I'm glad you like it ;-) I'm interested to know on what platform you experience problems.
Feel free to submit a PR and I'll review, I don't think this is an issue though:
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid

**Comment by alerque** [comment]
This is an issue.

I'm an packager for Arch Linux and ran into problems when trying to bring the current user contributed [AUR recipie](https://aur.archlinux.org/packages/mod_auth_openidc) closer to Arch Linux packaging guidelines. I would like to eventually migrate it to the default distro package repository, but first it needs to follow the guidelines.

The current Makefile situation (as highlighted by snippets above) means that running `make install` does not *install*, it *builds*. This means what is happening during the `build()` phase is not actually a build, and what is happening during `package()`, which should be just moving already built things to predefined distro locations is actually building. Also it doesn't create the directory like it should.

This is just the tip of the iceburg, looking at why that separation was going wrong let me to look at the other rules and almost everything is backwards and mostly re-inventing autotools stuff, hence this issue.

**Comment by alerque** [comment]
The installation has improved dramatically in the latest release, but for distro packaging it is still not *quite* there. I just had to monkey patch the setup to get something that would install to a specific target directory. Most package managers handle this the same way, you "install" to a target directory and then everything there gets packaged up. As such the default install mechanism that only allows installing to the apxs specified location and modifying the running config of the machine is unworkable. This prepare works:

```bash
sed -i -e '72d;73{s/^.//;s/@/$(DESTDIR)@/}' Makefile.am
 ```

 This deletes the default install method, uncomments the alternative, and adds a DESTDIR prefix. This should be the default `make install` action. The variant that installs it "hot" and modifies the system config should be in a different non-default target.
