### ISSUE TITLE
Installing Jansson gives dependency issue for glibc 2.14 version

### ISSUE THREAD

**Issue by rajindr88** [zmartzone/mod_auth_openidc#677]
I was following your step to install mod_auth_openidc with dependency using below steps

sudo wget https://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/Packages/glibc-2.28-151.el8.x86_64.rpm
sudo yum localinstall -y glibc-2.28-151.el8.x86_64.rpm
sudo wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-2.10-1.el7.x86_64.rpm
sudo yum localinstall -y ~/jansson-2.10-1.el7.x86_64.rpm
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/jansson-devel-2.10-1.el7.x86_64.rpm
yum localinstall -y ~/jansson-devel-2.10-1.el7.x86_64.rpm
wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.0/cjose-0.5.1-1.el7.centos.x86_64.rpm
yum localinstall -y ~/cjose-0.5.1-1.el7.centos.x86_64.rpm
sudo wget https://github.com/zmartzone/mod_auth_openidc/releases/download/v2.3.9/mod_auth_openidc-2.3.9-1.el7.x86_64.rpm
yum localinstall -y ~/mod_auth_openidc-2.3.9-1.el7.x86_64.rpm

But during first step itself getting dependency issue for glibc with particular version 2.14
So can you please recommend way to insatall mod_auth_openidc with its dependencies in Redhat server

![image](https://user-images.githubusercontent.com/70029527/132714441-aafdecdf-ec68-4352-92e2-573ad80ad8c8.png)

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
