### ISSUE TITLE
mod_auth_openidc installation successfull but Single Sign On configuration giving error while starting Apache

### ISSUE THREAD

**Issue by rajindr88** [zmartzone/mod_auth_openidc#687]
While configuring mod_auth_openidc in Apache files, I am getting below error

Starting httpd-ssc: httpd-ssc: Syntax error on line 58 of /etc/httpd-ssc/conf/httpd.conf: Syntax error on line 10 of /etc/httpd-ssc/conf/includes.conf: Syntax error on line 26 of /etc/httpd-ssc/conf/xclinkssc.xdev.motive.com_3443.conf: Cannot load /usr/lib64/httpd/modules/mod_auth_openidc.so into server: /usr/lib64/httpd/modules/mod_auth_openidc.so: undefined symbol: ap_requires

Below are the version I am using
Redhat                                 6.10
mod_auth_openidc              mod_auth_openidc-1.8.9-1.el6.x86_64.rpm
Apache                                 2.2.15

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
