### ISSUE TITLE
OIDCUnAutzAction action to explain how to get authorized (new feature)

### ISSUE THREAD

**Issue by chrisinmtown** [zmartzone/mod_auth_openidc#715]
### Discussed in https://github.com/zmartzone/mod_auth_openidc/discussions/711

<div type='discussions-op-text'>

<sup>Originally posted by **chrisinmtown** October 20, 2021</sup>
We need to display a message to users who are authenticated by mod-auth-openidc via the company-wide OAuth server, but who are NOT specifically authorized for the protected webapp. The message should explain how to get authorized, which is usually an involved process and always difficult to discover.

I was thinking maybe this could be a new option for the OIDCUnAutzAction action. Some possibilities might be:
1) Display static text with a message (limiting, but better than nothing)
2) Redirect to a URI, which might be an unprotected page in the webapp or another company site with instructions

Thanks in advance for considering it.</div>

**Comment by zandbelt** [comment]
please test 192f083c3e6208a39a2ad67bee53b83d25599fc2 and provide your feedback

**Comment by chrisinmtown** [comment]
Thanks @zandbelt !  I have not yet built this from source, so getting set up to test this might take me a while.

**Comment by zandbelt** [comment]
I can provide a release candidate package if you specify the target platform that you run on

**Comment by chrisinmtown** [comment]
That's a really nice offer, thank you!  I'm using a Debian-Bullseye docker image.  I was going to make an attempt at writing a Dockerfile that builds mod-auth-openidc from source. That Dockerfile might also be a nice addition to your repo, would you have any interest in that?

**Comment by zandbelt** [comment]
no, there's 2 Dockerfile already plus lots of Dockerfiles in other repos; and I actually want those in here to end up somewhere else as well one day; the Bullseye build is here https://www.mod-auth-openidc.org/downloads/libapache2-mod-auth-openidc_2.4.10rc1-1~bullseye+1_amd64.deb

**Comment by zandbelt** [comment]
included in 2.4.10

**Comment by chrisinmtown** [comment]
Thanks for the debian package, I finally made time to test these three scenarios: 401 with text message (works), 403 with text message (works), 302 with redirect URL (also works).
