### ISSUE TITLE
building 2.4.10 fails with warning: type of 'ap_hook_insert_filter' does not match original declaration [-Wlto-type-mismatch]

### ISSUE THREAD

**Issue by stroeder** [zmartzone/mod_auth_openidc#732]
Trying to update the openSUSE package to 2.4.10 fails.

See .spec file:
https://build.opensuse.org/package/view_file/home:stroeder:iam/apache2-mod_auth_openidc/apache2-mod_auth_openidc.spec?expand=1

Full error message:

[   35s] libtool: link: gcc -DNAMEVER=mod_auth_openidc-2.4.10 -I./src -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -Wall -DLDAP_DEPRECATED -DDEFAULT_LISTENBACKLOG=APR_INT32_MAX -DDEFAULT_ERRORLOG=\"/var/log/apache2/error_log\" -I/usr/include/apr-1 -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/usr/include/apache2 -DOPENSSL_LOAD_CONF -DOPENSSL_LOAD_CONF -DUSE_LIBHIREDIS -I/usr/include/hiredis -D_FILE_OFFSET_BITS=64 -DUSE_MEMCACHE -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -flto=auto -flto=auto -o test/test-cmd test/test-cmd.o test/stub.o  ./.libs/libauth_openidc.a -laprutil-1 -lldap -llber -lexpat -lapr-1 -lpthread -lssl -lcurl -lcjose -ljansson -lcrypto -lpcre -lhiredis
[   35s] /usr/include/apache2/http_request.h:558:1: warning: type of 'ap_hook_insert_filter' does not match original declaration [-Wlto-type-mismatch]
[   35s]   558 | AP_DECLARE_HOOK(void,insert_filter,(request_rec *r))
[   35s]       | ^
[   35s] test/stub.c:154:17: note: return value type mismatch
[   35s]   154 | AP_DECLARE(int) ap_hook_insert_filter(request_rec *r) {
[   35s]       |                 ^
[   35s] test/stub.c:154:17: note: type 'int' should match type 'void'
[   35s] test/stub.c:154:17: note: 'ap_hook_insert_filter' was previously declared here
[   35s] + RPM_EC=0

**Comment by zandbelt** [comment]
for the record, this mismatch has been there since version 2.4.0

**Comment by stroeder** [comment]
Sorry this issue is not fixed. Even building 2.4.11 still fails with same error:

```
[   64s] /usr/include/apache2/http_request.h:558:1: warning: type of 'ap_hook_insert_filter' does not match original declaration [-Wlto-type-mismatch]
[   64s]   558 | AP_DECLARE_HOOK(void,insert_filter,(request_rec *r))
[   64s]       | ^
[   64s] test/stub.c:154:18: note: type mismatch in parameter 1
[   64s]   154 | AP_DECLARE(void) ap_hook_insert_filter(request_rec *r) {
[   64s]       |                  ^
[   64s] test/stub.c:154:18: note: type 'struct request_rec' should match type 'void ap_HOOK_insert_filter_t (struct request_rec *)'
[   64s] test/stub.c:154:18: note: 'ap_hook_insert_filter' was previously declared here
```
