### ISSUE TITLE
requiring multiple claims with multi OP setup

### ISSUE THREAD

**Issue by zandbelt** [zmartzone/mod_auth_openidc#775]
### Discussed in https://github.com/zmartzone/mod_auth_openidc/discussions/770

<div type='discussions-op-text'>

<sup>Originally posted by **rajeevn1** January 16, 2022</sup>
I am using 2.4.10-1~bullseye+1 release from github with multiple providers (google, globus, gitlab).

The following works

\<RequireAll>
\# Require not claim email_verified:false
Require claim email~^(test1@gmail\.com|test2@gmail\.com)$
\</RequireAll>

but when I un-comment the claim for email_verified, the authentication always fails.  I have confirmed that email_verified claim, as provided by OP, is either set to true (google, gitlab), or is missing (globus).

The issue does not exist if I use any single provider setup.

I would appreciate any help in resolving the issue.</div>

**Comment by zandbelt** [comment]
@rajeevn1 would you be able to test a fix by building from source?

**Comment by rajeevn1** [comment]
@zandbelt yes, I should be able to.

**Comment by zandbelt** [comment]
please try this branch: https://github.com/zmartzone/mod_auth_openidc/tree/fix_discovery_require_all_authz

**Comment by rajeevn1** [comment]
I am getting a different error now, I am not sure if it is a problem with my build.

The original problem of multiple claims with multi OP setup works, but only when the email claim is not a regexp.  If it is a regexp then it fails. 

Not working log.
[nb.txt](https://github.com/zmartzone/mod_auth_openidc/files/7920521/nb.txt)

Working log:
[ng.txt](https://github.com/zmartzone/mod_auth_openidc/files/7920549/ng.txt)

**Comment by zandbelt** [comment]
that seemed to be different issue with regular expressions, which should be fixed now on the same branch; please confirm

**Comment by rajeevn1** [comment]
now it works when OIDCDiscoverURL is not defined (it shows internal page), but with OIDCDiscoverURL defined to a custom URL it just shows a blank page.

**Comment by zandbelt** [comment]
sorry, that was an oversight in the earlier patch, corrected that now

**Comment by rajeevn1** [comment]
It works for me now.
Thank you.

**Comment by zandbelt** [comment]
I had to revert some changes: can you please confirm that https://github.com/zmartzone/mod_auth_openidc/commit/3f082c156da2c410c4024d1c81bac26948d5816a still works for you?

**Comment by rajeevn1** [comment]
It still works for me. Thanks.
