### ISSUE TITLE
Compiling mod_auth_openidc 2.4.11 is not Working on RHEL 6

### ISSUE THREAD

**Issue by manojkavali** [zmartzone/mod_auth_openidc#800]
Hi,
While Compiling mod_auth_openidc 2.4.11 I was getting below error.

=== Build openidc 2.4.11
Expanding ...
Cleaning ...
make: *** No rule to make target clean'. Stop. aclocal: couldn't open directory m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
Configuring ...
./buildapache24.sh.linux_openidc[683]: ./configure: not found [No such file or directory]
Compiling openidc ...

I didn't get any issue with mod_auth_openidc 2.4.9.4 version which was released on Sep 03, 2021. Does something changed between versions 2.4.9.4 and 2.4.11 regarding RHEL 6 ?

Please Advice

Thanks
Manoj

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
