### ISSUE TITLE
OIDC Redirect uri doubt / problem

### ISSUE THREAD

**Issue by nchetbani** [zmartzone/mod_auth_openidc#804]
I try to protect my static resources which is in apache: /var/www/html
In the apache configuration file (httpd.conf), 

1. I imported the module: LoadModule auth_openidc_module /usr/lib64/httpd/modules/mod_auth_openidc.so
2. I add the fellowing configuration :
   ```   
    OIDCProviderMetadataURL <op url>/.well-known/openid-configuration
    OIDCClientID openidc_example
   OIDCClientSecret <my secret>
   OIDCRedirectURI **http://myappi/redirect_uri**
   OIDCCryptoPassphrase <password>
   OIDCJWKSRefreshInterval 3600
   OIDCSSLValidateServer Off

    <Location />
       AuthType openid-connect
       Require valid-user
    </Location>
```
3. I saved as redirect URI (http://myappi/redirect_uri) in client config on OP

When I connect to my application (http://myappi), I am redirected to authentication, but after authentication nothing is displayed and I get 500 errors when the server tries to load static resources (js, html, css, ...)

I tried to figure out the root cause but without success. I have a doubt about the used redirection uri **http://myappi/redirect_uri** because after that the errors start. So I want to know if my configuration/use is correct or there are things missing ?

Any idea please ?

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
