### ISSUE TITLE
auth_openidc module using issue

### ISSUE THREAD

**Issue by nchetbani** [zmartzone/mod_auth_openidc#805]
I have configure the auth_openidc module in my apache as follows:
```

...
LoadModule auth_openidc_module /usr/lib64/httpd/modules/mod_auth_openidc.so
...
**DocumentRoot "/var/www/html"**
...

<VirtualHost *:80>
   ServerName myApp.com
   ...

   OIDCProviderMetadataURL https://<my.op.url>/.well-known/openid-configuration
   OIDCClientID openidc_example
   OIDCClientSecret <secret>
   **OIDCRedirectURI http://myApp.com/protected/redirect_uri**
   OIDCCryptoPassphrase <password>
   OIDCJWKSRefreshInterval 3600
   OIDCSSLValidateServer Off

   <Location /protected/>
      AuthType openid-connect
      Require valid-user
   </Location>

</VirtualHost>

```

The **html** directory contains the frontend part (html, js, css, ...) of my application. As described in this [article ](https://oa.dnc.global/-fr-.html?page=unarticle&id_article=220&lang=fr) I defined a dummy URI that points to a directory protected by the module and saved it as a redirect URI in the client config on the OP

When I launch the application after deployment, I am redirected to authentication. But after authentication, I get 500 errors on loading static files

Any idea please ?

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
