### ISSUE TITLE
construction of shm cache from the conf pool

### ISSUE THREAD

**Issue by smanolache** [zmartzone/mod_auth_openidc#824]
Hello,

I suggest to construct the `oidc_cache_cfg_shm_t *context`, `context->mutex`, and `context->shm` from the `s->process->pconf`.

Otherwise a new cache (context, mutex, shm) is constructed each time the configuration of the apache server is reloaded. They are freed only when the server is shutdown and the process pool is cleared.

**Comment by smanolache** [comment]
Thanks for accepting the suggestion.

I think, however, that we could change to `pconf` in `apr_shm_create` called from `oidc_cache_shm_post_config`.

**Comment by zandbelt** [comment]
ok, see https://github.com/zmartzone/mod_auth_openidc/commit/2e97c4c4e7f9ce698f138bfea0da05242987153a
