### ISSUE TITLE
Support for Keycloak Role permission

### ISSUE THREAD

**Issue by bakousylla** [zmartzone/mod_auth_openidc#842]
Hello,

I want to thanks for this great work!

We are facing the same issue than here : https://github.com/zmartzone/mod_auth_openidc/issues/297

Keycloak OAuth2 server send user's roles:

in the access token,
in the json structure : realm_access.roles[]
So we would like to have a base url filtered on a specific role, something like :
<Location />
AuthType openid-connect
Require valid-user
Require claim realm_access.roles:MY_APP_ROLE
</Location>

But it's not working and all not authorized users can access on my application. Could you have the solution for this issue ?
Thanks on advance.

Environment
Name        : mod_auth_openidc
Arch        : x86_64
Version     : 2.4.11.1
Release     : 1.el7

Name        : httpd
Arch        : x86_64
Version     : 2.4.52
Release     : 1.amzn2

Operating System: Amazon Linux 2
Kernel: Linux 4.14.273-207.502.amzn2.x86_64

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
