### ISSUE TITLE
Typo or unknown dependency.

### ISSUE THREAD

**Issue by frankenstein91** [zmartzone/mod_auth_openidc#857]
https://github.com/zmartzone/mod_auth_openidc/blob/1a5e2a908b6913adf6694226b76398642d6da2ab/INSTALL#L19

Hello I need help with the above line. Unfortunately I do not know a pcre3 and I can not find a source. I therefore suspect it is a mistake and it is meant pcre2, could you please confirm this for me?

Thank you

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
