### ISSUE TITLE
redirection after code validation

### ISSUE THREAD

**Issue by MohamedAnouar** [zmartzone/mod_auth_openidc#866]
Hello, 

I had my configuration working perfectly on apache 2.4.46, but once I updated the config to 2.4.53, I noticed an issue that is linked to the last redirection after code validation. https://example.com/?code... : code validation is OK. 
The user got redirected to https://example.com:8080/app instead of https://example:443/app the external route (exposed via openshift). OIDC Module is forcing the use of virtual host port instead of the ServerName. 
Normally we expect after all the authentication is good that the user should be redirected to /app without any dns. I tried modifying the location header for the last redirection but without success. Do you have a fix?

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
