### ISSUE TITLE
Warning in parsing JSON with null-values

### ISSUE THREAD

**Issue by chrille69** [zmartzone/mod_auth_openidc#912]
By parsing a JSON-string like

`"{\"roles\":[
{\"uuid\":\"f66aee04-c335-4299-9cfe-ca7176cc0213\",\"id\":\"ROLE_ADMIN\",\"displayName\":\"Administrator\"},
{\"uuid\":\"c9b85a22-1a6c-46e1-99eb-36cb88001fda\",\"id\":\"ROLE_TEACHER\",\"displayName\":\"Lehrer\"},
{\"uuid\":null,\"id\":\"ROLE_USER\",\"displayName\":\"Benutzer\"}]}"`

mod_auth_openidc shows a warning

`oidc_util_set_app_infos: unhandled in-array JSON object type [0] for key "roles" when parsing claims array elements`

This is probably the null-value of uuid.

It results in an empty claim header/environmentvariable.

Apache 2.4.18
mod_auth_openidc 1.8.5

Greetings
Christian

**Comment by zandbelt** [comment]
https://github.com/zmartzone/mod_auth_openidc/wiki#20-why-is-my-ticket-closed-as-invalid
